_information-bearing-object_Messageservice.wsdl	1.0
objectperson__service.wsdl	0.6531012654304504
recommendedprice_coffeewithwhiskeycontentbearingobject_service.wsdl	0.5738842487335205
recommendedprice_contentbearingobjectwhiskeycoffee_service.wsdl	0.5738842487335205
