_lecturer-in-academiaMunchenUniversity_service.wsdl	1.0
_lecturer-in-academiaSaarlandUniversity_service.wsdl	1.0
_lecturer-in-academiaZambiaUniversity_service.wsdl	1.0
university_lecturer-in-academiaCurrentSemmester_service.wsdl	0.9831716418266296
university_lecturer-in-academia_Recommendservice.wsdl	0.9831716418266296
university_lecturer-in-academia_service.wsdl	0.9831716418266296
organization_lecturer-in-academia_service.wsdl	0.9787741899490356
educational-organization_lecturer-in-academia_service.wsdl	0.9513499140739441
learning-centred-organization_lecturer-in-academia_service.wsdl	0.9486703276634216
university_senior-lecturer-in-academia_service.wsdl	0.9343188405036926
higher-educational-organization_lecturer-in-academia_MostUsedservice.wsdl	0.9294008612632751
higher-educational-organization_lecturer-in-academia_service.wsdl	0.9294008612632751
university_professor-in-academia_service.wsdl	0.9047597646713257
higher-educational-organization_professor-in-academia_Pioneerservice.wsdl	0.8601474165916443
higher-educational-organization_professor-in-academia_service.wsdl	0.8601474165916443
university_research-fellow-in-academia_service.wsdl	0.7126535773277283
professor-in-academia_address_service.wsdl	0.6910722255706787
higher-educational-organization_senior-research-fellow-in-academia_Firstservice.wsdl	0.6498194932937622
higher-educational-organization_senior-research-fellow-in-academia_service.wsdl	0.6498194932937622
researcher-in-academia_abstract-information_service.wsdl	0.6469793915748596
researcher-in-academia_address_service.wsdl	0.6190736889839172
researcher-in-academia_address_TREEservice.wsdl	0.6190736889839172
researcher-in-academia_address_ZOOservice.wsdl	0.6190736889839172
university_researcher_service.wsdl	0.6075319051742554
research-assistant-in-academia_address_service.wsdl	0.5842962861061096
sfnovel_authorauthor_BookOntoservice.wsdl	0.5121870636940002
research-fellow-in-academia_publication-reference_service.wsdl	0.5096889734268188
sciencefictionnovel_author_MyOntoservice.wsdl	0.502295970916748
