_skilledoccupation_BMWservice.wsdl	1.0
country_skilledoccupation_jobsservice.wsdl	0.9767000675201416
country_skilledoccupation_service.wsdl	0.9767000675201416
company_skilledoccupation_service.wsdl	0.9732177257537842
city_skilledoccupation_service.wsdl	0.9690092206001282
companycountry_skilledoccupation_service.wsdl	0.9467662572860718
government-organization_skilledoccupation_service.wsdl	0.9396426677703857
citycountry_skilledoccupation_service.wsdl	0.9374631643295288
public-companycountry_skilledoccupation_service.wsdl	0.9122849106788635
profit-organization_skilledoccupation_service.wsdl	0.8981664776802063
geopolitical-entity_skilledoccupation_service.wsdl	0.8952941298484802
country_companyskilledoccupation_service.wsdl	0.8779296875
country_organizationskilledoccupation_service.wsdl	0.8707883358001709
country_corporationskilledoccupation_service.wsdl	0.8594525456428528
geopolitical-entity_companyskilledoccupation_service.wsdl	0.8419413566589355
geographical-region_companyskilledoccupation_service.wsdl	0.8367996215820312
geographical-region_organizationskilledoccupation_JobService.wsdl	0.8345676064491272
geographical-region_organizationskilledoccupation_service.wsdl	0.8345676064491272
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.834354043006897
geographical-region_corporationskilledoccupation_service.wsdl	0.8259710669517517
country_skilledoccupationtimemeasure_service.wsdl	0.8223094344139099
geopolitical-entity_skilledoccupationcompany_service.wsdl	0.8200033903121948
geopolitical-entity_corporationskilledoccupation_service.wsdl	0.811025083065033
country_skilledoccupationparttimeposition_JobService.wsdl	0.8024142980575562
country_skilledoccupationparttimeposition_service.wsdl	0.8024142980575562
country_skilledoccupationfulltimeposition_service.wsdl	0.800883948802948
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.8008721470832825
country_skilledoccupationtimeduration_JobService.wsdl	0.7936587333679199
country_skilledoccupationtimeduration_service.wsdl	0.7936587333679199
DJob_service.wsdl	0.7936587333679199
municipal-unit_skilledoccupationtimemeasure_service.wsdl	0.7928317189216614
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.7770476937294006
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.7770476937294006
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.7769084572792053
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.7769084572792053
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.7732399702072144
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.7716423273086548
