_videomediaBBC_service.wsdl	1.0
_videomediaSaturn_service.wsdl	1.0
_videomediaSmithLee_service.wsdl	1.0
title_videomediaMM_service.wsdl	0.8900653719902039
title_videomedia_service.wsdl	0.8900653719902039
_filmvideomediaDiscoveryChannel_service.wsdl	0.8262496590614319
linguisticexpression_videomedia_service.wsdl	0.7721952199935913
title_obtainablevideomedia_service.wsdl	0.6515601277351379
title_videomediapricequality_service.wsdl	0.6051968336105347
shoppingmall_maxpricedigital-video_service.wsdl	0.5971308350563049
title_videomediarecommendedprice_service.wsdl	0.5503828525543213
title_videomediamaxpricequality_service.wsdl	0.5417807698249817
title_videomediarecommendedpricequality_service.wsdl	0.5285601615905762
title_videomediataxedpricequality_service.wsdl	0.5009579658508301
