academic-degree_scholarship_GermanGovservice.wsdl	1.0
academic-degreegovernment_scholarship_service.wsdl	0.9748214483261108
degree_scholarship_GermanGovservice.wsdl	0.9683455228805542
degreegovernment_scholarship_service.wsdl	0.9465351104736328
governmentdegree_scholarship_service.wsdl	0.9465351104736328
governmentdegree_scholarship_TheBestservice.wsdl	0.9465351104736328
degreenationalgovernment_scholarship_service.wsdl	0.915433406829834
degreegovernmentorganization_scholarship_service.wsdl	0.9143442511558533
government_scholarship_service.wsdl	0.8686589598655701
academic-degree_scholarshipduration_GermanGovservice.wsdl	0.8592562079429626
award_scholarship_GermanGovservice.wsdl	0.8481682538986206
governmentaward_scholarship_service.wsdl	0.836814820766449
nationalgovernment_scholarship_service.wsdl	0.830443799495697
governmentorganization_scholarship_service.wsdl	0.8279865980148315
governmentdegree_scholarshipquantity_service.wsdl	0.8033435940742493
degree_scholarshipduration_GermanGovservice.wsdl	0.7961917519569397
government_scholarshiporganization_service.wsdl	0.7555625438690186
award_scholarshipduration_GermanGovservice.wsdl	0.7193737030029297
award_scholarshipduration_SwissGovservice.wsdl	0.7193737030029297
nationalgovernment_scholarshipquantity_service.wsdl	0.7131696939468384
academic-degree_funding_GermanGovservice.wsdl	0.636501669883728
nationalgovernment_scholarshipquantityduration_service.wsdl	0.6026373505592346
university_academic-support-staff_service.wsdl	0.5929259061813354
academic-degreegovernment_funding_service.wsdl	0.5871759653091431
academic-degreegovernmentorganization_funding_service.wsdl	0.5866085290908813
nationalgovernment_physical-quantityscholarshiplandarea_service.wsdl	0.5657357573509216
academic-degree_fundingduration_GermanGovservice.wsdl	0.5172058343887329
academic-degree_lending_GermanGovservice.wsdl	0.515938401222229
academic-degreegovernmentorganization_lending_service.wsdl	0.5002061724662781
