academic-degreegovernment_scholarship_service.wsdl	1.0
academic-degree_scholarship_GermanGovservice.wsdl	0.9748214483261108
degreegovernment_scholarship_service.wsdl	0.9717849493026733
governmentdegree_scholarship_service.wsdl	0.9717849493026733
governmentdegree_scholarship_TheBestservice.wsdl	0.9717849493026733
degreenationalgovernment_scholarship_service.wsdl	0.9540132880210876
degreegovernmentorganization_scholarship_service.wsdl	0.9477932453155518
degree_scholarship_GermanGovservice.wsdl	0.9338266849517822
government_scholarship_service.wsdl	0.905122697353363
nationalgovernment_scholarship_service.wsdl	0.8808006048202515
governmentorganization_scholarship_service.wsdl	0.8721482157707214
governmentaward_scholarship_service.wsdl	0.860325276851654
academic-degree_scholarshipduration_GermanGovservice.wsdl	0.8457252979278564
governmentdegree_scholarshipquantity_service.wsdl	0.83487868309021
award_scholarship_GermanGovservice.wsdl	0.8136552572250366
government_scholarshiporganization_service.wsdl	0.8032581210136414
degree_scholarshipduration_GermanGovservice.wsdl	0.7772829532623291
nationalgovernment_scholarshipquantity_service.wsdl	0.7649680376052856
award_scholarshipduration_GermanGovservice.wsdl	0.6996859908103943
award_scholarshipduration_SwissGovservice.wsdl	0.6996859908103943
academic-degreegovernmentorganization_funding_service.wsdl	0.6800509095191956
academic-degreegovernment_funding_service.wsdl	0.678726077079773
academic-degree_funding_GermanGovservice.wsdl	0.6774964928627014
nationalgovernment_scholarshipquantityduration_service.wsdl	0.6510125994682312
university_academic-support-staff_service.wsdl	0.6301421523094177
nationalgovernment_physical-quantityscholarshiplandarea_service.wsdl	0.6135498285293579
governmentdegree_givingback_service.wsdl	0.6003392338752747
academic-degreegovernmentorganization_lending_service.wsdl	0.5907378792762756
academic-degreegovernment_lending_service.wsdl	0.5720131397247314
degreegovernment_funding_service.wsdl	0.5592339634895325
academic-degree_fundingduration_GermanGovservice.wsdl	0.5562523007392883
academic-degree_lending_GermanGovservice.wsdl	0.5541914105415344
academic-degreegovernmentorganization_unilateralgiving_service.wsdl	0.5499783754348755
degree_funding_GermanGovservice.wsdl	0.5429368019104004
university_senior-lecturer-in-academia_service.wsdl	0.5279887318611145
academic-degreegovernment_unilateralgiving_service.wsdl	0.524539053440094
higher-educational-organization_lecturer-in-academia_MostUsedservice.wsdl	0.5227962136268616
higher-educational-organization_lecturer-in-academia_service.wsdl	0.5227962136268616
university_lecturer-in-academiaCurrentSemmester_service.wsdl	0.5198884606361389
university_lecturer-in-academia_Recommendservice.wsdl	0.5198884606361389
university_lecturer-in-academia_service.wsdl	0.5198884606361389
educational-organization_lecturer-in-academia_service.wsdl	0.511110246181488
higher-educational-organization_professor-in-academia_Pioneerservice.wsdl	0.5024605393409729
higher-educational-organization_professor-in-academia_service.wsdl	0.5024605393409729
governmentdegree_welfare_service.wsdl	0.5000870227813721
