CheckPersonnelAvailability_service.wsdl	1.0
CheckEquipmentAvailability_service.wsdl	0.9217391014099121
CheckRoomAvailability_service.wsdl	0.8984717130661011
CheckHospitalAvailability_service.wsdl	0.894180417060852
ProvideMedicalTransportInformation_service.wsdl	0.500789225101471
