companycountry_skilledoccupation_service.wsdl	1.0
company_skilledoccupation_service.wsdl	0.9787654280662537
public-companycountry_skilledoccupation_service.wsdl	0.9767972230911255
country_skilledoccupation_jobsservice.wsdl	0.9764636158943176
country_skilledoccupation_service.wsdl	0.9764636158943176
country_companyskilledoccupation_service.wsdl	0.9743261337280273
citycountry_skilledoccupation_service.wsdl	0.9589921832084656
_skilledoccupation_BMWservice.wsdl	0.9467662572860718
government-organization_skilledoccupation_service.wsdl	0.9431957006454468
city_skilledoccupation_service.wsdl	0.9425658583641052
geographical-region_companyskilledoccupation_service.wsdl	0.9257221817970276
geopolitical-entity_companyskilledoccupation_service.wsdl	0.922759473323822
country_corporationskilledoccupation_service.wsdl	0.922042727470398
country_organizationskilledoccupation_service.wsdl	0.9099251627922058
profit-organization_skilledoccupation_service.wsdl	0.9033385515213013
geopolitical-entity_skilledoccupationcompany_service.wsdl	0.8945650458335876
geographical-region_corporationskilledoccupation_service.wsdl	0.8845773339271545
geopolitical-entity_skilledoccupation_service.wsdl	0.8840647339820862
geographical-region_organizationskilledoccupation_JobService.wsdl	0.8714582324028015
geographical-region_organizationskilledoccupation_service.wsdl	0.8714582324028015
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.8636309504508972
geopolitical-entity_corporationskilledoccupation_service.wsdl	0.8609110116958618
country_skilledoccupationtimemeasure_service.wsdl	0.8399667739868164
country_skilledoccupationparttimeposition_JobService.wsdl	0.8282619118690491
country_skilledoccupationparttimeposition_service.wsdl	0.8282619118690491
country_skilledoccupationfulltimeposition_service.wsdl	0.8212663531303406
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.8082356452941895
country_skilledoccupationtimeduration_JobService.wsdl	0.8024706244468689
country_skilledoccupationtimeduration_service.wsdl	0.8024706244468689
DJob_service.wsdl	0.8024706244468689
municipal-unit_skilledoccupationtimemeasure_service.wsdl	0.801591157913208
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.7925013303756714
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.7925013303756714
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.7878466248512268
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.7878466248512268
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.7729354500770569
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.7723388671875
geographical-region_companyprofession_service.wsdl	0.5517422556877136
country_companyprofession_service.wsdl	0.5391353964805603
geographical-region_corporationprofession_service.wsdl	0.538305938243866
geopolitical-entity_companyprofession_service.wsdl	0.5322414636611938
country_corporationprofession_service.wsdl	0.5232929587364197
geopolitical-entity_professionfulltimeposition_service.wsdl	0.517768383026123
government-organization_profession_service.wsdl	0.5172098278999329
geopolitical-entity_professionparttimeposition_service.wsdl	0.5132895708084106
country_professionfulltimeposition_service.wsdl	0.5125110149383545
geopolitical-entity_professiontimemeasure_service.wsdl	0.5083438158035278
country_professionparttimeposition_service.wsdl	0.5079389810562134
geographical-region_organizationprofession_service.wsdl	0.506990909576416
country_profession_service.wsdl	0.504696786403656
geopolitical-entity_profession_service.wsdl	0.5024322867393494
