company_skilledoccupation_service.wsdl	1.0
companycountry_skilledoccupation_service.wsdl	0.9787654280662537
_skilledoccupation_BMWservice.wsdl	0.9732177257537842
country_skilledoccupation_jobsservice.wsdl	0.9585353136062622
country_skilledoccupation_service.wsdl	0.9585353136062622
city_skilledoccupation_service.wsdl	0.9531228542327881
country_companyskilledoccupation_service.wsdl	0.95244961977005
public-companycountry_skilledoccupation_service.wsdl	0.9504983425140381
government-organization_skilledoccupation_service.wsdl	0.9438377022743225
citycountry_skilledoccupation_service.wsdl	0.9291737675666809
geopolitical-entity_companyskilledoccupation_service.wsdl	0.9157638549804688
profit-organization_skilledoccupation_service.wsdl	0.9136846661567688
geographical-region_companyskilledoccupation_service.wsdl	0.9072368741035461
country_corporationskilledoccupation_service.wsdl	0.8995871543884277
geopolitical-entity_skilledoccupationcompany_service.wsdl	0.8933190107345581
geopolitical-entity_skilledoccupation_service.wsdl	0.8897364735603333
country_organizationskilledoccupation_service.wsdl	0.880483865737915
geographical-region_corporationskilledoccupation_service.wsdl	0.8652580976486206
geopolitical-entity_corporationskilledoccupation_service.wsdl	0.8525863289833069
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.8488560914993286
geographical-region_organizationskilledoccupation_JobService.wsdl	0.8457628488540649
geographical-region_organizationskilledoccupation_service.wsdl	0.8457628488540649
country_skilledoccupationtimemeasure_service.wsdl	0.8131077885627747
country_skilledoccupationfulltimeposition_service.wsdl	0.8021686673164368
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.8001986742019653
country_skilledoccupationparttimeposition_JobService.wsdl	0.7992792725563049
country_skilledoccupationparttimeposition_service.wsdl	0.7992792725563049
municipal-unit_skilledoccupationtimemeasure_service.wsdl	0.7991369366645813
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.785064160823822
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.785064160823822
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.7810078859329224
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.7810078859329224
country_skilledoccupationtimeduration_JobService.wsdl	0.7807863354682922
country_skilledoccupationtimeduration_service.wsdl	0.7807863354682922
DJob_service.wsdl	0.7807863354682922
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.7738689184188843
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.7689217329025269
