country_professionparttimeposition_service.wsdl	1.0
municipal-unit_professionparttimeposition_service.wsdl	0.9483723640441895
geopolitical-entity_professionparttimeposition_service.wsdl	0.9272351264953613
country_professionfulltimeposition_service.wsdl	0.9135807752609253
municipal-unit_professionfulltimeposition_service.wsdl	0.8618417978286743
geopolitical-entity_professionfulltimeposition_service.wsdl	0.8491848111152649
country_skilledoccupationparttimeposition_JobService.wsdl	0.7975119352340698
country_skilledoccupationparttimeposition_service.wsdl	0.7975119352340698
country_professiontimemeasure_service.wsdl	0.7759259939193726
country_profession_service.wsdl	0.7646207213401794
country_occupationaltradeparttimeposition_service.wsdl	0.7505584359169006
country_professiontimeduration_Service.wsdl	0.7494900822639465
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.734487771987915
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.734487771987915
geopolitical-entity_professiontimemeasure_service.wsdl	0.7279052734375
country_organizationprofession_service.wsdl	0.7269371151924133
government-organization_profession_service.wsdl	0.7208173871040344
country_sportsposition_service.wsdl	0.7198415398597717
country_skilledoccupationfulltimeposition_service.wsdl	0.7159707546234131
municipal-unit_professiontimemeasure_service.wsdl	0.7127887010574341
company_profession_service.wsdl	0.7057730555534363
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.7052799463272095
geopolitical-entity_professiontimeduration_service.wsdl	0.7009039521217346
municipal-unit_professiontimeduration_service.wsdl	0.696223258972168
country_companyprofession_service.wsdl	0.6960294842720032
geographical-region_organizationprofession_service.wsdl	0.6927778720855713
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.6887961030006409
country_corporationprofession_service.wsdl	0.6753997802734375
profit-organization_profession_service.wsdl	0.6659011244773865
geopolitical-entity_profession_service.wsdl	0.6653904318809509
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.6624058485031128
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.6624058485031128
geographical-region_companyprofession_service.wsdl	0.6605256199836731
country_occupationaltradefulltimeposition_service.wsdl	0.6592024564743042
geopolitical-entity_organizationprofession_service.wsdl	0.650592029094696
geographical-region_corporationprofession_service.wsdl	0.6460446119308472
geopolitical-entity_companyprofession_service.wsdl	0.6224938035011292
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.620378315448761
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.6091667413711548
_professiongeographical-region_USservice.wsdl	0.6064037084579468
geopolitical-entity_corporationprofession_service.wsdl	0.5827084183692932
geopolitical-entity_weatherseasontimeposition_service.wsdl	0.5773343443870544
country_skilledoccupationtimemeasure_service.wsdl	0.5740746855735779
country_skilledoccupationtimeduration_JobService.wsdl	0.555541455745697
country_skilledoccupationtimeduration_service.wsdl	0.555541455745697
DJob_service.wsdl	0.555541455745697
country_organizationskilledoccupation_service.wsdl	0.5485395193099976
geopolitical-entity_weatherseasonproposition_service.wsdl	0.5370123386383057
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.5338013768196106
municipal-unit_skilledoccupationtimemeasure_service.wsdl	0.5281564593315125
public-companycountry_skilledoccupation_service.wsdl	0.5245136022567749
geographical-region_organizationskilledoccupation_JobService.wsdl	0.5219263434410095
geographical-region_organizationskilledoccupation_service.wsdl	0.5219263434410095
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.5168574452400208
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.5155969262123108
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.5096742510795593
companycountry_skilledoccupation_service.wsdl	0.5079389810562134
citycountry_skilledoccupation_service.wsdl	0.5069355368614197
country_professionincometax_service.wsdl	0.5040322542190552
country_companyskilledoccupation_service.wsdl	0.5013274550437927
