country_companyprofession_service.wsdl	1.0
company_profession_service.wsdl	0.9512245655059814
geographical-region_companyprofession_service.wsdl	0.9137454032897949
country_profession_service.wsdl	0.884978175163269
country_corporationprofession_service.wsdl	0.8817815184593201
geopolitical-entity_companyprofession_service.wsdl	0.8736646771430969
government-organization_profession_service.wsdl	0.8601566553115845
country_organizationprofession_service.wsdl	0.8378407955169678
profit-organization_profession_service.wsdl	0.8226507902145386
geographical-region_corporationprofession_service.wsdl	0.8143500089645386
geographical-region_organizationprofession_service.wsdl	0.7747682929039001
geopolitical-entity_profession_service.wsdl	0.7512343525886536
geopolitical-entity_corporationprofession_service.wsdl	0.7442983984947205
geopolitical-entity_organizationprofession_service.wsdl	0.7357343435287476
country_professionparttimeposition_service.wsdl	0.6960294842720032
country_professiontimemeasure_service.wsdl	0.6928685903549194
country_professionfulltimeposition_service.wsdl	0.6833824515342712
municipal-unit_professionparttimeposition_service.wsdl	0.6751196384429932
municipal-unit_professionfulltimeposition_service.wsdl	0.6597087383270264
municipal-unit_professiontimemeasure_service.wsdl	0.6568533182144165
_professiongeographical-region_USservice.wsdl	0.6522632241249084
geopolitical-entity_professiontimemeasure_service.wsdl	0.6404486298561096
geopolitical-entity_professionparttimeposition_service.wsdl	0.639869749546051
country_professiontimeduration_Service.wsdl	0.6331763863563538
geopolitical-entity_professionfulltimeposition_service.wsdl	0.6289951801300049
country_companyskilledoccupation_service.wsdl	0.6083309650421143
municipal-unit_professiontimeduration_service.wsdl	0.6069671511650085
country_professionincometax_service.wsdl	0.5982365608215332
country_companyoccupationaltrade_service.wsdl	0.5935161113739014
geopolitical-entity_professiontimeduration_service.wsdl	0.5837607383728027
public-companycountry_skilledoccupation_service.wsdl	0.5643002390861511
geographical-region_companyskilledoccupation_service.wsdl	0.5620220899581909
geopolitical-entity_companyskilledoccupation_service.wsdl	0.5563338994979858
companycountry_skilledoccupation_service.wsdl	0.5391353964805603
geopolitical-entity_skilledoccupationcompany_service.wsdl	0.5374518036842346
geographical-region_companyoccupationaltrade_service.wsdl	0.5327831506729126
country_corporationskilledoccupation_service.wsdl	0.5238128304481506
country_corporationoccupationaltrade_service.wsdl	0.5217505693435669
geopolitical-entity_companyoccupationaltrade_service.wsdl	0.5209516286849976
country_organizationskilledoccupation_service.wsdl	0.5092429518699646
country_organizationoccupationaltrade_service.wsdl	0.5063941478729248
