country_sportsposition_service.wsdl	1.0
country_professionparttimeposition_service.wsdl	0.7198415398597717
geopolitical-entity_professionparttimeposition_service.wsdl	0.6792504191398621
country_professionfulltimeposition_service.wsdl	0.6657701730728149
municipal-unit_professionparttimeposition_service.wsdl	0.6647270917892456
country_skilledoccupationparttimeposition_JobService.wsdl	0.6453970670700073
country_skilledoccupationparttimeposition_service.wsdl	0.6453970670700073
countrycity_sportshotel_service.wsdl	0.6311189532279968
geopolitical-entity_professionfulltimeposition_service.wsdl	0.6304535865783691
personcountrycity_sportshotel_service.wsdl	0.6273109912872314
municipal-unit_professionfulltimeposition_service.wsdl	0.6103295683860779
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.603367030620575
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.603367030620575
country_skilledoccupationfulltimeposition_service.wsdl	0.5924748778343201
geopolitical-entity_weatherseasonproposition_service.wsdl	0.5792865753173828
geopolitical-entity_weatherseasontimeposition_service.wsdl	0.5743845701217651
country_occupationaltradeparttimeposition_service.wsdl	0.5718100666999817
sportsorganization_destination_service.wsdl	0.571358859539032
sports_nationalpark_service.wsdl	0.5575873255729675
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.5567893385887146
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.5567893385887146
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.5348132252693176
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.5347943305969238
country_professiontimemeasure_service.wsdl	0.5323306322097778
sports_destination_service.wsdl	0.5318089723587036
sports_town_service.wsdl	0.5249468684196472
country_organizationprofession_service.wsdl	0.5238317251205444
country_profession_service.wsdl	0.5171560049057007
geopolitical-entity_professiontimemeasure_service.wsdl	0.5135089755058289
country_occupationaltradefulltimeposition_service.wsdl	0.512502133846283
geographical-region_organizationprofession_service.wsdl	0.507899284362793
sportslegal-agent_destination_service.wsdl	0.5027589201927185
