country_companyoccupationaltrade_service.wsdl	1.0
geographical-region_companyoccupationaltrade_service.wsdl	0.94784015417099
country_occupationaltrade_service.wsdl	0.9238664507865906
country_corporationoccupationaltrade_service.wsdl	0.9186801314353943
geopolitical-entity_companyoccupationaltrade_service.wsdl	0.9178966879844666
country_organizationoccupationaltrade_service.wsdl	0.883237898349762
geographical-region_corporationoccupationaltrade_service.wsdl	0.8810200095176697
geographical-region_organizationoccupationaltrade_service.wsdl	0.8469408750534058
geopolitical-entity_occupationaltrade_service.wsdl	0.8418145775794983
geopolitical-entity_corporationoccupationaltrade_service.wsdl	0.8245911598205566
geopolitical-entity_organizationoccupationaltrade_service.wsdl	0.8125808238983154
country_occupationaltradetimemeasure_Service.wsdl	0.7855813503265381
municipal-unit_occupationaltradetimemeasure_service.wsdl	0.7609323263168335
country_occupationaltradefulltimeposition_service.wsdl	0.7585861682891846
country_occupationaltradeparttimeposition_service.wsdl	0.7580851912498474
geopolitical-entity_occupationaltradetimemeasure_service.wsdl	0.7568680047988892
country_occupationaltradetimeduration_Service.wsdl	0.7444377541542053
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.7423222064971924
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.7419701814651489
municipal-unit_occupationaltradetimeduration_service.wsdl	0.7276622653007507
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.7262241244316101
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.7232317924499512
geopolitical-entity_occupationaltradetimeduration_service.wsdl	0.7179113626480103
geographical-region_companyprofession_service.wsdl	0.6182687878608704
country_companyprofession_service.wsdl	0.5935161113739014
geopolitical-entity_companyprofession_service.wsdl	0.5734806656837463
country_companyskilledoccupation_service.wsdl	0.5523041486740112
geographical-region_companyskilledoccupation_service.wsdl	0.5502183437347412
geographical-region_corporationprofession_service.wsdl	0.5478065013885498
geopolitical-entity_companyskilledoccupation_service.wsdl	0.5355961322784424
country_corporationprofession_service.wsdl	0.5156300663948059
geopolitical-entity_skilledoccupationcompany_service.wsdl	0.5130024552345276
public-companycountry_skilledoccupation_service.wsdl	0.5027995109558105
