country_organizationoccupationaltrade_service.wsdl	1.0
geographical-region_organizationoccupationaltrade_service.wsdl	0.9522654414176941
geopolitical-entity_organizationoccupationaltrade_service.wsdl	0.9267077445983887
country_occupationaltrade_service.wsdl	0.9152480959892273
country_corporationoccupationaltrade_service.wsdl	0.8864502310752869
country_companyoccupationaltrade_service.wsdl	0.883237898349762
geographical-region_corporationoccupationaltrade_service.wsdl	0.8541637063026428
geopolitical-entity_occupationaltrade_service.wsdl	0.8497055172920227
geographical-region_companyoccupationaltrade_service.wsdl	0.84683758020401
geopolitical-entity_companyoccupationaltrade_service.wsdl	0.8296802043914795
geopolitical-entity_corporationoccupationaltrade_service.wsdl	0.809622049331665
country_occupationaltradetimemeasure_Service.wsdl	0.784667432308197
country_occupationaltradeparttimeposition_service.wsdl	0.7804449796676636
geopolitical-entity_occupationaltradetimemeasure_service.wsdl	0.7681699395179749
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.7633947134017944
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.7546358704566956
country_occupationaltradefulltimeposition_service.wsdl	0.7533293962478638
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.7379061579704285
municipal-unit_occupationaltradetimemeasure_service.wsdl	0.7364466190338135
country_occupationaltradetimeduration_Service.wsdl	0.732765793800354
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.7324925661087036
geopolitical-entity_occupationaltradetimeduration_service.wsdl	0.7189551591873169
municipal-unit_occupationaltradetimeduration_service.wsdl	0.6936417818069458
geographical-region_organizationprofession_service.wsdl	0.6641247272491455
country_organizationprofession_service.wsdl	0.6426796317100525
geopolitical-entity_organizationprofession_service.wsdl	0.6283544301986694
country_organizationskilledoccupation_service.wsdl	0.6022094488143921
geographical-region_organizationskilledoccupation_JobService.wsdl	0.5986708402633667
geographical-region_organizationskilledoccupation_service.wsdl	0.5986708402633667
government-organization_profession_service.wsdl	0.5915710926055908
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.5887326598167419
profit-organization_profession_service.wsdl	0.5793449878692627
geographical-region_corporationprofession_service.wsdl	0.5618657469749451
geographical-region_companyprofession_service.wsdl	0.5420808792114258
country_corporationprofession_service.wsdl	0.528635561466217
profit-organization_skilledoccupation_service.wsdl	0.5162724852561951
_professiongeographical-region_USservice.wsdl	0.5150901079177856
government_scholarshiporganization_service.wsdl	0.5145918130874634
geopolitical-entity_companyprofession_service.wsdl	0.5141283273696899
geopolitical-entity_corporationprofession_service.wsdl	0.5103146433830261
country_companyprofession_service.wsdl	0.5063941478729248
government-organization_skilledoccupation_service.wsdl	0.5012121796607971
