country_profession_service.wsdl	1.0
company_profession_service.wsdl	0.9276639223098755
government-organization_profession_service.wsdl	0.9066004753112793
country_organizationprofession_service.wsdl	0.8929080367088318
country_companyprofession_service.wsdl	0.884978175163269
country_corporationprofession_service.wsdl	0.8484734892845154
profit-organization_profession_service.wsdl	0.8385990262031555
geographical-region_organizationprofession_service.wsdl	0.8120484352111816
geopolitical-entity_profession_service.wsdl	0.8081626892089844
geographical-region_companyprofession_service.wsdl	0.7959678769111633
geographical-region_corporationprofession_service.wsdl	0.7707651853561401
country_professiontimemeasure_service.wsdl	0.770089864730835
country_professionparttimeposition_service.wsdl	0.7646207213401794
geopolitical-entity_organizationprofession_service.wsdl	0.7538301348686218
geopolitical-entity_companyprofession_service.wsdl	0.7409550547599792
country_professionfulltimeposition_service.wsdl	0.7349140644073486
country_professiontimeduration_Service.wsdl	0.7114777565002441
_professiongeographical-region_USservice.wsdl	0.7039613127708435
municipal-unit_professionparttimeposition_service.wsdl	0.7016512155532837
geopolitical-entity_corporationprofession_service.wsdl	0.6867874264717102
municipal-unit_professiontimemeasure_service.wsdl	0.6824462413787842
geopolitical-entity_professiontimemeasure_service.wsdl	0.6821331977844238
geopolitical-entity_professionparttimeposition_service.wsdl	0.6771984100341797
municipal-unit_professionfulltimeposition_service.wsdl	0.6701677441596985
geopolitical-entity_professionfulltimeposition_service.wsdl	0.6509084701538086
municipal-unit_professiontimeduration_service.wsdl	0.6358683109283447
geopolitical-entity_professiontimeduration_service.wsdl	0.6275214552879333
country_professionincometax_service.wsdl	0.5896390080451965
country_organizationskilledoccupation_service.wsdl	0.5317351222038269
public-companycountry_skilledoccupation_service.wsdl	0.5233643054962158
country_sportsposition_service.wsdl	0.5171560049057007
companycountry_skilledoccupation_service.wsdl	0.504696786403656
citycountry_skilledoccupation_service.wsdl	0.5014994144439697
