country_lightning_service.wsdl	1.0
geographical-region_lightning_service.wsdl	0.8723767995834351
municipal-unit_lightning_service.wsdl	0.8446613550186157
geopolitical-entity_lightning_service.wsdl	0.8024874329566956
