country_skilledoccupationtimeduration_JobService.wsdl	1.0
country_skilledoccupationtimeduration_service.wsdl	1.0
DJob_service.wsdl	1.0
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.9570239186286926
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.9414709210395813
country_skilledoccupationtimemeasure_service.wsdl	0.8442942500114441
country_skilledoccupationfulltimeposition_service.wsdl	0.8286839723587036
country_skilledoccupationparttimeposition_JobService.wsdl	0.8203471899032593
country_skilledoccupationparttimeposition_service.wsdl	0.8203471899032593
country_skilledoccupation_jobsservice.wsdl	0.8201173543930054
country_skilledoccupation_service.wsdl	0.8201173543930054
citycountry_skilledoccupation_service.wsdl	0.8054603338241577
companycountry_skilledoccupation_service.wsdl	0.8024706244468689
municipal-unit_skilledoccupationtimemeasure_service.wsdl	0.8011600971221924
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.8009942770004272
_skilledoccupation_BMWservice.wsdl	0.7936587333679199
city_skilledoccupation_service.wsdl	0.7902502417564392
public-companycountry_skilledoccupation_service.wsdl	0.7898498177528381
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.7846167683601379
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.7846167683601379
company_skilledoccupation_service.wsdl	0.7807863354682922
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.7752293348312378
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.7752293348312378
government-organization_skilledoccupation_service.wsdl	0.7716963291168213
country_professiontimeduration_Service.wsdl	0.7687137126922607
country_companyskilledoccupation_service.wsdl	0.7579189538955688
country_organizationskilledoccupation_service.wsdl	0.7458995580673218
geopolitical-entity_professiontimeduration_service.wsdl	0.7443822026252747
geopolitical-entity_skilledoccupation_service.wsdl	0.737784206867218
geographical-region_companyskilledoccupation_service.wsdl	0.7348606586456299
municipal-unit_professiontimeduration_service.wsdl	0.7338474988937378
geographical-region_organizationskilledoccupation_JobService.wsdl	0.7268027067184448
geographical-region_organizationskilledoccupation_service.wsdl	0.7268027067184448
geopolitical-entity_companyskilledoccupation_service.wsdl	0.7171577215194702
profit-organization_skilledoccupation_service.wsdl	0.7171400189399719
country_corporationskilledoccupation_service.wsdl	0.7171210646629333
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.7059049606323242
geographical-region_corporationskilledoccupation_service.wsdl	0.701833188533783
country_occupationaltradetimeduration_Service.wsdl	0.6986621618270874
geopolitical-entity_skilledoccupationcompany_service.wsdl	0.6878108978271484
geopolitical-entity_occupationaltradetimeduration_service.wsdl	0.6695877909660339
geopolitical-entity_corporationskilledoccupation_service.wsdl	0.668986439704895
municipal-unit_occupationaltradetimeduration_service.wsdl	0.6672515273094177
organization_experimentingtimeduration_service.wsdl	0.655378520488739
citycountryduration__HotelReserveservice.wsdl	0.63608717918396
careorganization_diagnosticprocesstimeduration_service.wsdl	0.605924665927887
HDP2_service.wsdl	0.5930696725845337
hospital_diagnosticprocesstimeduration_service.wsdl	0.5930696725845337
nationalgovernment_scholarshipquantityduration_service.wsdl	0.5805156826972961
country_professionfulltimeposition_service.wsdl	0.5777461528778076
medicalclinic_diagnosticprocesstimeduration_service.wsdl	0.5682818293571472
geopolitical-entity_professionfulltimeposition_service.wsdl	0.5656020045280457
country_professiontimemeasure_service.wsdl	0.5624945759773254
degree_fundingduration_GermanGovservice.wsdl	0.5593533515930176
geopolitical-entity_professiontimemeasure_service.wsdl	0.5592429637908936
country_occupationaltradefulltimeposition_service.wsdl	0.5584881901741028
academic-degree_fundingduration_GermanGovservice.wsdl	0.5582699179649353
country_professionparttimeposition_service.wsdl	0.555541455745697
academic-degree_lendingduration_GermanGovservice.wsdl	0.5529466271400452
degree_lendingduration_GermanGovservice.wsdl	0.5506460070610046
country_occupationaltradeparttimeposition_service.wsdl	0.5500020980834961
municipal-unit_professionfulltimeposition_service.wsdl	0.5485221743583679
degree_scholarshipduration_GermanGovservice.wsdl	0.5478115677833557
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.5454621315002441
geopolitical-entity_professionparttimeposition_service.wsdl	0.5449037551879883
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.5386862754821777
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.5375866293907166
academic-degree_scholarshipduration_GermanGovservice.wsdl	0.5355137586593628
municipal-unit_professiontimemeasure_service.wsdl	0.5310803651809692
municipal-unit_professionparttimeposition_service.wsdl	0.5301527380943298
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.5292556881904602
country_occupationaltradetimemeasure_Service.wsdl	0.5245911478996277
geopolitical-entity_occupationaltradetimemeasure_service.wsdl	0.5128147006034851
award_lendingduration_GermanGovservice.wsdl	0.5067380666732788
award_fundingduration_GermanGovservice.wsdl	0.5065232515335083
getSunsetSunriseTwilightTime.wsdl	0.50545334815979
durationgeopolitical-entitycity_accommodation_service.wsdl	0.5038918256759644
