degree_lendingduration_GermanGovservice.wsdl	1.0
academic-degree_lendingduration_GermanGovservice.wsdl	0.9714342951774597
award_lendingduration_GermanGovservice.wsdl	0.918081521987915
degree_lending_GermanGovservice.wsdl	0.8043927550315857
degreegovernment_lending_service.wsdl	0.7849699258804321
academic-degree_lending_GermanGovservice.wsdl	0.7723644375801086
academic-degreegovernment_lending_service.wsdl	0.7570962905883789
academic-degreegovernmentorganization_lending_service.wsdl	0.7211419939994812
degree_fundingduration_GermanGovservice.wsdl	0.7000462412834167
government_lending_service.wsdl	0.6973555088043213
academic-degree_fundingduration_GermanGovservice.wsdl	0.6945127844810486
award_lending_GermanGovservice.wsdl	0.6758741140365601
nationalgovernment_lending_service.wsdl	0.6691348552703857
citygovernment_lending_service.wsdl	0.6676340103149414
degree_scholarshipduration_GermanGovservice.wsdl	0.6062718033790588
missilegovernment_lendingrange_service.wsdl	0.6060654520988464
award_fundingduration_GermanGovservice.wsdl	0.5974874496459961
academic-degree_scholarshipduration_GermanGovservice.wsdl	0.5957407355308533
missilegovernmentorganization_lendingrange_service.wsdl	0.5890713334083557
country_occupationaltradetimeduration_Service.wsdl	0.5831800699234009
municipal-unit_occupationaltradetimeduration_service.wsdl	0.5806669592857361
municipal-unit_professiontimeduration_service.wsdl	0.578956127166748
country_professiontimeduration_Service.wsdl	0.5772735476493835
geopolitical-entity_professiontimeduration_service.wsdl	0.5761610865592957
geopolitical-entity_occupationaltradetimeduration_service.wsdl	0.5704713463783264
ballisticmissilegovernment_lendingrange_service.wsdl	0.5596056580543518
country_skilledoccupationtimeduration_JobService.wsdl	0.5506460070610046
country_skilledoccupationtimeduration_service.wsdl	0.5506460070610046
DJob_service.wsdl	0.5506460070610046
nationalgovernment_scholarshipquantityduration_service.wsdl	0.5502006411552429
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.550073504447937
organization_experimentingtimeduration_service.wsdl	0.5469374656677246
ballisticmissilegovernmentorganization_lendingrange_service.wsdl	0.5443843603134155
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.5393250584602356
citycountryduration__HotelReserveservice.wsdl	0.5133730173110962
careorganization_diagnosticprocesstimeduration_service.wsdl	0.5036466121673584
