degree_scholarship_GermanGovservice.wsdl	1.0
academic-degree_scholarship_GermanGovservice.wsdl	0.9683455228805542
degreegovernment_scholarship_service.wsdl	0.9644511342048645
governmentdegree_scholarship_service.wsdl	0.9644511342048645
governmentdegree_scholarship_TheBestservice.wsdl	0.9644511342048645
academic-degreegovernment_scholarship_service.wsdl	0.9338266849517822
degreegovernmentorganization_scholarship_service.wsdl	0.92453932762146
degreenationalgovernment_scholarship_service.wsdl	0.9210813045501709
award_scholarship_GermanGovservice.wsdl	0.8837870955467224
government_scholarship_service.wsdl	0.8837276697158813
governmentaward_scholarship_service.wsdl	0.8591190576553345
governmentorganization_scholarship_service.wsdl	0.8343247175216675
nationalgovernment_scholarship_service.wsdl	0.8315212726593018
academic-degree_scholarshipduration_GermanGovservice.wsdl	0.830605685710907
degree_scholarshipduration_GermanGovservice.wsdl	0.8183110952377319
governmentdegree_scholarshipquantity_service.wsdl	0.8106334209442139
government_scholarshiporganization_service.wsdl	0.7550346851348877
award_scholarshipduration_GermanGovservice.wsdl	0.7453767657279968
award_scholarshipduration_SwissGovservice.wsdl	0.7453767657279968
nationalgovernment_scholarshipquantity_service.wsdl	0.7068390846252441
nationalgovernment_scholarshipquantityduration_service.wsdl	0.5952990651130676
academic-degree_funding_GermanGovservice.wsdl	0.5540343523025513
nationalgovernment_physical-quantityscholarshiplandarea_service.wsdl	0.551952064037323
academic-degreegovernmentorganization_funding_service.wsdl	0.5025201439857483
academic-degreegovernment_funding_service.wsdl	0.5013415217399597
