degreegovernmentorganization_scholarship_service.wsdl	1.0
degreegovernment_scholarship_service.wsdl	0.9698728919029236
governmentdegree_scholarship_service.wsdl	0.9698728919029236
governmentdegree_scholarship_TheBestservice.wsdl	0.9698728919029236
degreenationalgovernment_scholarship_service.wsdl	0.9541740417480469
academic-degreegovernment_scholarship_service.wsdl	0.9477932453155518
governmentorganization_scholarship_service.wsdl	0.9437469244003296
degree_scholarship_GermanGovservice.wsdl	0.92453932762146
government_scholarship_service.wsdl	0.9164412021636963
government_scholarshiporganization_service.wsdl	0.916420042514801
academic-degree_scholarship_GermanGovservice.wsdl	0.9143442511558533
nationalgovernment_scholarship_service.wsdl	0.8931844830513
governmentaward_scholarship_service.wsdl	0.8816980123519897
governmentdegree_scholarshipquantity_service.wsdl	0.834858775138855
award_scholarship_GermanGovservice.wsdl	0.8286730051040649
academic-degree_scholarshipduration_GermanGovservice.wsdl	0.7898209095001221
nationalgovernment_scholarshipquantity_service.wsdl	0.7762444615364075
degree_scholarshipduration_GermanGovservice.wsdl	0.7634212374687195
award_scholarshipduration_GermanGovservice.wsdl	0.7052819728851318
award_scholarshipduration_SwissGovservice.wsdl	0.7052819728851318
academic-degreegovernmentorganization_funding_service.wsdl	0.6821860671043396
nationalgovernment_scholarshipquantityduration_service.wsdl	0.6547256708145142
nationalgovernment_physical-quantityscholarshiplandarea_service.wsdl	0.6294224262237549
academic-degreegovernment_funding_service.wsdl	0.6255077123641968
academic-degree_funding_GermanGovservice.wsdl	0.6109883189201355
governmentdegree_givingback_service.wsdl	0.5918346643447876
academic-degreegovernmentorganization_lending_service.wsdl	0.5780560374259949
degreegovernment_funding_service.wsdl	0.5625137686729431
university_academic-support-staff_service.wsdl	0.5576388835906982
academic-degreegovernmentorganization_unilateralgiving_service.wsdl	0.5519083738327026
degree_funding_GermanGovservice.wsdl	0.5379921793937683
government-organization_profession_service.wsdl	0.5067282915115356
country_organizationprofession_service.wsdl	0.5055293440818787
academic-degreegovernment_lending_service.wsdl	0.5054258108139038
