durationgeopolitical-entitycity_bedandbreakfast_service.wsdl	1.0
time-measuregeopolitical-entitycity_bedandbreakfast_service.wsdl	0.9525755643844604
geopolitical-entity_bedandbreakfast_service.wsdl	0.9500998258590698
geographical-region_bedandbreakfast_service.wsdl	0.8762352466583252
city_bedandbreakfast_service.wsdl	0.8713334202766418
durationgeopolitical-entitycity_hotel_service.wsdl	0.6921378374099731
durationgeopolitical-entitycity_accommodation_service.wsdl	0.6458220481872559
time-measuregeopolitical-entitycity_hotel_service.wsdl	0.630984365940094
geopolitical-entity_hotel_service.wsdl	0.6154819130897522
time-measuregeopolitical-entitycity_accommodation_service.wsdl	0.6055234670639038
durationcountrycity_hotel_service.wsdl	0.5749784708023071
geopolitical-entity_accommodation_service.wsdl	0.5678372979164124
geopolitical-entityrecorded-video_activityhotel_service.wsdl	0.5587300658226013
geopolitical-entity_professiontimeduration_service.wsdl	0.5381451845169067
geopolitical-entity_luxuryhotel_service.wsdl	0.5333881378173828
geopolitical-entity_occupationaltradetimeduration_service.wsdl	0.5170214176177979
geographical-region_hotel_service.wsdl	0.5122840404510498
geographical-region_hotel_XYZService.wsdl	0.5122840404510498
