educational-organization_lecturer-in-academia_service.wsdl	1.0
higher-educational-organization_lecturer-in-academia_MostUsedservice.wsdl	0.9805173873901367
higher-educational-organization_lecturer-in-academia_service.wsdl	0.9805173873901367
organization_lecturer-in-academia_service.wsdl	0.9803270697593689
learning-centred-organization_lecturer-in-academia_service.wsdl	0.9664725065231323
_lecturer-in-academiaMunchenUniversity_service.wsdl	0.9513499140739441
_lecturer-in-academiaSaarlandUniversity_service.wsdl	0.9513499140739441
_lecturer-in-academiaZambiaUniversity_service.wsdl	0.9513499140739441
university_lecturer-in-academiaCurrentSemmester_service.wsdl	0.9490439295768738
university_lecturer-in-academia_Recommendservice.wsdl	0.9490439295768738
university_lecturer-in-academia_service.wsdl	0.9490439295768738
higher-educational-organization_professor-in-academia_Pioneerservice.wsdl	0.9140133261680603
higher-educational-organization_professor-in-academia_service.wsdl	0.9140133261680603
university_senior-lecturer-in-academia_service.wsdl	0.8973326086997986
university_professor-in-academia_service.wsdl	0.874699056148529
university_research-fellow-in-academia_service.wsdl	0.7284590005874634
higher-educational-organization_senior-research-fellow-in-academia_Firstservice.wsdl	0.7248145341873169
higher-educational-organization_senior-research-fellow-in-academia_service.wsdl	0.7248145341873169
professor-in-academia_address_service.wsdl	0.6856396198272705
researcher-in-academia_abstract-information_service.wsdl	0.632196307182312
researcher-in-academia_address_service.wsdl	0.628015398979187
researcher-in-academia_address_TREEservice.wsdl	0.628015398979187
researcher-in-academia_address_ZOOservice.wsdl	0.628015398979187
research-assistant-in-academia_address_service.wsdl	0.6265586018562317
university_researcher_service.wsdl	0.5974094271659851
government-organization_profession_service.wsdl	0.5498068332672119
research-fellow-in-academia_publication-reference_service.wsdl	0.5488855242729187
sfnovel_authorauthor_BookOntoservice.wsdl	0.5261597633361816
university_academic-support-staff_service.wsdl	0.518622100353241
country_organizationprofession_service.wsdl	0.5164810419082642
academic-degreegovernmentorganization_funding_service.wsdl	0.5151616334915161
sciencefictionnovel_author_MyOntoservice.wsdl	0.5116205215454102
academic-degreegovernment_scholarship_service.wsdl	0.511110246181488
geopolitical-entity_organizationprofession_service.wsdl	0.5007554888725281
