geographical-region_accomodation_service.wsdl	1.0
citycountry_accommodation_service.wsdl	0.8083966970443726
city_accommodation_service.wsdl	0.7889490723609924
geopolitical-entity_accommodation_service.wsdl	0.7727260589599609
durationgeopolitical-entitycity_accommodation_service.wsdl	0.7681761384010315
time-measuregeopolitical-entitycity_accommodation_service.wsdl	0.7350767254829407
geographical-region_hotel_service.wsdl	0.6742285490036011
geographical-region_hotel_XYZService.wsdl	0.6742285490036011
geographical-regiongeographical-region_map_Gorgservice.wsdl	0.602289617061615
geographical-regiongeographical-region_map_service.wsdl	0.602289617061615
_professiongeographical-region_USservice.wsdl	0.5755605697631836
geographical-region_luxuryhotel_service.wsdl	0.5696451663970947
geographical-region_mapFromFrankfurt_service.wsdl	0.5241832137107849
geographical-region_mapToBerlin_service.wsdl	0.5241832137107849
geographical-regiongeographical-region_icon_service.wsdl	0.5234277844429016
durationgeopolitical-entitycity_hotel_service.wsdl	0.5200682878494263
citycountry_destinationhotel_service.wsdl	0.5151771903038025
durationcountrycity_hotel_service.wsdl	0.5052800178527832
