geographical-region_companyskilledoccupation_service.wsdl	1.0
country_companyskilledoccupation_service.wsdl	0.9763776659965515
geopolitical-entity_companyskilledoccupation_service.wsdl	0.9592694640159607
geographical-region_corporationskilledoccupation_service.wsdl	0.9337660670280457
companycountry_skilledoccupation_service.wsdl	0.9257221817970276
geopolitical-entity_skilledoccupationcompany_service.wsdl	0.9117839336395264
public-companycountry_skilledoccupation_service.wsdl	0.9096943736076355
company_skilledoccupation_service.wsdl	0.9072368741035461
geographical-region_organizationskilledoccupation_JobService.wsdl	0.9046759605407715
geographical-region_organizationskilledoccupation_service.wsdl	0.9046759605407715
country_corporationskilledoccupation_service.wsdl	0.9016818404197693
geopolitical-entity_corporationskilledoccupation_service.wsdl	0.8743983507156372
country_organizationskilledoccupation_service.wsdl	0.8720411062240601
citycountry_skilledoccupation_service.wsdl	0.8662499189376831
country_skilledoccupation_jobsservice.wsdl	0.8653860092163086
country_skilledoccupation_service.wsdl	0.8653860092163086
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.8614910840988159
government-organization_skilledoccupation_service.wsdl	0.857010006904602
city_skilledoccupation_service.wsdl	0.8506996631622314
geopolitical-entity_skilledoccupation_service.wsdl	0.8461660742759705
profit-organization_skilledoccupation_service.wsdl	0.8411115407943726
_skilledoccupation_BMWservice.wsdl	0.8367996215820312
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.773378849029541
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.7680850028991699
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.7680850028991699
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.7664120197296143
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.7664120197296143
country_skilledoccupationparttimeposition_JobService.wsdl	0.7575339674949646
country_skilledoccupationparttimeposition_service.wsdl	0.7575339674949646
country_skilledoccupationfulltimeposition_service.wsdl	0.7546004056930542
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.7536603212356567
country_skilledoccupationtimemeasure_service.wsdl	0.753183901309967
municipal-unit_skilledoccupationtimemeasure_service.wsdl	0.750506579875946
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.737884521484375
country_skilledoccupationtimeduration_JobService.wsdl	0.7348606586456299
country_skilledoccupationtimeduration_service.wsdl	0.7348606586456299
DJob_service.wsdl	0.7348606586456299
geographical-region_companyprofession_service.wsdl	0.7030363082885742
_professiongeographical-region_USservice.wsdl	0.6676099896430969
geographical-region_corporationprofession_service.wsdl	0.6559755802154541
geographical-region_companyoccupationaltrade_service.wsdl	0.6421540379524231
geopolitical-entity_companyprofession_service.wsdl	0.6125400066375732
geographical-region_corporationoccupationaltrade_service.wsdl	0.6109901666641235
geographical-region_organizationprofession_service.wsdl	0.6027150750160217
geopolitical-entity_companyoccupationaltrade_service.wsdl	0.5811080932617188
geographical-region_organizationoccupationaltrade_service.wsdl	0.5808637738227844
geographical-regiongeographical-region_map_Gorgservice.wsdl	0.5672014355659485
geographical-regiongeographical-region_map_service.wsdl	0.5672014355659485
country_companyprofession_service.wsdl	0.5620220899581909
country_companyoccupationaltrade_service.wsdl	0.5502183437347412
getLocationOfCityWorldwide.wsdl	0.5483637452125549
geopolitical-entity_corporationprofession_service.wsdl	0.5460333824157715
geographical-regiongeographical-region_icon_service.wsdl	0.5449366569519043
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.5440937280654907
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.542129397392273
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.5397502779960632
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.5396291017532349
geopolitical-entity_professionfulltimeposition_service.wsdl	0.5381245017051697
geopolitical-entity_corporationoccupationaltrade_service.wsdl	0.5343195199966431
geopolitical-entity_professionparttimeposition_service.wsdl	0.5305679440498352
geopolitical-entity_profession_service.wsdl	0.5250737071037292
geopolitical-entity_organizationoccupationaltrade_service.wsdl	0.5186623930931091
geopolitical-entity_professiontimemeasure_service.wsdl	0.5186201930046082
geopolitical-entity_organizationprofession_service.wsdl	0.5180587768554688
country_corporationprofession_service.wsdl	0.5174124240875244
country_corporationoccupationaltrade_service.wsdl	0.5173265337944031
geographical-region_mapFromFrankfurt_service.wsdl	0.5106301307678223
geographical-region_mapToBerlin_service.wsdl	0.5106301307678223
geopolitical-entity_professiontimeduration_service.wsdl	0.5092426538467407
geopolitical-entity_occupationaltradetimemeasure_service.wsdl	0.5064260363578796
country_occupationaltradeparttimeposition_service.wsdl	0.5060737133026123
municipal-unit_professionfulltimeposition_service.wsdl	0.5055504441261292
country_occupationaltradefulltimeposition_service.wsdl	0.502796471118927
municipal-unit_professionparttimeposition_service.wsdl	0.5005466938018799
