geographical-region_companyoccupationaltrade_service.wsdl	1.0
country_companyoccupationaltrade_service.wsdl	0.94784015417099
geographical-region_corporationoccupationaltrade_service.wsdl	0.9361152648925781
geopolitical-entity_companyoccupationaltrade_service.wsdl	0.9156911969184875
geographical-region_organizationoccupationaltrade_service.wsdl	0.9087632894515991
country_occupationaltrade_service.wsdl	0.8811581134796143
country_corporationoccupationaltrade_service.wsdl	0.8748209476470947
geopolitical-entity_occupationaltrade_service.wsdl	0.8546088337898254
country_organizationoccupationaltrade_service.wsdl	0.84683758020401
geopolitical-entity_corporationoccupationaltrade_service.wsdl	0.8273878693580627
geopolitical-entity_organizationoccupationaltrade_service.wsdl	0.8220465779304504
geopolitical-entity_occupationaltradetimemeasure_service.wsdl	0.7666466236114502
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.7555110454559326
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.7536765336990356
country_occupationaltradetimemeasure_Service.wsdl	0.7532190680503845
municipal-unit_occupationaltradetimemeasure_service.wsdl	0.7481168508529663
geopolitical-entity_occupationaltradetimeduration_service.wsdl	0.7445364594459534
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.7438938021659851
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.7431061267852783
country_occupationaltradeparttimeposition_service.wsdl	0.7397891879081726
country_occupationaltradefulltimeposition_service.wsdl	0.7387763261795044
municipal-unit_occupationaltradetimeduration_service.wsdl	0.7333815693855286
country_occupationaltradetimeduration_Service.wsdl	0.7323536276817322
geographical-region_companyprofession_service.wsdl	0.6859948039054871
geographical-region_companyskilledoccupation_service.wsdl	0.6421540379524231
_professiongeographical-region_USservice.wsdl	0.6405803561210632
geographical-region_corporationprofession_service.wsdl	0.6177882552146912
geopolitical-entity_companyskilledoccupation_service.wsdl	0.5897018909454346
geographical-region_corporationskilledoccupation_service.wsdl	0.5795027017593384
country_companyskilledoccupation_service.wsdl	0.5786688327789307
geopolitical-entity_companyprofession_service.wsdl	0.5733176469802856
geographical-region_organizationprofession_service.wsdl	0.568901002407074
geographical-region_organizationskilledoccupation_JobService.wsdl	0.5527167320251465
geographical-region_organizationskilledoccupation_service.wsdl	0.5527167320251465
geopolitical-entity_skilledoccupationcompany_service.wsdl	0.5472769737243652
geographical-regiongeographical-region_icon_service.wsdl	0.5371649265289307
country_companyprofession_service.wsdl	0.5327831506729126
geographical-regiongeographical-region_map_Gorgservice.wsdl	0.5256012678146362
geographical-regiongeographical-region_map_service.wsdl	0.5256012678146362
geopolitical-entity_corporationskilledoccupation_service.wsdl	0.5178269743919373
country_corporationskilledoccupation_service.wsdl	0.5123198628425598
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.5006745457649231
getLocationOfCityWorldwide.wsdl	0.5001800656318665
