geographical-region_organizationskilledoccupation_JobService.wsdl	1.0
geographical-region_organizationskilledoccupation_service.wsdl	1.0
country_organizationskilledoccupation_service.wsdl	0.9790972471237183
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.9642440676689148
geographical-region_corporationskilledoccupation_service.wsdl	0.9074991345405579
government-organization_skilledoccupation_service.wsdl	0.9073277115821838
geographical-region_companyskilledoccupation_service.wsdl	0.9046759605407715
profit-organization_skilledoccupation_service.wsdl	0.8908606171607971
country_corporationskilledoccupation_service.wsdl	0.8766437768936157
country_companyskilledoccupation_service.wsdl	0.8756466507911682
geopolitical-entity_companyskilledoccupation_service.wsdl	0.8732303977012634
companycountry_skilledoccupation_service.wsdl	0.8714582324028015
country_skilledoccupation_jobsservice.wsdl	0.8669465780258179
country_skilledoccupation_service.wsdl	0.8669465780258179
citycountry_skilledoccupation_service.wsdl	0.8604749441146851
geopolitical-entity_corporationskilledoccupation_service.wsdl	0.8570276498794556
geopolitical-entity_skilledoccupation_service.wsdl	0.8564484119415283
public-companycountry_skilledoccupation_service.wsdl	0.8518790602684021
company_skilledoccupation_service.wsdl	0.8457628488540649
city_skilledoccupation_service.wsdl	0.8409005999565125
_skilledoccupation_BMWservice.wsdl	0.8345676064491272
geopolitical-entity_skilledoccupationcompany_service.wsdl	0.8327224850654602
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.7912716269493103
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.7912716269493103
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.7828293442726135
country_skilledoccupationparttimeposition_JobService.wsdl	0.7761090397834778
country_skilledoccupationparttimeposition_service.wsdl	0.7761090397834778
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.7684082984924316
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.7684082984924316
country_skilledoccupationtimemeasure_service.wsdl	0.7558552026748657
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.7530945539474487
country_skilledoccupationfulltimeposition_service.wsdl	0.7498907446861267
geographical-region_organizationprofession_service.wsdl	0.7420570850372314
municipal-unit_skilledoccupationtimemeasure_service.wsdl	0.7307989001274109
country_skilledoccupationtimeduration_JobService.wsdl	0.7268027067184448
country_skilledoccupationtimeduration_service.wsdl	0.7268027067184448
DJob_service.wsdl	0.7268027067184448
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.7086546421051025
_professiongeographical-region_USservice.wsdl	0.6870039701461792
geographical-region_organizationoccupationaltrade_service.wsdl	0.6769059896469116
geopolitical-entity_organizationprofession_service.wsdl	0.6655741930007935
geographical-region_corporationprofession_service.wsdl	0.6525759696960449
geopolitical-entity_organizationoccupationaltrade_service.wsdl	0.6249108910560608
country_organizationprofession_service.wsdl	0.6228920817375183
geographical-region_companyprofession_service.wsdl	0.6184098124504089
country_organizationoccupationaltrade_service.wsdl	0.5986708402633667
geographical-region_corporationoccupationaltrade_service.wsdl	0.587462306022644
government-organization_profession_service.wsdl	0.5845159888267517
geopolitical-entity_professionparttimeposition_service.wsdl	0.58006751537323
geopolitical-entity_profession_service.wsdl	0.5736321210861206
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.5685942769050598
geopolitical-entity_professionfulltimeposition_service.wsdl	0.5626789927482605
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.5622327327728271
geopolitical-entity_corporationprofession_service.wsdl	0.5569175481796265
geopolitical-entity_professiontimemeasure_service.wsdl	0.5558456778526306
geographical-region_companyoccupationaltrade_service.wsdl	0.5527167320251465
geographical-regiongeographical-region_icon_service.wsdl	0.5513003468513489
geographical-regiongeographical-region_map_Gorgservice.wsdl	0.54973304271698
geographical-regiongeographical-region_map_service.wsdl	0.54973304271698
geopolitical-entity_companyprofession_service.wsdl	0.5466158986091614
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.5437011122703552
profit-organization_profession_service.wsdl	0.5426601767539978
municipal-unit_professionparttimeposition_service.wsdl	0.535993218421936
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.5348595380783081
geopolitical-entity_professiontimeduration_service.wsdl	0.5330803990364075
country_occupationaltradeparttimeposition_service.wsdl	0.5280110239982605
nationalgovernment_physical-quantityscholarshiplandarea_service.wsdl	0.5261843800544739
geopolitical-entity_corporationoccupationaltrade_service.wsdl	0.5237127542495728
country_professionparttimeposition_service.wsdl	0.5219263434410095
country_corporationprofession_service.wsdl	0.5199891328811646
geopolitical-entity_occupationaltradetimemeasure_service.wsdl	0.5183181762695312
municipal-unit_professionfulltimeposition_service.wsdl	0.5150173902511597
geopolitical-entity_occupationaltrade_service.wsdl	0.5072482824325562
geopolitical-entity_companyoccupationaltrade_service.wsdl	0.5055874586105347
government_scholarshiporganization_service.wsdl	0.5041231513023376
country_professionfulltimeposition_service.wsdl	0.5028208494186401
academic-degreegovernmentorganization_unilateralgiving_service.wsdl	0.5013374090194702
country_occupationaltradefulltimeposition_service.wsdl	0.5000446438789368
