geopolitical-entity_bedandbreakfast_service.wsdl	1.0
durationgeopolitical-entitycity_bedandbreakfast_service.wsdl	0.9500998258590698
time-measuregeopolitical-entitycity_bedandbreakfast_service.wsdl	0.9368004202842712
geographical-region_bedandbreakfast_service.wsdl	0.8916019201278687
city_bedandbreakfast_service.wsdl	0.876288890838623
geopolitical-entity_hotel_service.wsdl	0.5940772891044617
durationgeopolitical-entitycity_hotel_service.wsdl	0.5547590255737305
time-measuregeopolitical-entitycity_hotel_service.wsdl	0.5392743349075317
geopolitical-entity_accommodation_service.wsdl	0.5335139036178589
geopolitical-entity_luxuryhotel_service.wsdl	0.5158858895301819
geopolitical-entityrecorded-video_activityhotel_service.wsdl	0.5133628845214844
durationgeopolitical-entitycity_accommodation_service.wsdl	0.5077665448188782
time-measuregeopolitical-entitycity_accommodation_service.wsdl	0.5069366097450256
