geopolitical-entity_weatherseasontimeposition_service.wsdl	1.0
geopolitical-entity_weatherseasonproposition_service.wsdl	0.9332436919212341
geopolitical-entity_weatherseason_service.wsdl	0.915503203868866
geographical-region_weatherseason_service.wsdl	0.8480440378189087
country_weatherseason_service.wsdl	0.8435501456260681
city_weatherseason_service.wsdl	0.8264317512512207
municipal-unit_weatherseason_service.wsdl	0.8228028416633606
geopolitical-entity_weatherfront_service.wsdl	0.7150647044181824
geopolitical-entity_weathersystem_service.wsdl	0.6800622344017029
geopolitical-entity_weatherprocess_service.wsdl	0.6797511577606201
geopolitical-entity_professionparttimeposition_service.wsdl	0.6625062227249146
geopolitical-entity_professionfulltimeposition_service.wsdl	0.6551289558410645
country_weatherfront_service.wsdl	0.6481508612632751
geographical-region_weatherfront_service.wsdl	0.6344773173332214
geographical-region_weatherfront_WService.wsdl	0.6344773173332214
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.6303532123565674
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.6303532123565674
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.6183485984802246
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.6183485984802246
city_weatherfront_service.wsdl	0.6143518686294556
municipal-unit_weatherfront_service.wsdl	0.613932192325592
country_weatherprocess_service.wsdl	0.6134276390075684
country_weathersystem_service.wsdl	0.612493634223938
geographical-region_weathersystem_service.wsdl	0.6010600924491882
_weatherfront_BombayIndiaservice.wsdl	0.6008280515670776
_weatherfront_Britishservice.wsdl	0.6008280515670776
_weatherfront_Germanyservice.wsdl	0.6008280515670776
geographical-region_weatherprocess_GRWservice.wsdl	0.6004886031150818
geographical-region_weatherprocess_service.wsdl	0.6004886031150818
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.5956559777259827
city_weathersystem_service.wsdl	0.5890529155731201
municipal-unit_professionparttimeposition_service.wsdl	0.5864757299423218
municipal-unit_weatherprocess_service.wsdl	0.5804027915000916
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.5798160433769226
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.5793644189834595
country_professionparttimeposition_service.wsdl	0.5773343443870544
geopolitical-entity_professiontimeduration_service.wsdl	0.5768791437149048
municipal-unit_professionfulltimeposition_service.wsdl	0.5757140517234802
country_sportsposition_service.wsdl	0.5743845701217651
_weatherprocess_Germanservice.wsdl	0.5741546154022217
municipal-unit_weathersystem_service.wsdl	0.5702365636825562
country_professionfulltimeposition_service.wsdl	0.5692707300186157
country_skilledoccupationparttimeposition_JobService.wsdl	0.568534791469574
country_skilledoccupationparttimeposition_service.wsdl	0.568534791469574
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.5614830851554871
country_skilledoccupationfulltimeposition_service.wsdl	0.5552768111228943
geopolitical-entity_professiontimemeasure_service.wsdl	0.5478047728538513
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.5438103079795837
geopolitical-entity_warmfront_service.wsdl	0.543722927570343
geopolitical-entity_drought_service.wsdl	0.5407968759536743
country_occupationaltradeparttimeposition_service.wsdl	0.5263060331344604
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.5207474827766418
country_occupationaltradefulltimeposition_service.wsdl	0.5085031390190125
getSunsetSunriseTwilightTime.wsdl	0.5066336393356323
agent_movement.wsdl	0.5037224292755127
