geopolitical-entity_organizationoccupationaltrade_service.wsdl	1.0
geopolitical-entity_occupationaltrade_service.wsdl	0.9388349652290344
country_organizationoccupationaltrade_service.wsdl	0.9267077445983887
geographical-region_organizationoccupationaltrade_service.wsdl	0.9232209920883179
geopolitical-entity_corporationoccupationaltrade_service.wsdl	0.9165695309638977
geopolitical-entity_companyoccupationaltrade_service.wsdl	0.9121440649032593
geographical-region_corporationoccupationaltrade_service.wsdl	0.8622913360595703
country_corporationoccupationaltrade_service.wsdl	0.8551837205886841
geopolitical-entity_occupationaltradetimemeasure_service.wsdl	0.827928364276886
country_occupationaltrade_service.wsdl	0.8274075388908386
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.8258083462715149
geographical-region_companyoccupationaltrade_service.wsdl	0.8220465779304504
country_companyoccupationaltrade_service.wsdl	0.8125808238983154
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.8040350675582886
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.80286705493927
geopolitical-entity_occupationaltradetimeduration_service.wsdl	0.7860608696937561
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.7782469391822815
geopolitical-entity_organizationprofession_service.wsdl	0.7326983213424683
country_occupationaltradeparttimeposition_service.wsdl	0.7249082326889038
country_occupationaltradetimemeasure_Service.wsdl	0.7066836357116699
country_occupationaltradefulltimeposition_service.wsdl	0.6999558806419373
municipal-unit_occupationaltradetimemeasure_service.wsdl	0.6908566951751709
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.6844855546951294
country_occupationaltradetimeduration_Service.wsdl	0.6686410307884216
municipal-unit_occupationaltradetimeduration_service.wsdl	0.6597414612770081
geopolitical-entity_corporationprofession_service.wsdl	0.655413031578064
geographical-region_organizationprofession_service.wsdl	0.6492522358894348
geopolitical-entity_profession_service.wsdl	0.6402167081832886
geopolitical-entity_companyprofession_service.wsdl	0.6352942585945129
geographical-region_organizationskilledoccupation_JobService.wsdl	0.6249108910560608
geographical-region_organizationskilledoccupation_service.wsdl	0.6249108910560608
AddLinks__service.wsdl	0.6229027509689331
geopolitical-entity_corporationskilledoccupation_service.wsdl	0.6108523607254028
country_organizationskilledoccupation_service.wsdl	0.6042430996894836
geopolitical-entity_skilledoccupationcompany_service.wsdl	0.6027112007141113
geographical-region_corporationprofession_service.wsdl	0.5921443700790405
geopolitical-entity_companyskilledoccupation_service.wsdl	0.5868262648582458
country_organizationprofession_service.wsdl	0.5793214440345764
geopolitical-entity_skilledoccupation_service.wsdl	0.5698772072792053
geopolitical-entity_professiontimemeasure_service.wsdl	0.5640161633491516
geographical-region_corporationskilledoccupation_service.wsdl	0.5619276165962219
geopolitical-entity_professionparttimeposition_service.wsdl	0.5535812973976135
profit-organization_profession_service.wsdl	0.5517117977142334
government-organization_profession_service.wsdl	0.5469765663146973
geopolitical-entity_professionfulltimeposition_service.wsdl	0.5445460081100464
profit-organization_skilledoccupation_service.wsdl	0.5405633449554443
geopolitical-entity_internalchange_service.wsdl	0.5393368005752563
country_corporationskilledoccupation_service.wsdl	0.5346343517303467
geographical-region_companyprofession_service.wsdl	0.5327162742614746
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.529382050037384
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.529382050037384
geopolitical-entity_professiontimeduration_service.wsdl	0.5285640358924866
geopolitical-entityrecorded-video_activityhotel_service.wsdl	0.5265746116638184
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.524990439414978
_professiongeographical-region_USservice.wsdl	0.5216132998466492
geographical-region_companyskilledoccupation_service.wsdl	0.5186623930931091
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.5168912410736084
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.5168912410736084
academic-degreegovernmentorganization_unilateralgiving_service.wsdl	0.5165370106697083
government-organization_skilledoccupation_service.wsdl	0.5142714381217957
country_corporationprofession_service.wsdl	0.513522744178772
geopolitical-entity_hotel_service.wsdl	0.5014469623565674
