geopolitical-entity_occupationaltradetimemeasure_service.wsdl	1.0
country_occupationaltradetimemeasure_Service.wsdl	0.9322527050971985
municipal-unit_occupationaltradetimemeasure_service.wsdl	0.9133037328720093
geopolitical-entity_occupationaltrade_service.wsdl	0.8706395030021667
geopolitical-entity_occupationaltradetimeduration_service.wsdl	0.8648383021354675
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.858549952507019
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.8552374839782715
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.8487434983253479
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.8478350043296814
geopolitical-entity_organizationoccupationaltrade_service.wsdl	0.827928364276886
geopolitical-entity_companyoccupationaltrade_service.wsdl	0.8275274038314819
geopolitical-entity_corporationoccupationaltrade_service.wsdl	0.8106452822685242
country_occupationaltrade_service.wsdl	0.7957030534744263
country_occupationaltradefulltimeposition_service.wsdl	0.7943826913833618
country_occupationaltradeparttimeposition_service.wsdl	0.7913586497306824
country_occupationaltradetimeduration_Service.wsdl	0.7900140285491943
municipal-unit_occupationaltradetimeduration_service.wsdl	0.7842568755149841
geographical-region_corporationoccupationaltrade_service.wsdl	0.7804190516471863
geographical-region_organizationoccupationaltrade_service.wsdl	0.7766230702400208
country_corporationoccupationaltrade_service.wsdl	0.7699329257011414
country_organizationoccupationaltrade_service.wsdl	0.7681699395179749
geographical-region_companyoccupationaltrade_service.wsdl	0.7666466236114502
country_companyoccupationaltrade_service.wsdl	0.7568680047988892
geopolitical-entity_professiontimemeasure_service.wsdl	0.7560800909996033
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.7304968237876892
country_skilledoccupationtimemeasure_service.wsdl	0.6410131454467773
municipal-unit_skilledoccupationtimemeasure_service.wsdl	0.6382304430007935
municipal-unit_professiontimemeasure_service.wsdl	0.6265415549278259
country_professiontimemeasure_service.wsdl	0.6253379583358765
time-measuregeopolitical-entitycity_hotel_service.wsdl	0.6158455014228821
time-measuregeopolitical-entitycity_accommodation_service.wsdl	0.6105920076370239
geopolitical-entity_professiontimeduration_service.wsdl	0.6097142696380615
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.6086328625679016
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.6040838956832886
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.6040838956832886
geopolitical-entity_professionfulltimeposition_service.wsdl	0.5965649485588074
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.5917008519172668
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.5917008519172668
careorganization_diagnosticprocesstimemeasure_service.wsdl	0.588059663772583
geopolitical-entity_professionparttimeposition_service.wsdl	0.5752857327461243
geopolitical-entity_skilledoccupationcompany_service.wsdl	0.5605446696281433
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.5593962669372559
geopolitical-entity_companyskilledoccupation_service.wsdl	0.5537574291229248
geopolitical-entity_corporationskilledoccupation_service.wsdl	0.5521533489227295
hospital_diagnosticprocesstimemeasure_service.wsdl	0.5521504878997803
geopolitical-entity_skilledoccupation_service.wsdl	0.5509517788887024
medicalclinic_diagnosticprocesstimemeasure_service.wsdl	0.5454553365707397
geopolitical-entity_profession_service.wsdl	0.5344594120979309
AddLinks__service.wsdl	0.5307798981666565
CAD_medical_service.wsdl	0.5242395401000977
geographical-region_corporationskilledoccupation_service.wsdl	0.5212537050247192
geopolitical-entityrecorded-video_activityhotel_service.wsdl	0.5207231044769287
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.5197201371192932
geopolitical-entity_organizationprofession_service.wsdl	0.519078254699707
geographical-region_organizationskilledoccupation_JobService.wsdl	0.5183181762695312
geographical-region_organizationskilledoccupation_service.wsdl	0.5183181762695312
country_skilledoccupationfulltimeposition_service.wsdl	0.5181427597999573
geopolitical-entity_companyprofession_service.wsdl	0.5179234743118286
geopolitical-entity_corporationprofession_service.wsdl	0.5173007845878601
municipal-unit_professionfulltimeposition_service.wsdl	0.5147401690483093
country_skilledoccupationtimeduration_JobService.wsdl	0.5128147006034851
country_skilledoccupationtimeduration_service.wsdl	0.5128147006034851
DJob_service.wsdl	0.5128147006034851
beverage_taxfreepricephysical-quantity_service.wsdl	0.5127635598182678
time-measuregeopolitical-entitycity_bedandbreakfast_service.wsdl	0.5102241039276123
food_taxfreepricephysical-quantity_Aldiservice.wsdl	0.5081400871276855
geographical-region_companyskilledoccupation_service.wsdl	0.5064260363578796
meat_taxfreepricephysical-quantity_Aldiservice.wsdl	0.5055736303329468
country_skilledoccupationparttimeposition_JobService.wsdl	0.5040855407714844
country_skilledoccupationparttimeposition_service.wsdl	0.5040855407714844
geopolitical-entity_internalchange_service.wsdl	0.5031629800796509
