geopolitical-entity_corporationskilledoccupation_service.wsdl	1.0
country_corporationskilledoccupation_service.wsdl	0.9694700837135315
geographical-region_corporationskilledoccupation_service.wsdl	0.9653343558311462
geopolitical-entity_skilledoccupationcompany_service.wsdl	0.941033661365509
geopolitical-entity_companyskilledoccupation_service.wsdl	0.9376813769340515
geopolitical-entity_skilledoccupation_service.wsdl	0.9278914928436279
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.9110795259475708
country_companyskilledoccupation_service.wsdl	0.8748963475227356
geographical-region_companyskilledoccupation_service.wsdl	0.8743983507156372
government-organization_skilledoccupation_service.wsdl	0.8625686168670654
public-companycountry_skilledoccupation_service.wsdl	0.8615138530731201
companycountry_skilledoccupation_service.wsdl	0.8609110116958618
geographical-region_organizationskilledoccupation_JobService.wsdl	0.8570276498794556
geographical-region_organizationskilledoccupation_service.wsdl	0.8570276498794556
country_organizationskilledoccupation_service.wsdl	0.8539498448371887
company_skilledoccupation_service.wsdl	0.8525863289833069
profit-organization_skilledoccupation_service.wsdl	0.846173882484436
country_skilledoccupation_jobsservice.wsdl	0.8270783424377441
country_skilledoccupation_service.wsdl	0.8270783424377441
citycountry_skilledoccupation_service.wsdl	0.8221116662025452
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.8207395672798157
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.8193339705467224
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.8193339705467224
city_skilledoccupation_service.wsdl	0.8173684477806091
_skilledoccupation_BMWservice.wsdl	0.811025083065033
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.8003634810447693
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.8003634810447693
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.7797380089759827
geopolitical-entity_corporationprofession_service.wsdl	0.7534268498420715
country_skilledoccupationparttimeposition_JobService.wsdl	0.7247828245162964
country_skilledoccupationparttimeposition_service.wsdl	0.7247828245162964
municipal-unit_skilledoccupationtimemeasure_service.wsdl	0.71662437915802
country_skilledoccupationtimemeasure_service.wsdl	0.7067776322364807
geographical-region_corporationprofession_service.wsdl	0.7046082615852356
country_skilledoccupationfulltimeposition_service.wsdl	0.7040719389915466
geopolitical-entity_corporationoccupationaltrade_service.wsdl	0.6986044049263
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.6846611499786377
country_skilledoccupationtimeduration_JobService.wsdl	0.668986439704895
country_skilledoccupationtimeduration_service.wsdl	0.668986439704895
DJob_service.wsdl	0.668986439704895
geopolitical-entity_companyprofession_service.wsdl	0.6584147810935974
geopolitical-entity_profession_service.wsdl	0.6452333331108093
geographical-region_corporationoccupationaltrade_service.wsdl	0.6389383673667908
geopolitical-entity_organizationprofession_service.wsdl	0.6388981938362122
country_corporationprofession_service.wsdl	0.6323607563972473
AddLinks__service.wsdl	0.6173973679542542
geopolitical-entity_organizationoccupationaltrade_service.wsdl	0.6108523607254028
geopolitical-entity_companyoccupationaltrade_service.wsdl	0.6067086458206177
country_corporationoccupationaltrade_service.wsdl	0.6001525521278381
geopolitical-entity_professionparttimeposition_service.wsdl	0.5990139842033386
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.5934264063835144
geopolitical-entity_professionfulltimeposition_service.wsdl	0.5865842700004578
geopolitical-entity_professiontimemeasure_service.wsdl	0.5860946178436279
geopolitical-entity_occupationaltrade_service.wsdl	0.5730951428413391
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.5724727511405945
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.5710316896438599
geographical-region_companyprofession_service.wsdl	0.5631253123283386
geographical-region_organizationprofession_service.wsdl	0.5570929646492004
geopolitical-entity_occupationaltradetimemeasure_service.wsdl	0.5521533489227295
geopolitical-entity_professiontimeduration_service.wsdl	0.5501182675361633
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.5480467677116394
_professiongeographical-region_USservice.wsdl	0.5337532758712769
geographical-region_organizationoccupationaltrade_service.wsdl	0.5308882594108582
municipal-unit_professionparttimeposition_service.wsdl	0.5252415537834167
geopolitical-entity_occupationaltradetimeduration_service.wsdl	0.5217113494873047
geographical-region_companyoccupationaltrade_service.wsdl	0.5178269743919373
time-measuregeopolitical-entitycity_accommodation_service.wsdl	0.5173375010490417
time-measuregeopolitical-entitycity_hotel_service.wsdl	0.5132251977920532
geopolitical-entity_internalchange_service.wsdl	0.5111406445503235
municipal-unit_professionfulltimeposition_service.wsdl	0.5095990300178528
government-organization_profession_service.wsdl	0.5039006471633911
