geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	1.0
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.9925828576087952
country_occupationaltradefulltimeposition_service.wsdl	0.944953441619873
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.9429720044136047
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.9364393353462219
country_occupationaltradeparttimeposition_service.wsdl	0.8829267621040344
geopolitical-entity_occupationaltradetimemeasure_service.wsdl	0.858549952507019
geopolitical-entity_occupationaltradetimeduration_service.wsdl	0.8472991585731506
geopolitical-entity_occupationaltrade_service.wsdl	0.8349742293357849
geopolitical-entity_companyoccupationaltrade_service.wsdl	0.8070916533470154
geopolitical-entity_professionfulltimeposition_service.wsdl	0.804079532623291
geopolitical-entity_organizationoccupationaltrade_service.wsdl	0.80286705493927
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.7819659113883972
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.7819659113883972
geopolitical-entity_corporationoccupationaltrade_service.wsdl	0.7807726860046387
country_occupationaltradetimemeasure_Service.wsdl	0.7702857255935669
country_occupationaltradetimeduration_Service.wsdl	0.7647373676300049
municipal-unit_occupationaltradetimeduration_service.wsdl	0.758086085319519
municipal-unit_occupationaltradetimemeasure_service.wsdl	0.7578415274620056
geographical-region_organizationoccupationaltrade_service.wsdl	0.7490691542625427
geographical-region_corporationoccupationaltrade_service.wsdl	0.7471629977226257
country_occupationaltrade_service.wsdl	0.7455283999443054
geographical-region_companyoccupationaltrade_service.wsdl	0.7438938021659851
country_organizationoccupationaltrade_service.wsdl	0.7324925661087036
country_corporationoccupationaltrade_service.wsdl	0.7279598116874695
country_companyoccupationaltrade_service.wsdl	0.7262241244316101
municipal-unit_professionfulltimeposition_service.wsdl	0.7225609421730042
geopolitical-entity_professionparttimeposition_service.wsdl	0.7205724120140076
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.7181318998336792
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.7181318998336792
country_skilledoccupationfulltimeposition_service.wsdl	0.7085023522377014
country_professionfulltimeposition_service.wsdl	0.7006224393844604
geopolitical-entity_professiontimemeasure_service.wsdl	0.6425407528877258
geopolitical-entity_professiontimeduration_service.wsdl	0.6413148045539856
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.6405546069145203
municipal-unit_professionparttimeposition_service.wsdl	0.6394912004470825
country_skilledoccupationparttimeposition_JobService.wsdl	0.6381521224975586
country_skilledoccupationparttimeposition_service.wsdl	0.6381521224975586
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.6373879909515381
country_professionparttimeposition_service.wsdl	0.6091667413711548
geopolitical-entity_skilledoccupationcompany_service.wsdl	0.5946606397628784
geopolitical-entity_companyskilledoccupation_service.wsdl	0.5882508754730225
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.585860013961792
geopolitical-entity_weatherseasontimeposition_service.wsdl	0.5793644189834595
geopolitical-entity_skilledoccupation_service.wsdl	0.5765823125839233
geopolitical-entity_corporationskilledoccupation_service.wsdl	0.5724727511405945
geopolitical-entity_profession_service.wsdl	0.5631838440895081
geopolitical-entity_companyprofession_service.wsdl	0.5548481345176697
agent_movement.wsdl	0.5461633801460266
geopolitical-entity_organizationprofession_service.wsdl	0.546162486076355
geographical-region_organizationskilledoccupation_JobService.wsdl	0.5437011122703552
geographical-region_organizationskilledoccupation_service.wsdl	0.5437011122703552
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.5425084233283997
geographical-region_corporationskilledoccupation_service.wsdl	0.5408093333244324
geopolitical-entity_weatherseasonproposition_service.wsdl	0.5407177805900574
geographical-region_companyskilledoccupation_service.wsdl	0.5396291017532349
country_skilledoccupationtimeduration_JobService.wsdl	0.5386862754821777
country_skilledoccupationtimeduration_service.wsdl	0.5386862754821777
DJob_service.wsdl	0.5386862754821777
geopolitical-entity_corporationprofession_service.wsdl	0.5376441478729248
municipal-unit_skilledoccupationtimemeasure_service.wsdl	0.5362898111343384
time-measuregeopolitical-entitycity_accommodation_service.wsdl	0.5360240936279297
country_skilledoccupationtimemeasure_service.wsdl	0.5357607007026672
AddLinks__service.wsdl	0.5354838967323303
time-measuregeopolitical-entitycity_hotel_service.wsdl	0.523408055305481
country_organizationskilledoccupation_service.wsdl	0.5174353718757629
municipal-unit_professiontimeduration_service.wsdl	0.5132449269294739
country_corporationskilledoccupation_service.wsdl	0.5131844878196716
country_companyskilledoccupation_service.wsdl	0.5124343633651733
geopolitical-entity_internalchange_service.wsdl	0.5060752630233765
country_professiontimeduration_Service.wsdl	0.50356125831604
public-companycountry_skilledoccupation_service.wsdl	0.5031104683876038
profit-organization_skilledoccupation_service.wsdl	0.5014270544052124
municipal-unit_professiontimemeasure_service.wsdl	0.5002418160438538
