geopolitical-entity_occupationaltrade_service.wsdl	1.0
geopolitical-entity_companyoccupationaltrade_service.wsdl	0.943579375743866
geopolitical-entity_organizationoccupationaltrade_service.wsdl	0.9388349652290344
geopolitical-entity_corporationoccupationaltrade_service.wsdl	0.9313434958457947
country_occupationaltrade_service.wsdl	0.8911598920822144
geographical-region_corporationoccupationaltrade_service.wsdl	0.8784584999084473
geopolitical-entity_occupationaltradetimemeasure_service.wsdl	0.8706395030021667
country_corporationoccupationaltrade_service.wsdl	0.8660265803337097
geographical-region_organizationoccupationaltrade_service.wsdl	0.8614773750305176
geographical-region_companyoccupationaltrade_service.wsdl	0.8546088337898254
country_organizationoccupationaltrade_service.wsdl	0.8497055172920227
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.8424111008644104
geopolitical-entity_occupationaltradetimeduration_service.wsdl	0.8419914245605469
country_companyoccupationaltrade_service.wsdl	0.8418145775794983
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.8349742293357849
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.8199889063835144
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.8101932406425476
country_occupationaltradetimemeasure_Service.wsdl	0.7477182149887085
country_occupationaltradeparttimeposition_service.wsdl	0.7377291917800903
municipal-unit_occupationaltradetimemeasure_service.wsdl	0.7312379479408264
country_occupationaltradefulltimeposition_service.wsdl	0.7299548983573914
country_occupationaltradetimeduration_Service.wsdl	0.7244590520858765
municipal-unit_occupationaltradetimeduration_service.wsdl	0.714540421962738
AddLinks__service.wsdl	0.6175231337547302
geopolitical-entity_profession_service.wsdl	0.5889260768890381
geopolitical-entity_skilledoccupationcompany_service.wsdl	0.5782766938209534
geopolitical-entity_corporationprofession_service.wsdl	0.5759339928627014
geopolitical-entity_corporationskilledoccupation_service.wsdl	0.5730951428413391
geopolitical-entity_skilledoccupation_service.wsdl	0.5678144097328186
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.5674821734428406
geopolitical-entity_companyprofession_service.wsdl	0.5658994913101196
geopolitical-entity_organizationprofession_service.wsdl	0.5633525252342224
geopolitical-entity_companyskilledoccupation_service.wsdl	0.5618637204170227
geographical-region_corporationskilledoccupation_service.wsdl	0.5235801935195923
geopolitical-entity_professiontimemeasure_service.wsdl	0.5193545818328857
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.5175380110740662
geopolitical-entity_internalchange_service.wsdl	0.5146064162254333
geographical-region_organizationskilledoccupation_JobService.wsdl	0.5072482824325562
geographical-region_organizationskilledoccupation_service.wsdl	0.5072482824325562
geographical-region_corporationprofession_service.wsdl	0.5066841244697571
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.5038150548934937
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.5038150548934937
geopolitical-entity_professiontimeduration_service.wsdl	0.5035766959190369
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.5028378963470459
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.5007790923118591
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.5007790923118591
