geopolitical-entity_skilledoccupationcompany_service.wsdl	1.0
geopolitical-entity_companyskilledoccupation_service.wsdl	0.9906578063964844
geopolitical-entity_corporationskilledoccupation_service.wsdl	0.941033661365509
geopolitical-entity_skilledoccupation_service.wsdl	0.9403340220451355
country_companyskilledoccupation_service.wsdl	0.9267764687538147
geographical-region_companyskilledoccupation_service.wsdl	0.9117839336395264
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.9017130732536316
country_corporationskilledoccupation_service.wsdl	0.8978126049041748
companycountry_skilledoccupation_service.wsdl	0.8945650458335876
company_skilledoccupation_service.wsdl	0.8933190107345581
geographical-region_corporationskilledoccupation_service.wsdl	0.8898869156837463
public-companycountry_skilledoccupation_service.wsdl	0.8822073340415955
government-organization_skilledoccupation_service.wsdl	0.8594030141830444
profit-organization_skilledoccupation_service.wsdl	0.849250078201294
country_organizationskilledoccupation_service.wsdl	0.8377202153205872
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.8346464037895203
geographical-region_organizationskilledoccupation_JobService.wsdl	0.8327224850654602
geographical-region_organizationskilledoccupation_service.wsdl	0.8327224850654602
country_skilledoccupation_jobsservice.wsdl	0.8307238817214966
country_skilledoccupation_service.wsdl	0.8307238817214966
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.8299845457077026
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.8299845457077026
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.8267040848731995
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.8267040848731995
_skilledoccupation_BMWservice.wsdl	0.8200033903121948
citycountry_skilledoccupation_service.wsdl	0.8181360960006714
city_skilledoccupation_service.wsdl	0.8178930282592773
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.8038680553436279
country_skilledoccupationparttimeposition_JobService.wsdl	0.7292073369026184
country_skilledoccupationparttimeposition_service.wsdl	0.7292073369026184
country_skilledoccupationfulltimeposition_service.wsdl	0.7258458137512207
geopolitical-entity_companyprofession_service.wsdl	0.7246313095092773
municipal-unit_skilledoccupationtimemeasure_service.wsdl	0.721209704875946
country_skilledoccupationtimemeasure_service.wsdl	0.7140180468559265
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.7004678249359131
geopolitical-entity_corporationprofession_service.wsdl	0.6902177333831787
country_skilledoccupationtimeduration_JobService.wsdl	0.6878108978271484
country_skilledoccupationtimeduration_service.wsdl	0.6878108978271484
DJob_service.wsdl	0.6878108978271484
geopolitical-entity_companyoccupationaltrade_service.wsdl	0.658329427242279
geopolitical-entity_profession_service.wsdl	0.6560394167900085
geopolitical-entity_corporationoccupationaltrade_service.wsdl	0.6425453424453735
geopolitical-entity_organizationprofession_service.wsdl	0.6324858069419861
AddLinks__service.wsdl	0.6289893984794617
geopolitical-entity_professionfulltimeposition_service.wsdl	0.6142905354499817
geographical-region_corporationprofession_service.wsdl	0.6091322302818298
geopolitical-entity_professionparttimeposition_service.wsdl	0.608020007610321
geographical-region_companyprofession_service.wsdl	0.6033922433853149
geopolitical-entity_organizationoccupationaltrade_service.wsdl	0.6027112007141113
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.5991790890693665
geopolitical-entity_professiontimemeasure_service.wsdl	0.5990775227546692
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.5946606397628784
geopolitical-entity_occupationaltrade_service.wsdl	0.5782766938209534
geopolitical-entity_professiontimeduration_service.wsdl	0.5756441950798035
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.5738596320152283
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.5679197907447815
geopolitical-entity_occupationaltradetimemeasure_service.wsdl	0.5605446696281433
geographical-region_corporationoccupationaltrade_service.wsdl	0.5583323836326599
geographical-region_companyoccupationaltrade_service.wsdl	0.5472769737243652
country_corporationprofession_service.wsdl	0.5461006164550781
geopolitical-entity_occupationaltradetimeduration_service.wsdl	0.5408427715301514
country_companyprofession_service.wsdl	0.5374518036842346
geopolitical-entity_internalchange_service.wsdl	0.5315842032432556
country_corporationoccupationaltrade_service.wsdl	0.5250651240348816
geographical-region_organizationprofession_service.wsdl	0.5242710709571838
time-measuregeopolitical-entitycity_hotel_service.wsdl	0.5178573131561279
time-measuregeopolitical-entitycity_accommodation_service.wsdl	0.5166037678718567
municipal-unit_professionfulltimeposition_service.wsdl	0.5152514576911926
country_companyoccupationaltrade_service.wsdl	0.5130024552345276
geopolitical-entityrecorded-video_activityhotel_service.wsdl	0.5124663710594177
municipal-unit_professionparttimeposition_service.wsdl	0.5113417506217957
durationgeopolitical-entitycity_hotel_service.wsdl	0.5075140595436096
geopolitical-entity_hotel_service.wsdl	0.504265308380127
geographical-region_organizationoccupationaltrade_service.wsdl	0.5006836652755737
