geopolitical-entity_corporationprofession_service.wsdl	1.0
geopolitical-entity_companyprofession_service.wsdl	0.9176757335662842
geopolitical-entity_profession_service.wsdl	0.9069786071777344
country_corporationprofession_service.wsdl	0.9011114835739136
geographical-region_corporationprofession_service.wsdl	0.8946930766105652
geopolitical-entity_organizationprofession_service.wsdl	0.8847134113311768
government-organization_profession_service.wsdl	0.7624952793121338
geopolitical-entity_corporationskilledoccupation_service.wsdl	0.7534268498420715
geographical-region_companyprofession_service.wsdl	0.7498598694801331
geopolitical-entity_corporationoccupationaltrade_service.wsdl	0.745070219039917
country_companyprofession_service.wsdl	0.7442983984947205
profit-organization_profession_service.wsdl	0.7415321469306946
geopolitical-entity_professionparttimeposition_service.wsdl	0.7412500381469727
geographical-region_organizationprofession_service.wsdl	0.7383530139923096
company_profession_service.wsdl	0.7344989776611328
geopolitical-entity_professiontimemeasure_service.wsdl	0.7334243655204773
country_organizationprofession_service.wsdl	0.7308655381202698
geopolitical-entity_professionfulltimeposition_service.wsdl	0.7103864550590515
geopolitical-entity_skilledoccupationcompany_service.wsdl	0.6902177333831787
country_profession_service.wsdl	0.6867874264717102
AddLinks__service.wsdl	0.6865538954734802
country_corporationskilledoccupation_service.wsdl	0.680793821811676
geopolitical-entity_professiontimeduration_service.wsdl	0.6703357696533203
geographical-region_corporationskilledoccupation_service.wsdl	0.6689156889915466
municipal-unit_professionparttimeposition_service.wsdl	0.6688706278800964
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.6564169526100159
geopolitical-entity_companyskilledoccupation_service.wsdl	0.6561095714569092
geopolitical-entity_organizationoccupationaltrade_service.wsdl	0.655413031578064
geopolitical-entity_companyoccupationaltrade_service.wsdl	0.6448230743408203
country_corporationoccupationaltrade_service.wsdl	0.633693277835846
municipal-unit_professionfulltimeposition_service.wsdl	0.6332826614379883
geographical-region_corporationoccupationaltrade_service.wsdl	0.6242067217826843
_professiongeographical-region_USservice.wsdl	0.6142145395278931
geopolitical-entity_skilledoccupation_service.wsdl	0.6093359589576721
country_professionparttimeposition_service.wsdl	0.5827084183692932
geopolitical-entity_occupationaltrade_service.wsdl	0.5759339928627014
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.5739293694496155
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.5728806257247925
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.5728806257247925
country_professionincometax_service.wsdl	0.5643346309661865
country_organizationskilledoccupation_service.wsdl	0.5606246590614319
geographical-region_organizationskilledoccupation_JobService.wsdl	0.5569175481796265
geographical-region_organizationskilledoccupation_service.wsdl	0.5569175481796265
municipal-unit_professiontimemeasure_service.wsdl	0.556540310382843
country_companyskilledoccupation_service.wsdl	0.5503567457199097
country_professionfulltimeposition_service.wsdl	0.5493006706237793
geographical-region_companyskilledoccupation_service.wsdl	0.5460333824157715
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.5436305999755859
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.5420771837234497
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.5420771837234497
geopolitical-entity_internalchange_service.wsdl	0.5419472455978394
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.5376441478729248
country_professiontimemeasure_service.wsdl	0.5370091795921326
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.5348570942878723
public-companycountry_skilledoccupation_service.wsdl	0.5338823199272156
geopolitical-entity_hotel_service.wsdl	0.5261092782020569
profit-organization_skilledoccupation_service.wsdl	0.5228615403175354
geopolitical-entity_occupationaltradetimemeasure_service.wsdl	0.5173007845878601
geographical-region_organizationoccupationaltrade_service.wsdl	0.5129906535148621
time-measuregeopolitical-entitycity_hotel_service.wsdl	0.5109072923660278
country_organizationoccupationaltrade_service.wsdl	0.5103146433830261
municipal-unit_professiontimeduration_service.wsdl	0.5074191093444824
government-organization_skilledoccupation_service.wsdl	0.5054063200950623
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.5050510764122009
geopolitical-entity_weathersystem_service.wsdl	0.5011707544326782
