geopolitical-entity_internalchange_service.wsdl	1.0
_internalchange_EarthSystemservice.wsdl	0.8762218952178955
AddLinks__service.wsdl	0.7158522009849548
geopolitical-entity_weatherprocess_service.wsdl	0.5550619959831238
geopolitical-entity_corporationoccupationaltrade_service.wsdl	0.542471706867218
geopolitical-entity_corporationprofession_service.wsdl	0.5419472455978394
geopolitical-entity_organizationoccupationaltrade_service.wsdl	0.5393368005752563
geopolitical-entity_profession_service.wsdl	0.5331568717956543
geopolitical-entity_hotel_service.wsdl	0.5329094529151917
geopolitical-entity_skilledoccupationcompany_service.wsdl	0.5315842032432556
geopolitical-entity_weathersystem_service.wsdl	0.529447078704834
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.5282743573188782
geopolitical-entity_organizationprofession_service.wsdl	0.5282742977142334
geopolitical-entity_companyprofession_service.wsdl	0.5282278060913086
geopolitical-entity_companyoccupationaltrade_service.wsdl	0.5243657827377319
time-measuregeopolitical-entitycity_hotel_service.wsdl	0.5190365314483643
geopolitical-entity_warmfront_service.wsdl	0.5174725651741028
geopolitical-entity_occupationaltrade_service.wsdl	0.5146064162254333
time-measuregeopolitical-entitycity_accommodation_service.wsdl	0.51244056224823
geopolitical-entity_corporationskilledoccupation_service.wsdl	0.5111406445503235
durationgeopolitical-entitycity_hotel_service.wsdl	0.5091524720191956
geopolitical-entity_skilledoccupation_service.wsdl	0.5082746148109436
geopolitical-entity_accommodation_service.wsdl	0.5082396864891052
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.5060752630233765
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.5036813020706177
geopolitical-entity_professionparttimeposition_service.wsdl	0.5034052133560181
geopolitical-entity_occupationaltradetimemeasure_service.wsdl	0.5031629800796509
geopolitical-entity_lightning_service.wsdl	0.501496434211731
geopolitical-entity_professiontimemeasure_service.wsdl	0.5012203454971313
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.5008835792541504
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.5008835792541504
geopolitical-entity_weatherfront_service.wsdl	0.5001522898674011
