geopolitical-entity_occupationaltradetimeduration_service.wsdl	1.0
country_occupationaltradetimeduration_Service.wsdl	0.9379251003265381
municipal-unit_occupationaltradetimeduration_service.wsdl	0.9198734164237976
geopolitical-entity_occupationaltradetimemeasure_service.wsdl	0.8648383021354675
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.8472991585731506
geopolitical-entity_occupationaltrade_service.wsdl	0.8419914245605469
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.8391534686088562
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.8350876569747925
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.8290659189224243
geopolitical-entity_companyoccupationaltrade_service.wsdl	0.7945517301559448
geopolitical-entity_organizationoccupationaltrade_service.wsdl	0.7860608696937561
country_occupationaltradetimemeasure_Service.wsdl	0.7825111746788025
country_occupationaltradefulltimeposition_service.wsdl	0.7811188697814941
geopolitical-entity_professiontimeduration_service.wsdl	0.7767162919044495
country_occupationaltradeparttimeposition_service.wsdl	0.7726463675498962
municipal-unit_occupationaltradetimemeasure_service.wsdl	0.7656391859054565
geopolitical-entity_corporationoccupationaltrade_service.wsdl	0.7651993036270142
country_occupationaltrade_service.wsdl	0.7608581781387329
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.7516791224479675
geographical-region_organizationoccupationaltrade_service.wsdl	0.7447081208229065
geographical-region_companyoccupationaltrade_service.wsdl	0.7445364594459534
geographical-region_corporationoccupationaltrade_service.wsdl	0.7436500787734985
country_organizationoccupationaltrade_service.wsdl	0.7189551591873169
country_companyoccupationaltrade_service.wsdl	0.7179113626480103
country_corporationoccupationaltrade_service.wsdl	0.7154186367988586
country_skilledoccupationtimeduration_JobService.wsdl	0.6695877909660339
country_skilledoccupationtimeduration_service.wsdl	0.6695877909660339
DJob_service.wsdl	0.6695877909660339
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.6642351746559143
country_professiontimeduration_Service.wsdl	0.6576056480407715
municipal-unit_professiontimeduration_service.wsdl	0.6560410857200623
durationgeopolitical-entitycity_accommodation_service.wsdl	0.6113766431808472
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.610907256603241
careorganization_diagnosticprocesstimeduration_service.wsdl	0.6078308820724487
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.6040152311325073
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.6040152311325073
geopolitical-entity_professiontimemeasure_service.wsdl	0.6024088859558105
durationgeopolitical-entitycity_hotel_service.wsdl	0.5971068143844604
geopolitical-entity_professionfulltimeposition_service.wsdl	0.590055525302887
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.5872713327407837
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.5872713327407837
academic-degree_lendingduration_GermanGovservice.wsdl	0.5871996283531189
organization_experimentingtimeduration_service.wsdl	0.5813056230545044
HDP2_service.wsdl	0.5787938833236694
hospital_diagnosticprocesstimeduration_service.wsdl	0.5787938833236694
degree_lendingduration_GermanGovservice.wsdl	0.5704713463783264
medicalclinic_diagnosticprocesstimeduration_service.wsdl	0.5685186386108398
time-measuregeopolitical-entitycity_accommodation_service.wsdl	0.5680438280105591
academic-degree_fundingduration_GermanGovservice.wsdl	0.564673900604248
geopolitical-entity_professionparttimeposition_service.wsdl	0.5636311173439026
citycountryduration__HotelReserveservice.wsdl	0.5575433373451233
nationalgovernment_scholarshipquantityduration_service.wsdl	0.5542604327201843
degree_fundingduration_GermanGovservice.wsdl	0.548150897026062
geopolitical-entity_skilledoccupationcompany_service.wsdl	0.5408427715301514
geopolitical-entity_skilledoccupation_service.wsdl	0.5378987789154053
geopolitical-entity_companyskilledoccupation_service.wsdl	0.5373174548149109
time-measuregeopolitical-entitycity_hotel_service.wsdl	0.5353305339813232
award_lendingduration_GermanGovservice.wsdl	0.5353042483329773
geopolitical-entityrecorded-video_activityhotel_service.wsdl	0.5332989692687988
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.5332356095314026
geopolitical-entity_corporationskilledoccupation_service.wsdl	0.5217113494873047
AddLinks__service.wsdl	0.5212673544883728
country_skilledoccupationfulltimeposition_service.wsdl	0.5172700881958008
durationgeopolitical-entitycity_bedandbreakfast_service.wsdl	0.5170214176177979
country_skilledoccupationtimemeasure_service.wsdl	0.5082336664199829
geopolitical-entity_profession_service.wsdl	0.5071921944618225
municipal-unit_skilledoccupationtimemeasure_service.wsdl	0.5064704418182373
academic-degree_scholarshipduration_GermanGovservice.wsdl	0.5055526494979858
award_fundingduration_GermanGovservice.wsdl	0.5034677386283875
