geopolitical-entity_professiontimemeasure_service.wsdl	1.0
country_professiontimemeasure_service.wsdl	0.9021974205970764
municipal-unit_professiontimemeasure_service.wsdl	0.8779083490371704
geopolitical-entity_professionparttimeposition_service.wsdl	0.8144587278366089
geopolitical-entity_professionfulltimeposition_service.wsdl	0.8138921856880188
geopolitical-entity_profession_service.wsdl	0.8095913529396057
geopolitical-entity_professiontimeduration_service.wsdl	0.8092806339263916
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.7948561310768127
geopolitical-entity_organizationprofession_service.wsdl	0.7600966691970825
municipal-unit_professionparttimeposition_service.wsdl	0.7564640045166016
geopolitical-entity_occupationaltradetimemeasure_service.wsdl	0.7560800909996033
municipal-unit_professionfulltimeposition_service.wsdl	0.751669704914093
geopolitical-entity_companyprofession_service.wsdl	0.7504236698150635
geopolitical-entity_corporationprofession_service.wsdl	0.7334243655204773
country_professionparttimeposition_service.wsdl	0.7279052734375
country_professionfulltimeposition_service.wsdl	0.7271939516067505
country_skilledoccupationtimemeasure_service.wsdl	0.7210310101509094
municipal-unit_skilledoccupationtimemeasure_service.wsdl	0.7057498097419739
country_professiontimeduration_Service.wsdl	0.7047239542007446
government-organization_profession_service.wsdl	0.6984560489654541
municipal-unit_professiontimeduration_service.wsdl	0.69789719581604
country_profession_service.wsdl	0.6821331977844238
geographical-region_organizationprofession_service.wsdl	0.6819878220558167
geographical-region_corporationprofession_service.wsdl	0.6810773611068726
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.6732582449913025
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.6732582449913025
country_occupationaltradetimemeasure_Service.wsdl	0.672951340675354
country_organizationprofession_service.wsdl	0.6684955954551697
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.6670078635215759
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.6670078635215759
country_corporationprofession_service.wsdl	0.6659579277038574
municipal-unit_occupationaltradetimemeasure_service.wsdl	0.6591381430625916
geographical-region_companyprofession_service.wsdl	0.6567553877830505
company_profession_service.wsdl	0.6565536260604858
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.6534252166748047
time-measuregeopolitical-entitycity_hotel_service.wsdl	0.6428976655006409
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.6428952813148499
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.6425407528877258
profit-organization_profession_service.wsdl	0.6413775682449341
country_companyprofession_service.wsdl	0.6404486298561096
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.6384177207946777
time-measuregeopolitical-entitycity_accommodation_service.wsdl	0.632022500038147
careorganization_diagnosticprocesstimemeasure_service.wsdl	0.6304824352264404
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.6254720687866211
_professiongeographical-region_USservice.wsdl	0.6173404455184937
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.6137707829475403
geopolitical-entity_occupationaltradetimeduration_service.wsdl	0.6024088859558105
country_skilledoccupationparttimeposition_JobService.wsdl	0.6022975444793701
country_skilledoccupationparttimeposition_service.wsdl	0.6022975444793701
geopolitical-entity_skilledoccupationcompany_service.wsdl	0.5990775227546692
country_skilledoccupationfulltimeposition_service.wsdl	0.5954481959342957
hospital_diagnosticprocesstimemeasure_service.wsdl	0.5911150574684143
geopolitical-entity_skilledoccupation_service.wsdl	0.5885815620422363
geopolitical-entity_corporationskilledoccupation_service.wsdl	0.5860946178436279
geopolitical-entity_companyskilledoccupation_service.wsdl	0.5843126773834229
country_occupationaltradeparttimeposition_service.wsdl	0.5760201215744019
medicalclinic_diagnosticprocesstimemeasure_service.wsdl	0.569347620010376
country_occupationaltradefulltimeposition_service.wsdl	0.5642423033714294
geopolitical-entity_organizationoccupationaltrade_service.wsdl	0.5640161633491516
CAD_medical_service.wsdl	0.5613082051277161
country_skilledoccupationtimeduration_JobService.wsdl	0.5592429637908936
country_skilledoccupationtimeduration_service.wsdl	0.5592429637908936
DJob_service.wsdl	0.5592429637908936
country_organizationskilledoccupation_service.wsdl	0.5591654181480408
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.556008517742157
geographical-region_organizationskilledoccupation_JobService.wsdl	0.5558456778526306
geographical-region_organizationskilledoccupation_service.wsdl	0.5558456778526306
geopolitical-entity_weatherseasonproposition_service.wsdl	0.5529260635375977
geopolitical-entity_weatherseasontimeposition_service.wsdl	0.5478047728538513
country_professionincometax_service.wsdl	0.546580970287323
AddLinks__service.wsdl	0.5419021844863892
public-companycountry_skilledoccupation_service.wsdl	0.539668083190918
country_corporationskilledoccupation_service.wsdl	0.5394277572631836
geographical-region_corporationskilledoccupation_service.wsdl	0.5388033986091614
time-measuregeopolitical-entitycity_bedandbreakfast_service.wsdl	0.5362370014190674
geopolitical-entity_corporationoccupationaltrade_service.wsdl	0.5346391201019287
geopolitical-entity_companyoccupationaltrade_service.wsdl	0.5237553715705872
country_companyskilledoccupation_service.wsdl	0.5200077295303345
geopolitical-entity_occupationaltrade_service.wsdl	0.5193545818328857
geographical-region_companyskilledoccupation_service.wsdl	0.5186201930046082
country_sportsposition_service.wsdl	0.5135089755058289
government-organization_skilledoccupation_service.wsdl	0.5132157206535339
country_occupationaltradetimeduration_Service.wsdl	0.510021984577179
municipal-unit_occupationaltradetimeduration_service.wsdl	0.5084290504455566
companycountry_skilledoccupation_service.wsdl	0.5083438158035278
time-measurecountrycity_hotel_service.wsdl	0.5073464512825012
geopolitical-entity_internalchange_service.wsdl	0.5012203454971313
