geopolitical-entity_professiontimeduration_service.wsdl	1.0
country_professiontimeduration_Service.wsdl	0.9110231995582581
municipal-unit_professiontimeduration_service.wsdl	0.8875153064727783
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.8125921487808228
geopolitical-entity_professiontimemeasure_service.wsdl	0.8092806339263916
geopolitical-entity_professionfulltimeposition_service.wsdl	0.798231303691864
geopolitical-entity_professionparttimeposition_service.wsdl	0.7916682362556458
geopolitical-entity_occupationaltradetimeduration_service.wsdl	0.7767162919044495
geopolitical-entity_profession_service.wsdl	0.7665860652923584
country_skilledoccupationtimeduration_JobService.wsdl	0.7443822026252747
country_skilledoccupationtimeduration_service.wsdl	0.7443822026252747
DJob_service.wsdl	0.7443822026252747
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.7270976901054382
municipal-unit_professionfulltimeposition_service.wsdl	0.7222878336906433
municipal-unit_professionparttimeposition_service.wsdl	0.7194153666496277
country_professionfulltimeposition_service.wsdl	0.7080301642417908
geopolitical-entity_companyprofession_service.wsdl	0.7036355137825012
geopolitical-entity_organizationprofession_service.wsdl	0.7018263936042786
country_professionparttimeposition_service.wsdl	0.7009039521217346
country_occupationaltradetimeduration_Service.wsdl	0.6999983191490173
country_professiontimemeasure_service.wsdl	0.6919254660606384
municipal-unit_occupationaltradetimeduration_service.wsdl	0.6836385726928711
municipal-unit_professiontimemeasure_service.wsdl	0.6716787219047546
geopolitical-entity_corporationprofession_service.wsdl	0.6703357696533203
organization_experimentingtimeduration_service.wsdl	0.6686466932296753
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.666092038154602
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.666092038154602
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.6658732295036316
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.6658732295036316
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.6524323225021362
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.6458319425582886
careorganization_diagnosticprocesstimeduration_service.wsdl	0.6442449688911438
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.6413148045539856
geographical-region_organizationprofession_service.wsdl	0.6375163793563843
geographical-region_corporationprofession_service.wsdl	0.6294357180595398
citycountryduration__HotelReserveservice.wsdl	0.6279697418212891
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.6279602646827698
country_profession_service.wsdl	0.6275214552879333
durationgeopolitical-entitycity_accommodation_service.wsdl	0.6272270083427429
geographical-region_companyprofession_service.wsdl	0.626083493232727
government-organization_profession_service.wsdl	0.6260677576065063
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.6216918230056763
HDP2_service.wsdl	0.613361656665802
hospital_diagnosticprocesstimeduration_service.wsdl	0.613361656665802
_professiongeographical-region_USservice.wsdl	0.6120331287384033
durationgeopolitical-entitycity_hotel_service.wsdl	0.6118117570877075
geopolitical-entity_occupationaltradetimemeasure_service.wsdl	0.6097142696380615
company_profession_service.wsdl	0.6029351949691772
country_organizationprofession_service.wsdl	0.5991482734680176
academic-degree_lendingduration_GermanGovservice.wsdl	0.5931029915809631
academic-degree_fundingduration_GermanGovservice.wsdl	0.5930876731872559
country_skilledoccupationparttimeposition_JobService.wsdl	0.592631995677948
country_skilledoccupationparttimeposition_service.wsdl	0.592631995677948
country_skilledoccupationfulltimeposition_service.wsdl	0.5924721360206604
medicalclinic_diagnosticprocesstimeduration_service.wsdl	0.5888157486915588
country_corporationprofession_service.wsdl	0.5881081819534302
country_companyprofession_service.wsdl	0.5837607383728027
time-measuregeopolitical-entitycity_accommodation_service.wsdl	0.5824306011199951
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.5819774270057678
degree_fundingduration_GermanGovservice.wsdl	0.5787325501441956
geopolitical-entity_weatherseasontimeposition_service.wsdl	0.5768791437149048
degree_lendingduration_GermanGovservice.wsdl	0.5761610865592957
profit-organization_profession_service.wsdl	0.5761129856109619
geopolitical-entity_skilledoccupationcompany_service.wsdl	0.5756441950798035
geopolitical-entity_skilledoccupation_service.wsdl	0.5730374455451965
nationalgovernment_scholarshipquantityduration_service.wsdl	0.5704858899116516
country_occupationaltradeparttimeposition_service.wsdl	0.5657306909561157
geopolitical-entity_companyskilledoccupation_service.wsdl	0.565079391002655
country_skilledoccupationtimemeasure_service.wsdl	0.5620255470275879
academic-degree_scholarshipduration_GermanGovservice.wsdl	0.5619714856147766
country_occupationaltradefulltimeposition_service.wsdl	0.5610749125480652
degree_scholarshipduration_GermanGovservice.wsdl	0.5596610903739929
geopolitical-entity_corporationskilledoccupation_service.wsdl	0.5501182675361633
municipal-unit_skilledoccupationtimemeasure_service.wsdl	0.5485003590583801
time-measuregeopolitical-entitycity_hotel_service.wsdl	0.5480930209159851
durationgeopolitical-entitycity_bedandbreakfast_service.wsdl	0.5381451845169067
geographical-region_organizationskilledoccupation_JobService.wsdl	0.5330803990364075
geographical-region_organizationskilledoccupation_service.wsdl	0.5330803990364075
AddLinks__service.wsdl	0.5316741466522217
geopolitical-entity_organizationoccupationaltrade_service.wsdl	0.5285640358924866
award_lendingduration_GermanGovservice.wsdl	0.5266107320785522
country_organizationskilledoccupation_service.wsdl	0.5228528380393982
geopolitical-entity_weatherseasonproposition_service.wsdl	0.5198116302490234
award_fundingduration_GermanGovservice.wsdl	0.5196980237960815
geographical-region_corporationskilledoccupation_service.wsdl	0.5111368894577026
geopolitical-entityrecorded-video_activityhotel_service.wsdl	0.5103251934051514
country_occupationaltradetimemeasure_Service.wsdl	0.5098021030426025
geographical-region_companyskilledoccupation_service.wsdl	0.5092426538467407
public-companycountry_skilledoccupation_service.wsdl	0.5040032863616943
geopolitical-entity_occupationaltrade_service.wsdl	0.5035766959190369
geopolitical-entity_companyoccupationaltrade_service.wsdl	0.5006104707717896
