government_scholarship_service.wsdl	1.0
nationalgovernment_scholarship_service.wsdl	0.9642491936683655
governmentorganization_scholarship_service.wsdl	0.9612435102462769
governmentaward_scholarship_service.wsdl	0.95292067527771
degreegovernment_scholarship_service.wsdl	0.9321290850639343
governmentdegree_scholarship_service.wsdl	0.9321290850639343
governmentdegree_scholarship_TheBestservice.wsdl	0.9321290850639343
degreegovernmentorganization_scholarship_service.wsdl	0.9164412021636963
degreenationalgovernment_scholarship_service.wsdl	0.9158486127853394
academic-degreegovernment_scholarship_service.wsdl	0.905122697353363
award_scholarship_GermanGovservice.wsdl	0.9007548093795776
degree_scholarship_GermanGovservice.wsdl	0.8837276697158813
government_scholarshiporganization_service.wsdl	0.8835064172744751
academic-degree_scholarship_GermanGovservice.wsdl	0.8686589598655701
nationalgovernment_scholarshipquantity_service.wsdl	0.8015355467796326
governmentdegree_scholarshipquantity_service.wsdl	0.7763065695762634
award_scholarshipduration_GermanGovservice.wsdl	0.7523938417434692
award_scholarshipduration_SwissGovservice.wsdl	0.7523938417434692
academic-degree_scholarshipduration_GermanGovservice.wsdl	0.7421095371246338
degree_scholarshipduration_GermanGovservice.wsdl	0.7202414870262146
nationalgovernment_scholarshipquantityduration_service.wsdl	0.665999174118042
nationalgovernment_physical-quantityscholarshiplandarea_service.wsdl	0.6178606152534485
academic-degreegovernmentorganization_funding_service.wsdl	0.541372537612915
academic-degreegovernment_funding_service.wsdl	0.5219763517379761
awardgovernment_funding_service.wsdl	0.5069950819015503
