government-organization_skilledoccupation_service.wsdl	1.0
country_organizationskilledoccupation_service.wsdl	0.9492371678352356
country_skilledoccupation_jobsservice.wsdl	0.9447880983352661
country_skilledoccupation_service.wsdl	0.9447880983352661
company_skilledoccupation_service.wsdl	0.9438377022743225
companycountry_skilledoccupation_service.wsdl	0.9431957006454468
_skilledoccupation_BMWservice.wsdl	0.9396426677703857
profit-organization_skilledoccupation_service.wsdl	0.9364162087440491
city_skilledoccupation_service.wsdl	0.9308761358261108
public-companycountry_skilledoccupation_service.wsdl	0.9306210279464722
citycountry_skilledoccupation_service.wsdl	0.9249542951583862
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.9192050099372864
geographical-region_organizationskilledoccupation_JobService.wsdl	0.9073277115821838
geographical-region_organizationskilledoccupation_service.wsdl	0.9073277115821838
country_corporationskilledoccupation_service.wsdl	0.9023057222366333
country_companyskilledoccupation_service.wsdl	0.8993979096412659
geopolitical-entity_skilledoccupation_service.wsdl	0.8914090991020203
geopolitical-entity_companyskilledoccupation_service.wsdl	0.8757551312446594
geographical-region_corporationskilledoccupation_service.wsdl	0.8660721778869629
geopolitical-entity_corporationskilledoccupation_service.wsdl	0.8625686168670654
geopolitical-entity_skilledoccupationcompany_service.wsdl	0.8594030141830444
geographical-region_companyskilledoccupation_service.wsdl	0.857010006904602
country_skilledoccupationtimemeasure_service.wsdl	0.8186718821525574
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.8156580328941345
country_skilledoccupationparttimeposition_JobService.wsdl	0.80568528175354
country_skilledoccupationparttimeposition_service.wsdl	0.80568528175354
municipal-unit_skilledoccupationtimemeasure_service.wsdl	0.8005257844924927
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.7962334156036377
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.7962334156036377
country_skilledoccupationfulltimeposition_service.wsdl	0.7868238091468811
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.7804199457168579
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.7804199457168579
country_skilledoccupationtimeduration_JobService.wsdl	0.7716963291168213
country_skilledoccupationtimeduration_service.wsdl	0.7716963291168213
DJob_service.wsdl	0.7716963291168213
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.7706695795059204
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.7614027857780457
government-organization_profession_service.wsdl	0.5839793682098389
geopolitical-entity_organizationprofession_service.wsdl	0.5560278296470642
geographical-region_organizationprofession_service.wsdl	0.5445470809936523
country_organizationprofession_service.wsdl	0.5320243239402771
academic-degreegovernmentorganization_unilateralgiving_service.wsdl	0.5221471786499023
geopolitical-entity_organizationoccupationaltrade_service.wsdl	0.5142714381217957
geopolitical-entity_professionparttimeposition_service.wsdl	0.514018714427948
geopolitical-entity_professiontimemeasure_service.wsdl	0.5132157206535339
geographical-region_corporationprofession_service.wsdl	0.5113413333892822
geopolitical-entity_profession_service.wsdl	0.5063097476959229
geopolitical-entity_corporationprofession_service.wsdl	0.5054063200950623
geopolitical-entity_professionfulltimeposition_service.wsdl	0.5053415298461914
country_organizationoccupationaltrade_service.wsdl	0.5012121796607971
