governmentorganizationmissile_unilateralgiving_service.wsdl	1.0
degreegovernment_unilateralgiving_service.wsdl	0.8209604620933533
academic-degreegovernmentorganization_unilateralgiving_service.wsdl	0.8151234984397888
academic-degreegovernment_unilateralgiving_service.wsdl	0.7851789593696594
missilegovernment_giving_Borrowservice.wsdl	0.6543626189231873
missilegovernment_giving_service.wsdl	0.6543626189231873
missilegovernmentorganization_funding_service.wsdl	0.6315268874168396
governmentmissileweapon_funding_service.wsdl	0.6004797220230103
governmentmissile_funding_Reliableservice.wsdl	0.5978865623474121
governmentmissile_funding_service.wsdl	0.5978865623474121
ballisticmissilegovernmentorganization_fundingrange_service.wsdl	0.5947216153144836
missilegovernmentorganization_fundingrange_service.wsdl	0.5909252166748047
governmentmissile_financing_service.wsdl	0.5903283357620239
ballisticmissilegovernmentorganization_financingrange_service.wsdl	0.5850382447242737
missilegovernment_givingrange_service.wsdl	0.5823938250541687
missilegovernmentorganization_financingrange_service.wsdl	0.5781813859939575
governmentmissileweapon_fundingfunding_service.wsdl	0.5762714743614197
ballisticmissilegovernment_givingrange_service.wsdl	0.573757529258728
missilegovernmentorganization_givingrange_service.wsdl	0.5724771022796631
ballisticmissilegovernmentorganization_givingrange_service.wsdl	0.5658309459686279
ballisticmissilegovernment_fundingrange_service.wsdl	0.5599701404571533
ballisticmissilegovernment_lendingrange_service.wsdl	0.5577602982521057
missilegovernment_fundingrange_service.wsdl	0.5554722547531128
ballisticmissilegovernmentorganization_lendingrange_service.wsdl	0.554939866065979
missilegovernment_lendingrange_service.wsdl	0.5515544414520264
missilegovernmentorganization_lendingrange_service.wsdl	0.548831045627594
ballisticmissilegovernment_financingrange_service.wsdl	0.5465439558029175
missilegovernment_financingrange_service.wsdl	0.5374963879585266
weaponmissile_funding_Iraqservice.wsdl	0.520347535610199
missile_funding_Asianservice.wsdl	0.5116362571716309
missile_funding_Indiaservice.wsdl	0.5116362571716309
missile_funding_NKoreaservice.wsdl	0.5116362571716309
missile_funding_Pakservice.wsdl	0.5116362571716309
