government_scholarshiporganization_service.wsdl	1.0
governmentorganization_scholarship_service.wsdl	0.9784083962440491
degreegovernmentorganization_scholarship_service.wsdl	0.916420042514801
government_scholarship_service.wsdl	0.8835064172744751
nationalgovernment_scholarship_service.wsdl	0.8741728663444519
governmentaward_scholarship_service.wsdl	0.8521220684051514
degreenationalgovernment_scholarship_service.wsdl	0.822119414806366
degreegovernment_scholarship_service.wsdl	0.8165714740753174
governmentdegree_scholarship_service.wsdl	0.8165714740753174
governmentdegree_scholarship_TheBestservice.wsdl	0.8165714740753174
academic-degreegovernment_scholarship_service.wsdl	0.8032581210136414
award_scholarship_GermanGovservice.wsdl	0.788486659526825
academic-degree_scholarship_GermanGovservice.wsdl	0.7555625438690186
degree_scholarship_GermanGovservice.wsdl	0.7550346851348877
nationalgovernment_scholarshipquantity_service.wsdl	0.7431156635284424
governmentdegree_scholarshipquantity_service.wsdl	0.6969859004020691
award_scholarshipduration_GermanGovservice.wsdl	0.6519424319267273
award_scholarshipduration_SwissGovservice.wsdl	0.6519424319267273
academic-degree_scholarshipduration_GermanGovservice.wsdl	0.6396337151527405
academic-degreegovernmentorganization_funding_service.wsdl	0.6352521181106567
nationalgovernment_scholarshipquantityduration_service.wsdl	0.6108759045600891
degree_scholarshipduration_GermanGovservice.wsdl	0.6091784834861755
nationalgovernment_physical-quantityscholarshiplandarea_service.wsdl	0.6033264398574829
country_organizationprofession_service.wsdl	0.5961132645606995
geopolitical-entity_organizationprofession_service.wsdl	0.5779376029968262
geographical-region_organizationprofession_service.wsdl	0.5717971324920654
government-organization_profession_service.wsdl	0.5536157488822937
university_academic-support-staff_service.wsdl	0.5421525239944458
governmentorganizationselfpowereddevice_funding_service.wsdl	0.5359686613082886
missilegovernmentorganization_funding_service.wsdl	0.5344727039337158
country_organizationskilledoccupation_service.wsdl	0.5302733778953552
academic-degreegovernmentorganization_lending_service.wsdl	0.5246841907501221
profit-organization_profession_service.wsdl	0.5198970437049866
awardgovernment_funding_service.wsdl	0.5193870067596436
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.5174072980880737
academic-degreegovernment_funding_service.wsdl	0.5166326761245728
country_organizationoccupationaltrade_service.wsdl	0.5145918130874634
geographical-region_organizationskilledoccupation_JobService.wsdl	0.5041231513023376
geographical-region_organizationskilledoccupation_service.wsdl	0.5041231513023376
