higher-educational-organization_professor-in-academia_Pioneerservice.wsdl	1.0
higher-educational-organization_professor-in-academia_service.wsdl	1.0
higher-educational-organization_lecturer-in-academia_MostUsedservice.wsdl	0.935845136642456
higher-educational-organization_lecturer-in-academia_service.wsdl	0.935845136642456
university_professor-in-academia_service.wsdl	0.9331498146057129
educational-organization_lecturer-in-academia_service.wsdl	0.9140133261680603
organization_lecturer-in-academia_service.wsdl	0.8888365030288696
learning-centred-organization_lecturer-in-academia_service.wsdl	0.8822441101074219
university_lecturer-in-academiaCurrentSemmester_service.wsdl	0.8699356913566589
university_lecturer-in-academia_Recommendservice.wsdl	0.8699356913566589
university_lecturer-in-academia_service.wsdl	0.8699356913566589
_lecturer-in-academiaMunchenUniversity_service.wsdl	0.8601474165916443
_lecturer-in-academiaSaarlandUniversity_service.wsdl	0.8601474165916443
_lecturer-in-academiaZambiaUniversity_service.wsdl	0.8601474165916443
university_senior-lecturer-in-academia_service.wsdl	0.8178987503051758
higher-educational-organization_senior-research-fellow-in-academia_Firstservice.wsdl	0.7580359578132629
higher-educational-organization_senior-research-fellow-in-academia_service.wsdl	0.7580359578132629
university_research-fellow-in-academia_service.wsdl	0.7515664100646973
professor-in-academia_address_service.wsdl	0.7245270609855652
researcher-in-academia_abstract-information_service.wsdl	0.6767715215682983
university_researcher_service.wsdl	0.6486275792121887
researcher-in-academia_address_service.wsdl	0.64449542760849
researcher-in-academia_address_TREEservice.wsdl	0.64449542760849
researcher-in-academia_address_ZOOservice.wsdl	0.64449542760849
research-assistant-in-academia_address_service.wsdl	0.6319905519485474
sfnovel_authorauthor_BookOntoservice.wsdl	0.5427918434143066
sciencefictionnovel_author_MyOntoservice.wsdl	0.5244981646537781
academic-degreegovernmentorganization_funding_service.wsdl	0.5222455263137817
research-fellow-in-academia_publication-reference_service.wsdl	0.5186773538589478
government-organization_profession_service.wsdl	0.5085416436195374
university_academic-support-staff_service.wsdl	0.5025970339775085
academic-degreegovernment_scholarship_service.wsdl	0.5024605393409729
