missilegovernmentorganization_givingrange_service.wsdl	1.0
missilegovernment_givingrange_service.wsdl	0.9626559019088745
ballisticmissilegovernmentorganization_givingrange_service.wsdl	0.956179141998291
ballisticmissilegovernment_givingrange_service.wsdl	0.923554003238678
ballisticmissilegovernmentorganization_financingrange_service.wsdl	0.7883384823799133
ballisticmissilegovernmentorganization_lendingrange_service.wsdl	0.7807526588439941
missilegovernmentorganization_financingrange_service.wsdl	0.7785000205039978
ballisticmissilegovernmentorganization_fundingrange_service.wsdl	0.7762848138809204
missilegovernmentorganization_lendingrange_service.wsdl	0.7762161493301392
missilegovernmentorganization_fundingrange_service.wsdl	0.7673400640487671
ballisticmissilegovernment_financingrange_service.wsdl	0.7569916248321533
missilegovernment_giving_Borrowservice.wsdl	0.7558014392852783
missilegovernment_giving_service.wsdl	0.7558014392852783
ballisticmissilegovernment_fundingrange_service.wsdl	0.7494277358055115
missilegovernment_financingrange_service.wsdl	0.7468740940093994
ballisticmissilegovernment_lendingrange_service.wsdl	0.7461884021759033
missilegovernment_fundingrange_service.wsdl	0.7419556975364685
missilegovernment_lendingrange_service.wsdl	0.7365050911903381
governmentorganizationmissile_unilateralgiving_service.wsdl	0.5724771022796631
missilegovernmentorganization_funding_service.wsdl	0.5081549882888794
