missile_funding_Asianservice.wsdl	1.0
missile_funding_Indiaservice.wsdl	1.0
missile_funding_NKoreaservice.wsdl	1.0
missile_funding_Pakservice.wsdl	1.0
governmentmissile_funding_Reliableservice.wsdl	0.9675110578536987
governmentmissile_funding_service.wsdl	0.9675110578536987
governmentmissileweapon_fundingfunding_service.wsdl	0.9434705972671509
weaponmissile_funding_Iraqservice.wsdl	0.9400124549865723
governmentmissileweapon_funding_service.wsdl	0.9318535327911377
missilegovernmentorganization_funding_service.wsdl	0.9307158589363098
missilegovernment_fundingrange_service.wsdl	0.8435990810394287
missilegovernmentorganization_fundingrange_service.wsdl	0.8289658427238464
governmentweapon_funding_service.wsdl	0.8212255239486694
ballisticmissilegovernment_fundingrange_service.wsdl	0.8176329731941223
projectilegovernment_funding_service.wsdl	0.8168948888778687
ballisticmissilegovernmentorganization_fundingrange_service.wsdl	0.8114539980888367
nationalgovernmentweapon_funding_service.wsdl	0.7883448600769043
government_funding_ABombservice.wsdl	0.781486988067627
government_funding_BallMissileservice.wsdl	0.781486988067627
government_funding_ForPhDservice.wsdl	0.781486988067627
government_funding_Missileservice.wsdl	0.781486988067627
governmentmissile_financing_service.wsdl	0.7608844637870789
missile_financing_Chinaservice.wsdl	0.7527641654014587
missile_financing_Russianservice.wsdl	0.7527641654014587
missile_financing_USservice.wsdl	0.7527641654014587
awardgovernment_funding_service.wsdl	0.7359588742256165
degreegovernment_funding_service.wsdl	0.7332481145858765
degree_funding_GermanGovservice.wsdl	0.730137050151825
award_funding_GermanGovservice.wsdl	0.7275031805038452
governmentorganizationselfpowereddevice_funding_service.wsdl	0.7063723206520081
academic-degreegovernment_funding_service.wsdl	0.6974696516990662
academic-degree_funding_GermanGovservice.wsdl	0.6895946860313416
academic-degreegovernmentorganization_funding_service.wsdl	0.6846430897712708
ballisticmissilegovernmentorganization_financingrange_service.wsdl	0.6699387431144714
missilegovernmentorganization_financingrange_service.wsdl	0.6670861840248108
ballisticmissilegovernment_financingrange_service.wsdl	0.6628451943397522
missilegovernment_financingrange_service.wsdl	0.6626557111740112
award_fundingduration_GermanGovservice.wsdl	0.6048148274421692
degree_fundingduration_GermanGovservice.wsdl	0.5956453084945679
academic-degree_fundingduration_GermanGovservice.wsdl	0.595637857913971
ballisticmissilegovernment_lendingrange_service.wsdl	0.539055585861206
ballisticmissilegovernmentorganization_lendingrange_service.wsdl	0.5369495153427124
missilegovernment_lendingrange_service.wsdl	0.5240936279296875
missilegovernmentorganization_lendingrange_service.wsdl	0.5222050547599792
governmentorganizationmissile_unilateralgiving_service.wsdl	0.5116362571716309
