missilegovernment_giving_Borrowservice.wsdl	1.0
missilegovernment_giving_service.wsdl	1.0
missilegovernment_givingrange_service.wsdl	0.8042266368865967
ballisticmissilegovernment_givingrange_service.wsdl	0.7700753808021545
missilegovernmentorganization_givingrange_service.wsdl	0.7558014392852783
ballisticmissilegovernmentorganization_givingrange_service.wsdl	0.7300965189933777
governmentorganizationmissile_unilateralgiving_service.wsdl	0.6543626189231873
ballisticmissilegovernment_lendingrange_service.wsdl	0.5797025561332703
missilegovernment_lendingrange_service.wsdl	0.5673168897628784
governmentmissileweapon_funding_service.wsdl	0.5589322447776794
ballisticmissilegovernment_fundingrange_service.wsdl	0.5580295920372009
ballisticmissilegovernmentorganization_fundingrange_service.wsdl	0.5562205910682678
ballisticmissilegovernmentorganization_financingrange_service.wsdl	0.5549534559249878
ballisticmissilegovernment_financingrange_service.wsdl	0.55222487449646
ballisticmissilegovernmentorganization_lendingrange_service.wsdl	0.5519446134567261
governmentmissile_financing_service.wsdl	0.549605131149292
governmentmissile_funding_Reliableservice.wsdl	0.5445663928985596
governmentmissile_funding_service.wsdl	0.5445663928985596
missilegovernment_fundingrange_service.wsdl	0.5434567332267761
missilegovernmentorganization_fundingrange_service.wsdl	0.5383771657943726
missilegovernmentorganization_lendingrange_service.wsdl	0.5364434123039246
missilegovernmentorganization_financingrange_service.wsdl	0.5357292890548706
missilegovernment_financingrange_service.wsdl	0.5346378087997437
missilegovernmentorganization_funding_service.wsdl	0.5332676768302917
governmentmissileweapon_fundingfunding_service.wsdl	0.5304356217384338
