municipal-unit_professiontimemeasure_service.wsdl	1.0
country_professiontimemeasure_service.wsdl	0.9327698945999146
geopolitical-entity_professiontimemeasure_service.wsdl	0.8779083490371704
municipal-unit_professiontimeduration_service.wsdl	0.7943128943443298
municipal-unit_professionfulltimeposition_service.wsdl	0.7797420620918274
municipal-unit_professionparttimeposition_service.wsdl	0.7741667628288269
municipal-unit_skilledoccupationtimemeasure_service.wsdl	0.7741314172744751
municipal-unit_occupationaltradetimemeasure_service.wsdl	0.7348887324333191
country_professionfulltimeposition_service.wsdl	0.723308265209198
country_professionparttimeposition_service.wsdl	0.7127887010574341
country_skilledoccupationtimemeasure_service.wsdl	0.7114410996437073
country_professiontimeduration_Service.wsdl	0.7111179828643799
government-organization_profession_service.wsdl	0.6917064785957336
country_profession_service.wsdl	0.6824462413787842
geopolitical-entity_professionfulltimeposition_service.wsdl	0.6805490255355835
company_profession_service.wsdl	0.6781122088432312
geopolitical-entity_professiontimeduration_service.wsdl	0.6716787219047546
geopolitical-entity_professionparttimeposition_service.wsdl	0.6702941656112671
country_occupationaltradetimemeasure_Service.wsdl	0.6692075133323669
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.6633827686309814
careorganization_diagnosticprocesstimemeasure_service.wsdl	0.658660352230072
country_companyprofession_service.wsdl	0.6568533182144165
hospital_diagnosticprocesstimemeasure_service.wsdl	0.6475148797035217
country_corporationprofession_service.wsdl	0.636754035949707
geographical-region_companyprofession_service.wsdl	0.6352241039276123
country_organizationprofession_service.wsdl	0.6346974968910217
medicalclinic_diagnosticprocesstimemeasure_service.wsdl	0.6266472339630127
geopolitical-entity_occupationaltradetimemeasure_service.wsdl	0.6265415549278259
geographical-region_corporationprofession_service.wsdl	0.6202897429466248
geographical-region_organizationprofession_service.wsdl	0.6178954243659973
profit-organization_profession_service.wsdl	0.6125843524932861
geopolitical-entity_profession_service.wsdl	0.6046524047851562
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.6040048599243164
geopolitical-entity_companyprofession_service.wsdl	0.5954071283340454
CAD_medical_service.wsdl	0.5828090310096741
time-measurecountrycity_hotel_service.wsdl	0.5798861980438232
geopolitical-entity_organizationprofession_service.wsdl	0.5764557123184204
country_professionincometax_service.wsdl	0.5668037533760071
municipal-unit_occupationaltradetimeduration_service.wsdl	0.5631802082061768
country_skilledoccupationfulltimeposition_service.wsdl	0.5610650777816772
country_skilledoccupationparttimeposition_JobService.wsdl	0.5577279329299927
country_skilledoccupationparttimeposition_service.wsdl	0.5577279329299927
geopolitical-entity_corporationprofession_service.wsdl	0.556540310382843
_professiongeographical-region_USservice.wsdl	0.549322783946991
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.5429865121841431
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.5416920781135559
country_occupationaltradeparttimeposition_service.wsdl	0.5344812273979187
real-time_geocoding.wsdl	0.5342877507209778
country_occupationaltradefulltimeposition_service.wsdl	0.5337076187133789
time-measuregeopolitical-entitycity_hotel_service.wsdl	0.5330473184585571
country_skilledoccupationtimeduration_JobService.wsdl	0.5310803651809692
country_skilledoccupationtimeduration_service.wsdl	0.5310803651809692
DJob_service.wsdl	0.5310803651809692
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.5261324644088745
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.5261324644088745
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.521799623966217
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.521799623966217
public-companycountry_skilledoccupation_service.wsdl	0.5159782767295837
careorganization_diagnosticprocesstimeduration_service.wsdl	0.5089476108551025
time-measuregeopolitical-entitycity_accommodation_service.wsdl	0.5059476494789124
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.5002418160438538
