municipal-unit_occupationaltradetimeduration_service.wsdl	1.0
country_occupationaltradetimeduration_Service.wsdl	0.9548565745353699
geopolitical-entity_occupationaltradetimeduration_service.wsdl	0.9198734164237976
municipal-unit_occupationaltradetimemeasure_service.wsdl	0.851402759552002
country_occupationaltradetimemeasure_Service.wsdl	0.8033303022384644
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.7938625812530518
geopolitical-entity_occupationaltradetimemeasure_service.wsdl	0.7842568755149841
country_occupationaltradefulltimeposition_service.wsdl	0.7824651598930359
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.7776157259941101
country_occupationaltradeparttimeposition_service.wsdl	0.7642025947570801
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.758086085319519
country_occupationaltrade_service.wsdl	0.7579095363616943
municipal-unit_professiontimeduration_service.wsdl	0.7522162795066833
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.7392028570175171
geographical-region_companyoccupationaltrade_service.wsdl	0.7333815693855286
country_companyoccupationaltrade_service.wsdl	0.7276622653007507
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.7244315147399902
geopolitical-entity_occupationaltrade_service.wsdl	0.714540421962738
geographical-region_corporationoccupationaltrade_service.wsdl	0.7059938311576843
geographical-region_organizationoccupationaltrade_service.wsdl	0.7033304572105408
country_corporationoccupationaltrade_service.wsdl	0.6943740248680115
country_organizationoccupationaltrade_service.wsdl	0.6936417818069458
geopolitical-entity_companyoccupationaltrade_service.wsdl	0.6933705806732178
geopolitical-entity_professiontimeduration_service.wsdl	0.6836385726928711
country_professiontimeduration_Service.wsdl	0.6795462369918823
country_skilledoccupationtimeduration_JobService.wsdl	0.6672515273094177
country_skilledoccupationtimeduration_service.wsdl	0.6672515273094177
DJob_service.wsdl	0.6672515273094177
geopolitical-entity_organizationoccupationaltrade_service.wsdl	0.6597414612770081
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.6566004753112793
geopolitical-entity_corporationoccupationaltrade_service.wsdl	0.6456138491630554
careorganization_diagnosticprocesstimeduration_service.wsdl	0.6350703835487366
HDP2_service.wsdl	0.6278505921363831
hospital_diagnosticprocesstimeduration_service.wsdl	0.6278505921363831
medicalclinic_diagnosticprocesstimeduration_service.wsdl	0.6194747090339661
citycountryduration__HotelReserveservice.wsdl	0.6164005994796753
academic-degree_lendingduration_GermanGovservice.wsdl	0.5941468477249146
organization_experimentingtimeduration_service.wsdl	0.5941445827484131
degree_lendingduration_GermanGovservice.wsdl	0.5806669592857361
academic-degree_fundingduration_GermanGovservice.wsdl	0.57498699426651
municipal-unit_skilledoccupationtimemeasure_service.wsdl	0.5716391801834106
nationalgovernment_scholarshipquantityduration_service.wsdl	0.563707172870636
municipal-unit_professiontimemeasure_service.wsdl	0.5631802082061768
degree_fundingduration_GermanGovservice.wsdl	0.5622007250785828
award_lendingduration_GermanGovservice.wsdl	0.5445592999458313
municipal-unit_professionfulltimeposition_service.wsdl	0.5279676914215088
award_fundingduration_GermanGovservice.wsdl	0.5164614319801331
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.5146694779396057
durationgeopolitical-entitycity_accommodation_service.wsdl	0.513884961605072
country_skilledoccupationtimemeasure_service.wsdl	0.5088960528373718
academic-degree_scholarshipduration_GermanGovservice.wsdl	0.5084629058837891
geopolitical-entity_professiontimemeasure_service.wsdl	0.5084290504455566
durationgeopolitical-entitycity_hotel_service.wsdl	0.508223295211792
durationcountrycity_hotel_service.wsdl	0.5040713548660278
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.5028126239776611
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.5028126239776611
degree_scholarshipduration_GermanGovservice.wsdl	0.502799391746521
country_skilledoccupationfulltimeposition_service.wsdl	0.5010574460029602
