municipal-unit_occupationaltradetimemeasure_service.wsdl	1.0
country_occupationaltradetimemeasure_Service.wsdl	0.9517834186553955
geopolitical-entity_occupationaltradetimemeasure_service.wsdl	0.9133037328720093
municipal-unit_occupationaltradetimeduration_service.wsdl	0.851402759552002
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.7978299856185913
country_occupationaltradetimeduration_Service.wsdl	0.7911750078201294
country_occupationaltradefulltimeposition_service.wsdl	0.787996232509613
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.7866436243057251
country_occupationaltrade_service.wsdl	0.786017656326294
country_occupationaltradeparttimeposition_service.wsdl	0.7751835584640503
geopolitical-entity_occupationaltradetimeduration_service.wsdl	0.7656391859054565
country_companyoccupationaltrade_service.wsdl	0.7609323263168335
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.7578415274620056
geographical-region_companyoccupationaltrade_service.wsdl	0.7481168508529663
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.7437325716018677
country_corporationoccupationaltrade_service.wsdl	0.742882251739502
country_organizationoccupationaltrade_service.wsdl	0.7364466190338135
geographical-region_corporationoccupationaltrade_service.wsdl	0.7351534962654114
municipal-unit_professiontimemeasure_service.wsdl	0.7348887324333191
geopolitical-entity_occupationaltrade_service.wsdl	0.7312379479408264
geographical-region_organizationoccupationaltrade_service.wsdl	0.7272957563400269
geopolitical-entity_companyoccupationaltrade_service.wsdl	0.7159484028816223
municipal-unit_skilledoccupationtimemeasure_service.wsdl	0.7057464122772217
geopolitical-entity_organizationoccupationaltrade_service.wsdl	0.6908566951751709
geopolitical-entity_corporationoccupationaltrade_service.wsdl	0.6809038519859314
geopolitical-entity_professiontimemeasure_service.wsdl	0.6591381430625916
country_professiontimemeasure_service.wsdl	0.6551651954650879
country_skilledoccupationtimemeasure_service.wsdl	0.6419320702552795
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.6296786665916443
careorganization_diagnosticprocesstimemeasure_service.wsdl	0.6211416721343994
hospital_diagnosticprocesstimemeasure_service.wsdl	0.6087058782577515
medicalclinic_diagnosticprocesstimemeasure_service.wsdl	0.6030420064926147
municipal-unit_professiontimeduration_service.wsdl	0.5745490193367004
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.5686328411102295
CAD_medical_service.wsdl	0.5506716370582581
municipal-unit_professionfulltimeposition_service.wsdl	0.5415361523628235
time-measuregeopolitical-entitycity_hotel_service.wsdl	0.5323805212974548
time-measurecountrycity_hotel_service.wsdl	0.5318048000335693
beverage_taxfreepricephysical-quantity_service.wsdl	0.5139296650886536
time-measuregeopolitical-entitycity_accommodation_service.wsdl	0.5133765339851379
municipal-unit_professionparttimeposition_service.wsdl	0.5122904181480408
price_coffeewhiskeytimemeasure_service.wsdl	0.5068532228469849
food_taxfreepricephysical-quantity_Aldiservice.wsdl	0.5057898759841919
meat_taxfreepricephysical-quantity_Aldiservice.wsdl	0.5047399401664734
careorganization_diagnosticprocesstimeduration_service.wsdl	0.5024692416191101
