municipal-unit_professiontimeduration_service.wsdl	1.0
country_professiontimeduration_Service.wsdl	0.9371329545974731
geopolitical-entity_professiontimeduration_service.wsdl	0.8875153064727783
municipal-unit_professiontimemeasure_service.wsdl	0.7943128943443298
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.7896786332130432
municipal-unit_professionfulltimeposition_service.wsdl	0.7597094178199768
municipal-unit_occupationaltradetimeduration_service.wsdl	0.7522162795066833
municipal-unit_professionparttimeposition_service.wsdl	0.74652498960495
country_skilledoccupationtimeduration_JobService.wsdl	0.7338474988937378
country_skilledoccupationtimeduration_service.wsdl	0.7338474988937378
DJob_service.wsdl	0.7338474988937378
country_professiontimemeasure_service.wsdl	0.7260860204696655
country_professionfulltimeposition_service.wsdl	0.7145656943321228
geopolitical-entity_professiontimemeasure_service.wsdl	0.69789719581604
country_professionparttimeposition_service.wsdl	0.696223258972168
country_occupationaltradetimeduration_Service.wsdl	0.6938689351081848
citycountryduration__HotelReserveservice.wsdl	0.6910767555236816
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.6909962296485901
geopolitical-entity_professionfulltimeposition_service.wsdl	0.6808270812034607
organization_experimentingtimeduration_service.wsdl	0.6779783368110657
careorganization_diagnosticprocesstimeduration_service.wsdl	0.667826235294342
geopolitical-entity_professionparttimeposition_service.wsdl	0.6634736061096191
HDP2_service.wsdl	0.6630048155784607
hospital_diagnosticprocesstimeduration_service.wsdl	0.6630048155784607
geopolitical-entity_occupationaltradetimeduration_service.wsdl	0.6560410857200623
medicalclinic_diagnosticprocesstimeduration_service.wsdl	0.6402328610420227
country_profession_service.wsdl	0.6358683109283447
company_profession_service.wsdl	0.6315174102783203
government-organization_profession_service.wsdl	0.6270368695259094
municipal-unit_skilledoccupationtimemeasure_service.wsdl	0.6186229586601257
geographical-region_companyprofession_service.wsdl	0.6139351725578308
country_companyprofession_service.wsdl	0.6069671511650085
academic-degree_fundingduration_GermanGovservice.wsdl	0.5971206426620483
academic-degree_lendingduration_GermanGovservice.wsdl	0.5918093323707581
degree_fundingduration_GermanGovservice.wsdl	0.5875304341316223
geographical-region_organizationprofession_service.wsdl	0.5839102864265442
degree_lendingduration_GermanGovservice.wsdl	0.578956127166748
geographical-region_corporationprofession_service.wsdl	0.5787009596824646
geopolitical-entity_profession_service.wsdl	0.5785434246063232
municipal-unit_occupationaltradetimemeasure_service.wsdl	0.5745490193367004
country_organizationprofession_service.wsdl	0.5735868215560913
nationalgovernment_scholarshipquantityduration_service.wsdl	0.5731340646743774
country_skilledoccupationfulltimeposition_service.wsdl	0.5681561827659607
country_corporationprofession_service.wsdl	0.5665833353996277
geopolitical-entity_companyprofession_service.wsdl	0.5628854632377625
degree_scholarshipduration_GermanGovservice.wsdl	0.5609660148620605
academic-degree_scholarshipduration_GermanGovservice.wsdl	0.5595133304595947
country_skilledoccupationparttimeposition_JobService.wsdl	0.5582564473152161
country_skilledoccupationparttimeposition_service.wsdl	0.5582564473152161
country_skilledoccupationtimemeasure_service.wsdl	0.5567628145217896
_professiongeographical-region_USservice.wsdl	0.5553632974624634
profit-organization_profession_service.wsdl	0.5551652312278748
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.5499429702758789
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.544826865196228
country_occupationaltradefulltimeposition_service.wsdl	0.5400007367134094
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.5395618081092834
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.5395618081092834
durationcountrycity_hotel_service.wsdl	0.5382285118103027
country_occupationaltradeparttimeposition_service.wsdl	0.5338610410690308
geopolitical-entity_organizationprofession_service.wsdl	0.5329848527908325
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.5309484601020813
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.5293564796447754
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.5293564796447754
award_lendingduration_GermanGovservice.wsdl	0.5282467603683472
award_fundingduration_GermanGovservice.wsdl	0.5273597240447998
real-time_geocoding.wsdl	0.5252271294593811
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.5132449269294739
country_occupationaltradetimemeasure_Service.wsdl	0.5092833638191223
geopolitical-entity_corporationprofession_service.wsdl	0.5074191093444824
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.5058262944221497
durationgeopolitical-entitycity_accommodation_service.wsdl	0.5031264424324036
getSunsetSunriseTwilightTime.wsdl	0.5011036992073059
