municipal-unit_occupationaltradeparttimeposition_service.wsdl	1.0
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.9923485517501831
country_occupationaltradeparttimeposition_service.wsdl	0.9629546999931335
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.9388806223869324
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.9364393353462219
country_occupationaltradefulltimeposition_service.wsdl	0.8993217349052429
geopolitical-entity_occupationaltradetimemeasure_service.wsdl	0.8478350043296814
geopolitical-entity_occupationaltradetimeduration_service.wsdl	0.8290659189224243
geopolitical-entity_occupationaltrade_service.wsdl	0.8199889063835144
geopolitical-entity_organizationoccupationaltrade_service.wsdl	0.8040350675582886
geopolitical-entity_companyoccupationaltrade_service.wsdl	0.7938107848167419
municipal-unit_occupationaltradetimemeasure_service.wsdl	0.7866436243057251
country_occupationaltradetimemeasure_Service.wsdl	0.7854390144348145
geopolitical-entity_professionparttimeposition_service.wsdl	0.7830435633659363
geopolitical-entity_corporationoccupationaltrade_service.wsdl	0.7784256935119629
municipal-unit_occupationaltradetimeduration_service.wsdl	0.7776157259941101
geographical-region_organizationoccupationaltrade_service.wsdl	0.7742999196052551
country_occupationaltradetimeduration_Service.wsdl	0.7705323100090027
geographical-region_corporationoccupationaltrade_service.wsdl	0.7687466144561768
country_occupationaltrade_service.wsdl	0.7640137076377869
country_organizationoccupationaltrade_service.wsdl	0.7633947134017944
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.7592092752456665
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.7592092752456665
geographical-region_companyoccupationaltrade_service.wsdl	0.7555110454559326
country_corporationoccupationaltrade_service.wsdl	0.7546613216400146
country_companyoccupationaltrade_service.wsdl	0.7419701814651489
geopolitical-entity_professionfulltimeposition_service.wsdl	0.7395886778831482
municipal-unit_professionparttimeposition_service.wsdl	0.7374222874641418
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.7154951691627502
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.7154951691627502
country_skilledoccupationparttimeposition_JobService.wsdl	0.7072871327400208
country_skilledoccupationparttimeposition_service.wsdl	0.7072871327400208
country_professionparttimeposition_service.wsdl	0.7052799463272095
municipal-unit_professionfulltimeposition_service.wsdl	0.68826824426651
country_skilledoccupationfulltimeposition_service.wsdl	0.6587628126144409
country_professionfulltimeposition_service.wsdl	0.6576278805732727
geopolitical-entity_professiontimemeasure_service.wsdl	0.6384177207946777
geopolitical-entity_professiontimeduration_service.wsdl	0.6279602646827698
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.6237481236457825
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.6135196089744568
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.5880678296089172
geopolitical-entity_weatherseasontimeposition_service.wsdl	0.5798160433769226
geopolitical-entity_companyskilledoccupation_service.wsdl	0.5754247903823853
geopolitical-entity_skilledoccupationcompany_service.wsdl	0.5738596320152283
geopolitical-entity_corporationskilledoccupation_service.wsdl	0.5710316896438599
agent_movement.wsdl	0.56789630651474
geographical-region_organizationskilledoccupation_JobService.wsdl	0.5622327327728271
geographical-region_organizationskilledoccupation_service.wsdl	0.5622327327728271
municipal-unit_skilledoccupationtimemeasure_service.wsdl	0.5577587485313416
geopolitical-entity_organizationprofession_service.wsdl	0.556385338306427
geographical-region_corporationskilledoccupation_service.wsdl	0.5556045174598694
geopolitical-entity_profession_service.wsdl	0.5555667281150818
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.555117130279541
geopolitical-entity_skilledoccupation_service.wsdl	0.5536342263221741
geopolitical-entity_weatherseasonproposition_service.wsdl	0.5513878464698792
geopolitical-entity_companyprofession_service.wsdl	0.5484103560447693
municipal-unit_professiontimeduration_service.wsdl	0.544826865196228
geographical-region_companyskilledoccupation_service.wsdl	0.5440937280654907
geopolitical-entity_corporationprofession_service.wsdl	0.5436305999755859
country_skilledoccupationtimemeasure_service.wsdl	0.5435008406639099
municipal-unit_professiontimemeasure_service.wsdl	0.5429865121841431
country_organizationskilledoccupation_service.wsdl	0.5391719937324524
country_skilledoccupationtimeduration_JobService.wsdl	0.5375866293907166
country_skilledoccupationtimeduration_service.wsdl	0.5375866293907166
DJob_service.wsdl	0.5375866293907166
country_sportsposition_service.wsdl	0.5347943305969238
geographical-region_corporationprofession_service.wsdl	0.5334087610244751
country_corporationskilledoccupation_service.wsdl	0.5308157205581665
time-measuregeopolitical-entitycity_accommodation_service.wsdl	0.5295007824897766
time-measuregeopolitical-entitycity_hotel_service.wsdl	0.5290682315826416
geographical-region_organizationprofession_service.wsdl	0.5259937644004822
country_professiontimemeasure_service.wsdl	0.5214915871620178
country_professiontimeduration_Service.wsdl	0.5193967223167419
country_companyskilledoccupation_service.wsdl	0.5190368294715881
public-companycountry_skilledoccupation_service.wsdl	0.5147897601127625
_professiongeographical-region_USservice.wsdl	0.5137195587158203
geographical-region_companyprofession_service.wsdl	0.5090332627296448
geopolitical-entityrecorded-video_activityhotel_service.wsdl	0.5063396692276001
profit-organization_skilledoccupation_service.wsdl	0.5004656314849854
