nationalgovernment_scholarshipquantityduration_service.wsdl	1.0
nationalgovernment_scholarshipquantity_service.wsdl	0.8865001201629639
governmentdegree_scholarshipquantity_service.wsdl	0.8384782671928406
degree_scholarshipduration_GermanGovservice.wsdl	0.819064736366272
award_scholarshipduration_GermanGovservice.wsdl	0.816094696521759
award_scholarshipduration_SwissGovservice.wsdl	0.816094696521759
academic-degree_scholarshipduration_GermanGovservice.wsdl	0.811625063419342
nationalgovernment_physical-quantityscholarshiplandarea_service.wsdl	0.7451409697532654
nationalgovernment_scholarship_service.wsdl	0.6977868676185608
academic-degree_fundingduration_GermanGovservice.wsdl	0.694258987903595
degreenationalgovernment_scholarship_service.wsdl	0.6916407942771912
award_fundingduration_GermanGovservice.wsdl	0.6803568005561829
degree_fundingduration_GermanGovservice.wsdl	0.6680397987365723
government_scholarship_service.wsdl	0.665999174118042
degreegovernment_scholarship_service.wsdl	0.656875491142273
governmentdegree_scholarship_service.wsdl	0.656875491142273
governmentdegree_scholarship_TheBestservice.wsdl	0.656875491142273
degreegovernmentorganization_scholarship_service.wsdl	0.6547256708145142
governmentorganization_scholarship_service.wsdl	0.6534075140953064
academic-degreegovernment_scholarship_service.wsdl	0.6510125994682312
governmentaward_scholarship_service.wsdl	0.6433826684951782
government_scholarshiporganization_service.wsdl	0.6108759045600891
academic-degree_scholarship_GermanGovservice.wsdl	0.6026373505592346
degree_scholarship_GermanGovservice.wsdl	0.5952990651130676
academic-degree_lendingduration_GermanGovservice.wsdl	0.589299738407135
country_professiontimeduration_Service.wsdl	0.5829408168792725
country_skilledoccupationtimeduration_JobService.wsdl	0.5805156826972961
country_skilledoccupationtimeduration_service.wsdl	0.5805156826972961
DJob_service.wsdl	0.5805156826972961
award_scholarship_GermanGovservice.wsdl	0.5791318416595459
country_occupationaltradetimeduration_Service.wsdl	0.5754241347312927
municipal-unit_professiontimeduration_service.wsdl	0.5731340646743774
geopolitical-entity_professiontimeduration_service.wsdl	0.5704858899116516
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.5693411231040955
award_lendingduration_GermanGovservice.wsdl	0.5689144730567932
municipal-unit_occupationaltradetimeduration_service.wsdl	0.563707172870636
organization_experimentingtimeduration_service.wsdl	0.5621520280838013
citycountryduration__HotelReserveservice.wsdl	0.5613048672676086
food_pricephysical-quantity_Aldiservice.wsdl	0.557671308517456
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.5575101971626282
geopolitical-entity_occupationaltradetimeduration_service.wsdl	0.5542604327201843
degree_lendingduration_GermanGovservice.wsdl	0.5502006411552429
food_pricequantity_Aldiservice.wsdl	0.5500829219818115
food_maxpricephysical-quantity_Aldiservice.wsdl	0.5489831566810608
food_maxpricequantity_Aldiservice.wsdl	0.54393070936203
food_maxpricequantity_service.wsdl	0.54393070936203
meat_pricephysical-quantity_Aldiservice.wsdl	0.5417245030403137
beverage_pricephysical-quantity_Aldiservice.wsdl	0.5396683812141418
meat_maxpricephysical-quantity_service.wsdl	0.5347333550453186
beverage_maxpricephysical-quantity_service.wsdl	0.5310956239700317
meat_pricequantity_Aldiservice.wsdl	0.5309832096099854
beverage_pricequantity_Aldiservice.wsdl	0.5287960767745972
meat_maxpricequantity_service.wsdl	0.5271748304367065
beverage_maxpricequantity_service.wsdl	0.5228776931762695
food_taxfreepricephysical-quantity_Aldiservice.wsdl	0.5124649405479431
careorganization_diagnosticprocesstimeduration_service.wsdl	0.5108007788658142
academic-degreegovernmentorganization_funding_service.wsdl	0.5100753903388977
food_taxedpricephysical-quantity_Aldiservice.wsdl	0.5076568722724915
meat_taxfreepricephysical-quantity_Aldiservice.wsdl	0.5022113919258118
