organization_experimentingtimeduration_service.wsdl	1.0
country_professiontimeduration_Service.wsdl	0.6906731128692627
careorganization_diagnosticprocesstimeduration_service.wsdl	0.6849260330200195
organization_experimenting_service.wsdl	0.6830753684043884
municipal-unit_professiontimeduration_service.wsdl	0.6779783368110657
geopolitical-entity_professiontimeduration_service.wsdl	0.6686466932296753
careorganization_experimenting_service.wsdl	0.6680430769920349
country_skilledoccupationtimeduration_JobService.wsdl	0.655378520488739
country_skilledoccupationtimeduration_service.wsdl	0.655378520488739
DJob_service.wsdl	0.655378520488739
HDP2_service.wsdl	0.6488073468208313
hospital_diagnosticprocesstimeduration_service.wsdl	0.6488073468208313
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.6426337361335754
hospital_experimenting_service.wsdl	0.6273592710494995
medicalclinic_diagnosticprocesstimeduration_service.wsdl	0.6258455514907837
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.625148355960846
country_occupationaltradetimeduration_Service.wsdl	0.605534017086029
degree_fundingduration_GermanGovservice.wsdl	0.6019075512886047
municipal-unit_occupationaltradetimeduration_service.wsdl	0.5941445827484131
academic-degree_fundingduration_GermanGovservice.wsdl	0.5906271934509277
geopolitical-entity_occupationaltradetimeduration_service.wsdl	0.5813056230545044
medicalclinic_experimenting_service.wsdl	0.5702493190765381
citycountryduration__HotelReserveservice.wsdl	0.5672457814216614
award_fundingduration_GermanGovservice.wsdl	0.5634261965751648
nationalgovernment_scholarshipquantityduration_service.wsdl	0.5621520280838013
degree_lendingduration_GermanGovservice.wsdl	0.5469374656677246
academic-degree_lendingduration_GermanGovservice.wsdl	0.5435399413108826
degree_scholarshipduration_GermanGovservice.wsdl	0.5406615138053894
academic-degree_scholarshipduration_GermanGovservice.wsdl	0.5234727263450623
award_lendingduration_GermanGovservice.wsdl	0.5164633989334106
careorganization_diagnosticprocesstimeinterval_service.wsdl	0.5035511255264282
