organization_lecturer-in-academia_service.wsdl	1.0
educational-organization_lecturer-in-academia_service.wsdl	0.9803270697593689
_lecturer-in-academiaMunchenUniversity_service.wsdl	0.9787741899490356
_lecturer-in-academiaSaarlandUniversity_service.wsdl	0.9787741899490356
_lecturer-in-academiaZambiaUniversity_service.wsdl	0.9787741899490356
learning-centred-organization_lecturer-in-academia_service.wsdl	0.974978506565094
university_lecturer-in-academiaCurrentSemmester_service.wsdl	0.9681432247161865
university_lecturer-in-academia_Recommendservice.wsdl	0.9681432247161865
university_lecturer-in-academia_service.wsdl	0.9681432247161865
higher-educational-organization_lecturer-in-academia_MostUsedservice.wsdl	0.9570785760879517
higher-educational-organization_lecturer-in-academia_service.wsdl	0.9570785760879517
university_senior-lecturer-in-academia_service.wsdl	0.9197773337364197
university_professor-in-academia_service.wsdl	0.8913748860359192
higher-educational-organization_professor-in-academia_Pioneerservice.wsdl	0.8888365030288696
higher-educational-organization_professor-in-academia_service.wsdl	0.8888365030288696
university_research-fellow-in-academia_service.wsdl	0.7239488363265991
higher-educational-organization_senior-research-fellow-in-academia_Firstservice.wsdl	0.6922141909599304
higher-educational-organization_senior-research-fellow-in-academia_service.wsdl	0.6922141909599304
professor-in-academia_address_service.wsdl	0.6891431212425232
researcher-in-academia_abstract-information_service.wsdl	0.6417841911315918
researcher-in-academia_address_service.wsdl	0.6271031498908997
researcher-in-academia_address_TREEservice.wsdl	0.6271031498908997
researcher-in-academia_address_ZOOservice.wsdl	0.6271031498908997
university_researcher_service.wsdl	0.6091911792755127
research-assistant-in-academia_address_service.wsdl	0.6089133620262146
research-fellow-in-academia_publication-reference_service.wsdl	0.5430032014846802
government-organization_profession_service.wsdl	0.5363106727600098
sfnovel_authorauthor_BookOntoservice.wsdl	0.513332188129425
sciencefictionnovel_author_MyOntoservice.wsdl	0.5030879378318787
