public-companycountry_skilledoccupation_service.wsdl	1.0
companycountry_skilledoccupation_service.wsdl	0.9767972230911255
country_companyskilledoccupation_service.wsdl	0.9573749303817749
company_skilledoccupation_service.wsdl	0.9504983425140381
country_skilledoccupation_jobsservice.wsdl	0.947438657283783
country_skilledoccupation_service.wsdl	0.947438657283783
citycountry_skilledoccupation_service.wsdl	0.9442431926727295
government-organization_skilledoccupation_service.wsdl	0.9306210279464722
city_skilledoccupation_service.wsdl	0.9233338832855225
country_corporationskilledoccupation_service.wsdl	0.9210894703865051
_skilledoccupation_BMWservice.wsdl	0.9122849106788635
geographical-region_companyskilledoccupation_service.wsdl	0.9096943736076355
geopolitical-entity_companyskilledoccupation_service.wsdl	0.9089365601539612
country_organizationskilledoccupation_service.wsdl	0.8892136812210083
geographical-region_corporationskilledoccupation_service.wsdl	0.8831768035888672
profit-organization_skilledoccupation_service.wsdl	0.8830412030220032
geopolitical-entity_skilledoccupationcompany_service.wsdl	0.8822073340415955
geopolitical-entity_skilledoccupation_service.wsdl	0.8621193766593933
geopolitical-entity_corporationskilledoccupation_service.wsdl	0.8615138530731201
geographical-region_organizationskilledoccupation_JobService.wsdl	0.8518790602684021
geographical-region_organizationskilledoccupation_service.wsdl	0.8518790602684021
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.8462433815002441
country_skilledoccupationtimemeasure_service.wsdl	0.8344404101371765
country_skilledoccupationparttimeposition_JobService.wsdl	0.8139212727546692
country_skilledoccupationparttimeposition_service.wsdl	0.8139212727546692
municipal-unit_skilledoccupationtimemeasure_service.wsdl	0.8098034858703613
country_skilledoccupationfulltimeposition_service.wsdl	0.8088734149932861
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.8052371740341187
country_skilledoccupationtimeduration_JobService.wsdl	0.7898498177528381
country_skilledoccupationtimeduration_service.wsdl	0.7898498177528381
DJob_service.wsdl	0.7898498177528381
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.7813302874565125
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.7813302874565125
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.7783828377723694
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.7783828377723694
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.7732764482498169
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.7634145021438599
geographical-region_corporationprofession_service.wsdl	0.5751880407333374
geographical-region_companyprofession_service.wsdl	0.5734266042709351
country_corporationprofession_service.wsdl	0.5648375749588013
country_companyprofession_service.wsdl	0.5643002390861511
geopolitical-entity_companyprofession_service.wsdl	0.5568618774414062
government-organization_profession_service.wsdl	0.5515432357788086
geopolitical-entity_professiontimemeasure_service.wsdl	0.539668083190918
geopolitical-entity_professionfulltimeposition_service.wsdl	0.5368139743804932
geopolitical-entity_corporationprofession_service.wsdl	0.5338823199272156
municipal-unit_professionfulltimeposition_service.wsdl	0.5323553681373596
country_professionfulltimeposition_service.wsdl	0.5310171842575073
geopolitical-entity_professionparttimeposition_service.wsdl	0.5305619835853577
municipal-unit_professionparttimeposition_service.wsdl	0.5289995670318604
country_professionparttimeposition_service.wsdl	0.5245136022567749
country_professiontimemeasure_service.wsdl	0.5235850811004639
country_profession_service.wsdl	0.5233643054962158
geographical-region_organizationprofession_service.wsdl	0.5215767025947571
geopolitical-entity_profession_service.wsdl	0.5215006470680237
company_profession_service.wsdl	0.5161010026931763
municipal-unit_professiontimemeasure_service.wsdl	0.5159782767295837
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.5147897601127625
country_occupationaltradeparttimeposition_service.wsdl	0.5102561116218567
country_corporationoccupationaltrade_service.wsdl	0.5101132392883301
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.5099745392799377
country_organizationprofession_service.wsdl	0.5072452425956726
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.5060155987739563
country_occupationaltradefulltimeposition_service.wsdl	0.5055991411209106
geopolitical-entity_professiontimeduration_service.wsdl	0.5040032863616943
geographical-region_corporationoccupationaltrade_service.wsdl	0.503412663936615
geopolitical-entity_organizationprofession_service.wsdl	0.5033793449401855
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.5031104683876038
country_companyoccupationaltrade_service.wsdl	0.5027995109558105
_professiongeographical-region_USservice.wsdl	0.5007129311561584
