time-measuregeopolitical-entitycity_accommodation_service.wsdl	1.0
durationgeopolitical-entitycity_accommodation_service.wsdl	0.9354243278503418
geopolitical-entity_accommodation_service.wsdl	0.9135313034057617
citycountry_accommodation_service.wsdl	0.8257662057876587
city_accommodation_service.wsdl	0.8150882720947266
time-measuregeopolitical-entitycity_hotel_service.wsdl	0.8103610873222351
durationgeopolitical-entitycity_hotel_service.wsdl	0.7610373497009277
geographical-region_accomodation_service.wsdl	0.7350767254829407
geopolitical-entity_hotel_service.wsdl	0.6969392895698547
time-measuregeopolitical-entitycity_bedandbreakfast_service.wsdl	0.6535930037498474
time-measurecountrycity_hotel_service.wsdl	0.6524290442466736
geopolitical-entityrecorded-video_activityhotel_service.wsdl	0.6423213481903076
geopolitical-entity_skilledoccupationtimemeasure_service.wsdl	0.6334286332130432
geopolitical-entity_professiontimemeasure_service.wsdl	0.632022500038147
geopolitical-entity_luxuryhotel_service.wsdl	0.6216896176338196
geopolitical-entity_occupationaltradetimemeasure_service.wsdl	0.6105920076370239
AddLinks__service.wsdl	0.6095839142799377
durationgeopolitical-entitycity_bedandbreakfast_service.wsdl	0.6055234670639038
durationcountrycity_hotel_service.wsdl	0.6017518043518066
geopolitical-entity_skilledoccupationtimeduration_service.wsdl	0.5904252529144287
geographical-region_hotel_service.wsdl	0.5898898243904114
geographical-region_hotel_XYZService.wsdl	0.5898898243904114
geopolitical-entity_professiontimeduration_service.wsdl	0.5824306011199951
countrycapital-city_hotel_service.wsdl	0.5701834559440613
geopolitical-entity_occupationaltradetimeduration_service.wsdl	0.5680438280105591
citycountry_destinationhotel_service.wsdl	0.5659391283988953
personcountrycity_sportshotel_service.wsdl	0.5612965226173401
citycountry_hotel_service.wsdl	0.5576140880584717
countrycity_hotel_service.wsdl	0.5576140880584717
geopolitical-entity_skilledoccupationparttimeposition_service.wsdl	0.5540990233421326
municipal-unit_skilledoccupationparttimeposition_service.wsdl	0.5540990233421326
geopolitical-entity_skilledoccupationfulltimeposition_service.wsdl	0.5474627614021301
municipal-unit_skilledoccupationfulltimeposition_service.wsdl	0.5474627614021301
geopolitical-entity_occupationaltradeparttimeposition_service.wsdl	0.5467280149459839
municipal-unit_skilledoccupationtimemeasure_service.wsdl	0.5425773859024048
real-time_geocoding.wsdl	0.5410330891609192
countrycity_sportshotel_service.wsdl	0.5406621694564819
geographical-region_luxuryhotel_service.wsdl	0.5382741093635559
geopolitical-entity_occupationaltradefulltimeposition_service.wsdl	0.5360240936279297
getDistanceBetweenCitiesWorldwide.wsdl	0.5353913903236389
citycountryduration__HotelReserveservice.wsdl	0.5339316129684448
towncountry_hotel_service.wsdl	0.5299476981163025
municipal-unit_occupationaltradeparttimeposition_service.wsdl	0.5295007824897766
geopolitical-entity_professionparttimeposition_service.wsdl	0.5265023112297058
geopolitical-entity_professionfulltimeposition_service.wsdl	0.5248977541923523
geopolitical-entity_skilledoccupation_service.wsdl	0.5235614776611328
countryvillage_hotel_service.wsdl	0.5229039788246155
getATMLocationsInCity.wsdl	0.522735059261322
geopolitical-entity_organizationskilledoccupation_service.wsdl	0.521978497505188
geopolitical-entity_corporationskilledoccupation_service.wsdl	0.5173375010490417
municipal-unit_occupationaltradefulltimeposition_service.wsdl	0.5171328783035278
geopolitical-entity_skilledoccupationcompany_service.wsdl	0.5166037678718567
countrycity_luxuryhotel_Gelservice.wsdl	0.5143264532089233
countrycity_luxuryhotel_service.wsdl	0.5143264532089233
postal-addresscity_hotel_service.wsdl	0.5142198204994202
municipal-unit_occupationaltradetimemeasure_service.wsdl	0.5133765339851379
geopolitical-entity_internalchange_service.wsdl	0.51244056224823
country_skilledoccupationtimemeasure_service.wsdl	0.5113243460655212
city_hotel_Germanservice.wsdl	0.5099737048149109
city_hotel_Saarlandservice.wsdl	0.5099737048149109
city_hotel_service.wsdl	0.5099737048149109
getLocationOfCityState.wsdl	0.5091077089309692
geopolitical-entity_bedandbreakfast_service.wsdl	0.5069366097450256
municipal-unit_skilledoccupationtimeduration_service.wsdl	0.5062698721885681
municipal-unit_professiontimemeasure_service.wsdl	0.5059476494789124
geopolitical-entity_companyskilledoccupation_service.wsdl	0.5032463669776917
geopolitical-entity_weatherprocess_service.wsdl	0.5014747381210327
country_hotel_service.wsdl	0.5003572106361389
