university_senior-lecturer-in-academia_service.wsdl	1.0
university_lecturer-in-academiaCurrentSemmester_service.wsdl	0.9507922530174255
university_lecturer-in-academia_Recommendservice.wsdl	0.9507922530174255
university_lecturer-in-academia_service.wsdl	0.9507922530174255
_lecturer-in-academiaMunchenUniversity_service.wsdl	0.9343188405036926
_lecturer-in-academiaSaarlandUniversity_service.wsdl	0.9343188405036926
_lecturer-in-academiaZambiaUniversity_service.wsdl	0.9343188405036926
organization_lecturer-in-academia_service.wsdl	0.9197773337364197
educational-organization_lecturer-in-academia_service.wsdl	0.8973326086997986
learning-centred-organization_lecturer-in-academia_service.wsdl	0.8886764645576477
higher-educational-organization_lecturer-in-academia_MostUsedservice.wsdl	0.8839271664619446
higher-educational-organization_lecturer-in-academia_service.wsdl	0.8839271664619446
university_professor-in-academia_service.wsdl	0.8757753968238831
higher-educational-organization_professor-in-academia_Pioneerservice.wsdl	0.8178987503051758
higher-educational-organization_professor-in-academia_service.wsdl	0.8178987503051758
higher-educational-organization_senior-research-fellow-in-academia_Firstservice.wsdl	0.7435876727104187
higher-educational-organization_senior-research-fellow-in-academia_service.wsdl	0.7435876727104187
university_research-fellow-in-academia_service.wsdl	0.7376909255981445
professor-in-academia_address_service.wsdl	0.6447790861129761
university_researcher_service.wsdl	0.6232686042785645
research-assistant-in-academia_address_service.wsdl	0.579477846622467
researcher-in-academia_address_service.wsdl	0.5774113535881042
researcher-in-academia_address_TREEservice.wsdl	0.5774113535881042
researcher-in-academia_address_ZOOservice.wsdl	0.5774113535881042
researcher-in-academia_abstract-information_service.wsdl	0.5682756304740906
academic-degreegovernment_scholarship_service.wsdl	0.5279887318611145
university_academic-support-staff_service.wsdl	0.5024712681770325
