4wheeledcaryear_pricereport_service.wsdl	car_pricereport_service.wsdl	fastcar_pricereport_service.wsdl	cheapcar_pricereport_service.wsdl	car_taxedpricereport_service.wsdl	fastcar_taxedpricereport_service.wsdl	cheapcar_taxedpricereport_service.wsdl	4wheeledcar_yearprice_service.wsdl	3wheeledcaryear_price_service.wsdl	4wheeledcaryear_price_service.wsdl	3wheeledcaryear_recommendedprice_service.wsdl	car_report_service.wsdl	_aps-slrpricereport_Musuemservice.wsdl	SPD-Grune_service.wsdl	_droughtreport_service.wsdl	car_yearprice_service.wsdl	fastcar_yearprice_service.wsdl	bicyclecar_priceyear_service.wsdl	cheapcar_yearprice_service.wsdl	expensivecar_yearprice_service.wsdl	