_investigating_Saarservice.wsdl	hospital_investigating_service.wsdl	careorganization_investigating_service.wsdl	medicalclinic_investigating_MedService.wsdl	medicalclinic_investigating_service.wsdl	hospital_investigatingaddress_service.wsdl	hospital_postal-addressinvestigating_service.wsdl	