novel_person_Reserverservice.wsdl	novel_person_Writerservice.wsdl	_person_MyShopservice.wsdl	book_person_Publisherservice.wsdl	novelperson__Reservationservice.wsdl	bookperson__service.wsdl	monographperson__service.wsdl	objectperson__service.wsdl	publicationperson__service.wsdl	book_readerreviewperson_service.wsdl	novelperson_price_service.wsdl	person_address_service.wsdl	printedmaterialperson__service.wsdl	bookpersoncreditaccount__Beaservice.wsdl	bookpersoncreditaccount__service.wsdl	bookpersonOptional_price_service.wsdl	bookperson_price_service.wsdl	personbookliabilityaccount__service.wsdl	1personbicyclecar_price_Kohlservice.wsdl	1personbicyclecar_price_service.wsdl	