_weatherprocess_Germanservice.wsdl	country_weatherprocess_service.wsdl	geographical-region_weatherprocess_GRWservice.wsdl	geographical-region_weatherprocess_service.wsdl	geopolitical-entity_weatherprocess_service.wsdl	municipal-unit_weatherprocess_service.wsdl	_weatherfront_BombayIndiaservice.wsdl	_weatherfront_Britishservice.wsdl	_weatherfront_Germanyservice.wsdl	city_weatherfront_service.wsdl	city_weathersystem_service.wsdl	country_weatherfront_service.wsdl	country_weathersystem_service.wsdl	geographical-region_weatherfront_service.wsdl	geographical-region_weatherfront_WService.wsdl	geographical-region_weathersystem_service.wsdl	geopolitical-entity_weatherfront_service.wsdl	geopolitical-entity_weathersystem_service.wsdl	municipal-unit_weatherfront_service.wsdl	municipal-unit_weathersystem_service.wsdl	