academic-degree_fundingduration_GermanGovservice.wsdl	degree_fundingduration_GermanGovservice.wsdl	academic-degree_funding_GermanGovservice.wsdl	award_fundingduration_GermanGovservice.wsdl	academic-degreegovernment_funding_service.wsdl	academic-degreegovernmentorganization_funding_service.wsdl	academic-degree_lendingduration_GermanGovservice.wsdl	academic-degree_scholarshipduration_GermanGovservice.wsdl	degree_funding_GermanGovservice.wsdl	degreegovernment_funding_service.wsdl	degree_lendingduration_GermanGovservice.wsdl	degree_scholarshipduration_GermanGovservice.wsdl	award_funding_GermanGovservice.wsdl	government_funding_ABombservice.wsdl	government_funding_BallMissileservice.wsdl	government_funding_ForPhDservice.wsdl	government_funding_Missileservice.wsdl	missile_funding_Asianservice.wsdl	missile_funding_Indiaservice.wsdl	missile_funding_NKoreaservice.wsdl	