AcceptCostAndHealingPlan_service.wsdl	AuthorizePhysician_service.wsdl	CheckCostAndHealingPlan_service.wsdl	SetUpCostAndHealingPlan_service.wsdl	hospital_diagnosticprocesscost_service.wsdl	organization_diagnosticprocesscost_service.wsdl	InformHospital_service.wsdl	UpdatePatientMedicalRecords_service.wsdl	PatientTransport_service.wsdl	HospitalPhysician_service.wsdl	