agent_price_MianMarktservice.wsdl	agent_movement.wsdl	generic-agentsports_destination_service.wsdl	generic-agentsports_destination_SportsService.wsdl	legal-agentsurfing_destination_service.wsdl	sportslegal-agent_destination_service.wsdl	surfinggeneric-agent_city_service.wsdl	surfinggeneric-agent_destination_service.wsdl	KodakDigCamera_price_service.wsdl	novel_price_service.wsdl	_3WheeledAudiCarprice_service.wsdl	_3WheeledOpelCarPrice_service.wsdl	_price_CannonCameraservice.wsdl	_price_Fishservice.wsdl	_RedFerrariprice_service.wsdl	_Toyotaprice_service.wsdl	book_taxedpriceprice_service.wsdl	car_taxedpriceprice_service.wsdl	apple_price_service.wsdl	author_novelprice_service.wsdl	