agent_movement.wsdl	flip_down_slider.wsdl	fall_down_pill.wsdl	flip_slider.wsdl	agent_price_MianMarktservice.wsdl	generic-agentsports_destination_service.wsdl	generic-agentsports_destination_SportsService.wsdl	legal-agentsurfing_destination_service.wsdl	sportslegal-agent_destination_service.wsdl	surfinggeneric-agent_city_service.wsdl	surfinggeneric-agent_destination_service.wsdl	country_sportsposition_service.wsdl	_propositionmotion_service.wsdl	country_professionfulltimeposition_service.wsdl	country_professionparttimeposition_service.wsdl	geopolitical-entity_professionfulltimeposition_service.wsdl	geopolitical-entity_professionparttimeposition_service.wsdl	municipal-unit_professionfulltimeposition_service.wsdl	municipal-unit_professionparttimeposition_service.wsdl	country_occupationaltradefulltimeposition_service.wsdl	