amount-of-moneyexpensivecar_price_service.wsdl	amount-of-moneyexpensivecar_recommendedprice_service.wsdl	amount-of-moneycar_price_service.wsdl	amount-of-money3wheeledcar_price_service.wsdl	amount-of-money4wheeledcar_price_service.wsdl	amount-of-moneycheapcar_price_service.wsdl	amount-of-moneycar_pricecompany_service.wsdl	amount-of-money3wheeledcar_recommendedprice_service.wsdl	amount-of-money4wheeledcar_recommendedprice_service.wsdl	amount-of-moneycheapcar_recommendedprice_service.wsdl	expensivecar_price_service.wsdl	expensivecar_pricecolor_service.wsdl	expensivecar_yearprice_service.wsdl	expensivecar_recommendedpricecolor_service.wsdl	expensivecar_technology_service.wsdl	car_price_service.wsdl	lenthu_rentcar_service.wsdl	3wheeledcar_price_service.wsdl	4wheeledcar_price_service.wsdl	bicyclecar_price_service.wsdl	