author_monographrecommendedprice_service.wsdl	monograph_recommendedpriceineuro_service.wsdl	monographpersoncreditcardaccount_recommendedprice_service.wsdl	author_monographprice_service.wsdl	author_monographmaxprice_service.wsdl	author_monographtaxedprice_service.wsdl	author_monographtaxfreeprice_service.wsdl	monograph_author_service.wsdl	monograph_price_service.wsdl	novel_authorrecommendedprice_service.wsdl	author_novelrecommendedprice_service.wsdl	romanticnovel_authorrecommendedprice_service.wsdl	short-story_authorrecommendedprice_service.wsdl	science-fiction-novel_authorrecommendedprice_service.wsdl	sciencefictionbook_authorrecommendedprice_service.wsdl	author_bookrecommendedprice_service.wsdl	author_publicationrecommendedprice_service.wsdl	author_sciencefictionbookrecommendedprice_service.wsdl	monographperson__service.wsdl	monograph_publisher_service.wsdl	