AuthorizePhysician_service.wsdl	AcceptCostAndHealingPlan_service.wsdl	SetUpCostAndHealingPlan_service.wsdl	CheckCostAndHealingPlan_service.wsdl	ContactEMA_services.wsdl	HospitalPhysician_service.wsdl	UpdatePatientMedicalRecords_service.wsdl	SeePatientMedicalRecords_service.wsdl	hospital_diagnosticprocesscost_service.wsdl	organization_diagnosticprocesscost_service.wsdl	GetMedicalTransportAccount_service.wsdl	InformHospital_service.wsdl	getSunsetSunriseTimeOfLocation.wsdl	HealthInsurance_service.wsdl	GetMedicalFlightAccount_service.wsdl	GetNonMedicalTransportAccount_service.wsdl	GetNonMedicalFlightAccount_service.wsdl	NonMedicalFlightCompany_service.wsdl	ProvideNonMedicalTransportInformation_service.wsdl	medicalclinic_diagnosticprocesstimeduration_service.wsdl	