autobicycle_recommendedprice_service.wsdl	auto2personbicycle_recommendedprice_service.wsdl	autocycle_recommendedprice_service.wsdl	auto_recommendedpricecolor_service.wsdl	carbicycle_recommendedprice_service.wsdl	autobicycle_price_service.wsdl	bicycleauto_price_service.wsdl	auto1personbicycle_price_service.wsdl	auto2personbicycle_price_service.wsdl	autobicycle_maxprice_service.wsdl	autobicycle_taxedprice_service.wsdl	auto2personbicycle_maxprice_service.wsdl	auto2personbicycle_taxedprice_service.wsdl	author_novelrecommendedprice_service.wsdl	book_recommendedprice_RegisteredUserservice.wsdl	book_recommendedprice_service.wsdl	butter_recommendedprice_service.wsdl	car_recommendedprice_service.wsdl	coffee_recommendedprice_service.wsdl	fastcar_recommendedprice_service.wsdl	