award_funding_GermanGovservice.wsdl	awardgovernment_funding_service.wsdl	award_fundingduration_GermanGovservice.wsdl	degree_funding_GermanGovservice.wsdl	government_funding_ABombservice.wsdl	government_funding_BallMissileservice.wsdl	government_funding_ForPhDservice.wsdl	government_funding_Missileservice.wsdl	missile_funding_Asianservice.wsdl	missile_funding_Indiaservice.wsdl	missile_funding_NKoreaservice.wsdl	missile_funding_Pakservice.wsdl	academic-degree_funding_GermanGovservice.wsdl	degreegovernment_funding_service.wsdl	governmentmissile_funding_Reliableservice.wsdl	governmentmissile_funding_service.wsdl	governmentweapon_funding_service.wsdl	projectilegovernment_funding_service.wsdl	weaponmissile_funding_Iraqservice.wsdl	governmentmissileweapon_fundingfunding_service.wsdl	