Ben_service.wsdl	preparedfood_SpainishTax_service.wsdl	SPD-Grune_service.wsdl	car_recommendedpriceineuro_service.wsdl	monograph_recommendedpriceineuro_service.wsdl	Renaultyear_recommendedpriceineuro_service.wsdl	mediaplayer_recommendedpriceineuro_service.wsdl	caryear_recommendedpriceineuro_service.wsdl	cyclecar_recommendedpriceineuro_service.wsdl	breadorbiscuit_recPricetaxedpriceineuro_service.wsdl	CCP_service.wsdl	SFNovelReview_service.wsdl	recommendedpriceineuro_coffeewhiskey_service.wsdl	preparedfood_recommendedprice_service.wsdl	MAK_service.wsdl	ZAD_service.wsdl	preparedfood_GSprice_service.wsdl	dvdplayermp3player_RecpriceEuro_service.wsdl	food_recommendedprice_service.wsdl	grocerystore_preparedfoodprice_service.wsdl	