book_readerreviewperson_service.wsdl	book_readerreview_service.wsdl	book_pricereviewbook_service.wsdl	book_reviewprice_service.wsdl	reader-in-academia_address_service.wsdl	novel_userreviewauthor_service.wsdl	ScienceFNovelReview_service.wsdl	SFNovelReview_service.wsdl	book_person_Publisherservice.wsdl	bookperson__service.wsdl	bookpersoncreditaccount__Beaservice.wsdl	bookpersoncreditaccount__service.wsdl	bookpersonOptional_price_service.wsdl	bookperson_price_service.wsdl	personbookliabilityaccount__service.wsdl	bookpersoncreditcardaccount__BShopservice.wsdl	bookpersoncreditcardaccount__service.wsdl	bookpersoncreditcardaccount_price_service.wsdl	bookpersoncreditcardaccount_recommendedprice_service.wsdl	bookpersoncreditcardaccount_taxedfreeprice_service.wsdl	