bookpersoncreditcardaccount_recommendedprice_service.wsdl	monographpersoncreditcardaccount_recommendedprice_service.wsdl	bookpersoncreditcardaccount_price_service.wsdl	bookpersoncreditcardaccount_taxedfreeprice_service.wsdl	bookpersoncreditcardaccount__BShopservice.wsdl	bookpersoncreditcardaccount__service.wsdl	printedmaterialpersoncreditcardaccount_price_service.wsdl	personmonographcreditcardaccount__service.wsdl	printedmaterialpersoncreditcardaccount__service.wsdl	bookusercreditcardaccount__service.wsdl	bookpersoncreditaccount__Beaservice.wsdl	bookpersoncreditaccount__service.wsdl	objectpersoncreditaccount_price_service.wsdl	GetMedicalFlightAccount_service.wsdl	GetNonMedicalTransportAccount_service.wsdl	GetNonMedicalFlightAccount_service.wsdl	GetMedicalTransportAccount_service.wsdl	auto2personbicycle_recommendedprice_service.wsdl	book_recommendedprice_RegisteredUserservice.wsdl	book_recommendedprice_service.wsdl	