BookMedicalFlight_service.wsdl	BookNonMedicalFlight_service.wsdl	NonMedicalFlightCompany_service.wsdl	ProvideMedicalFlightInformation_services.wsdl	BookMedicalTransport_service.wsdl	BookNonMedicalTransport_service.wsdl	GetNonMedicalFlightAccount_service.wsdl	GetMedicalFlightAccount_service.wsdl	SelectFlight_service.wsdl	SeePatientMedicalRecords_service.wsdl	GetNonMedicalTransportAccount_service.wsdl	GetMedicalTransportAccount_service.wsdl	HospitalPhysician_service.wsdl	_medicaldoctor_UNOservice.wsdl	bookpersoncreditaccount__Beaservice.wsdl	bookpersoncreditaccount__service.wsdl	personbookliabilityaccount__service.wsdl	_book_Oracleservice.wsdl	book_authorbook-type_service.wsdl	EBookOrder1.wsdl	