book_recommendedpriceindollar_service.wsdl	Tizonbook_recommendedpriceindollar_service.wsdl	car_recommendedpriceindollar_service.wsdl	MAK_service.wsdl	ZAD_service.wsdl	science-fiction-noveluser_recommendedpriceindollar_service.wsdl	SRcamera_service.wsdl	recommendedpriceindollar_whiskeycoffee_service.wsdl	mp3playerdvdplayer_Recpriceshipping_USservice.wsdl	EntranceFeeindollar_service.wsdl	preparedfood_USTax_service.wsdl	preparedfood_taxedpriceindollarprice_service.wsdl	book_recommendedprice_RegisteredUserservice.wsdl	book_recommendedprice_service.wsdl	author_bookrecommendedprice_service.wsdl	author_sciencefictionbookrecommendedprice_service.wsdl	bookpersoncreditcardaccount_recommendedprice_service.wsdl	sciencefictionbook_authorrecommendedprice_service.wsdl	author_novelrecommendedprice_service.wsdl	butter_recommendedprice_service.wsdl	