bookpersoncreditcardaccount_taxedfreeprice_service.wsdl	bookpersoncreditcardaccount_price_service.wsdl	author_booktaxfreeprice_service.wsdl	bookpersoncreditcardaccount_recommendedprice_service.wsdl	author_sciencefictionbooktaxfreeprice_service.wsdl	bookpersoncreditcardaccount__BShopservice.wsdl	bookpersoncreditcardaccount__service.wsdl	printedmaterialpersoncreditcardaccount_price_service.wsdl	author_noveltaxfreeprice_service.wsdl	monographpersoncreditcardaccount_recommendedprice_service.wsdl	preparedfood_taxfreeprice_service.wsdl	author_monographtaxfreeprice_service.wsdl	author_publicationtaxfreeprice_service.wsdl	beverage_taxfreepricequantity_service.wsdl	food_taxfreepricequantity_Aldiservice.wsdl	meat_taxfreepricequantity_service.wsdl	title_mediataxfreepricequality_service.wsdl	beverage_taxfreepricephysical-quantity_service.wsdl	food_taxfreepricephysical-quantity_Aldiservice.wsdl	meat_taxfreepricephysical-quantity_Aldiservice.wsdl	