bookpersonOptional_price_service.wsdl	bookperson_price_service.wsdl	bookpersoncreditcardaccount_price_service.wsdl	bookpersoncreditcardaccount_recommendedprice_service.wsdl	bookpersoncreditcardaccount_taxedfreeprice_service.wsdl	book_person_Publisherservice.wsdl	bookperson__service.wsdl	bookpersoncreditaccount__Beaservice.wsdl	bookpersoncreditaccount__service.wsdl	personbookliabilityaccount__service.wsdl	book_readerreviewperson_service.wsdl	bookpersoncreditcardaccount__BShopservice.wsdl	bookpersoncreditcardaccount__service.wsdl	novelperson_price_service.wsdl	1personbicyclecar_price_Kohlservice.wsdl	1personbicyclecar_price_service.wsdl	1personbicyclecar_price_TheBestservice.wsdl	auto1personbicycle_price_service.wsdl	auto2personbicycle_price_service.wsdl	car2personbicycle_price_service.wsdl	