calculateDistanceInMiles.wsdl	getDistanceBetweenLocations.wsdl	getZipCodeInfoWorldwide.wsdl	calculateDistanceUsingSphericalGeometry.wsdl	getDistanceBetweenPlaces.wsdl	addressDistanceCalculator.wsdl	getDistanceBetweenCitiesWorldwide.wsdl	getZipCodesWithinCityState.wsdl	usPostalCode_distance.wsdl	uszipcode_distance.wsdl	checkAndLookupAddress.wsdl	calculatorDistanceSphericalLawOfCosines.wsdl	city_state_ZipCodes.wsdl	getLocationOfAddress.wsdl	googleGeocodingAPI.wsdl	getCoordinatesOfAddress.wsdl	getLocationOfAddressYahooMaps.wsdl	mileToKilometerConverter.wsdl	staticMapsDisplay.wsdl	googleStaticMapsAPI.wsdl	