car_report_service.wsdl	car_pricereport_service.wsdl	fastcar_pricereport_service.wsdl	cheapcar_pricereport_service.wsdl	4wheeledcaryear_pricereport_service.wsdl	car_taxedpricereport_service.wsdl	fastcar_taxedpricereport_service.wsdl	cheapcar_taxedpricereport_service.wsdl	_droughtreport_service.wsdl	_coffeeteareport_service.wsdl	_aps-slrpricereport_Musuemservice.wsdl	title_highcomedyfilmreport_service.wsdl	SPD-Grune_service.wsdl	car_price_service.wsdl	car_technology_service.wsdl	fastcar_technology_service.wsdl	lenthu_rentcar_service.wsdl	3wheeledcar_price_service.wsdl	4wheeledcar_price_service.wsdl	4wheeledcar_technology_service.wsdl	