careorganization_diagnosticprocesstimeduration_service.wsdl	HDP2_service.wsdl	hospital_diagnosticprocesstimeduration_service.wsdl	medicalclinic_diagnosticprocesstimeduration_service.wsdl	careorganization_diagnosticprocesstimeinterval_service.wsdl	careorganization_diagnosticprocesstimemeasure_service.wsdl	careorganization_diagnosticprocess_service.wsdl	CAD_medical_service.wsdl	hospital_diagnosticprocesstimeinterval_service.wsdl	hospital_diagnosticprocesstimemeasure_service.wsdl	medicalclinic_diagnosticprocesstimeinterval_service.wsdl	medicalclinic_diagnosticprocesstimemeasure_service.wsdl	_diagnosticprocessorganization_service.wsdl	organization_diagnosticprocess_service.wsdl	organization_diagnosticprocesscost_service.wsdl	hospital_diagnosticprocess_MedDiagservice.wsdl	hospital_diagnosticprocess_service.wsdl	medicalclinic_diagnosticprocess_service.wsdl	questionhospital_diagnosticprocess_service.wsdl	HDP_service.wsdl	