cdplayer_recommendedprice_service.wsdl	cdplayermp3player_price_service.wsdl	mp3playerdvdplayer_recommendedprice_service.wsdl	mp3playerdvdplayer_Recpriceshipping_service.wsdl	portabledvdplayermp3player_recommendedpricetaxedprice_servi.wsdl	portabledvdplayermp3player_recommendedpricetaxedprice_service.wsdl	mediaplayer_recommendedpriceineuro_service.wsdl	mp3playerdvdplayer_Recpriceshipping_USservice.wsdl	mp3playerportabledvdplayer_recommendedpricequality_service.wsdl	cdplayer_maxprice_service.wsdl	cdplayer_taxedprice_service.wsdl	mp3playercdplayermicrowaveoven_price_service.wsdl	dvdplayermp3player_Recprice_service.wsdl	dvdplayermp3player_RecpriceEuro_service.wsdl	dvdplayermp3player_Recpricemessage_service.wsdl	author_novelrecommendedprice_service.wsdl	book_recommendedprice_RegisteredUserservice.wsdl	book_recommendedprice_service.wsdl	butter_recommendedprice_service.wsdl	car_recommendedprice_service.wsdl	