checkAndLookupAddress.wsdl	getZipCodeInfoWorldwide.wsdl	city_state_ZipCodes.wsdl	calculateDistanceInMiles.wsdl	getLocationOfAddress.wsdl	getMapOfAddress.wsdl	addressGeocoder.wsdl	geocodeUSAddress.wsdl	addressDistanceCalculator.wsdl	getCoordinatesOfAddress.wsdl	real-time_geocodingStreetAddress.wsdl	getMapOfUSAddress.wsdl	getLocationOfAddressWorldwide.wsdl	academic_address_service.wsdl	employee_address_service.wsdl	person_address_service.wsdl	researcher_address_HOM2service.wsdl	researcher_address_service.wsdl	postal-addresscity_hotel_service.wsdl	educational-employee_address_service.wsdl	