city_state_ZipCodes.wsdl	getZipCodeInfoWorldwide.wsdl	checkAndLookupAddress.wsdl	getZipcodeForUSCity.wsdl	getLocationOfCityState.wsdl	getLocationOfAddress.wsdl	getLocationOfUSCity.wsdl	getUSZipCodeLocation.wsdl	geocodeUSAddress.wsdl	getGeographicAreaOfZipCode.wsdl	getZipCodeLocation.wsdl	getMapOfUSAddress.wsdl	real-time_geocodingStreetAddress.wsdl	getDistanceBetweenPlaces.wsdl	getCoordinatesOfAddress.wsdl	getATMLocationsInCity.wsdl	getMapOfAddress.wsdl	getZipCodeInfo.wsdl	getZipCodesWithinCityState.wsdl	getListOfMatchingCities.wsdl	