citygovernment_lending_service.wsdl	government_lending_service.wsdl	degreegovernment_lending_service.wsdl	nationalgovernment_lending_service.wsdl	academic-degreegovernment_lending_service.wsdl	academic-degreegovernmentorganization_lending_service.wsdl	missilegovernment_lendingrange_service.wsdl	ballisticmissilegovernment_lendingrange_service.wsdl	missilegovernmentorganization_lendingrange_service.wsdl	ballisticmissilegovernmentorganization_lendingrange_service.wsdl	award_lending_GermanGovservice.wsdl	degree_lending_GermanGovservice.wsdl	academic-degree_lending_GermanGovservice.wsdl	award_lendingduration_GermanGovservice.wsdl	degree_lendingduration_GermanGovservice.wsdl	academic-degree_lendingduration_GermanGovservice.wsdl	activity_city_service.wsdl	sightseeing_city_service.wsdl	getUSZipCodeLocation.wsdl	hikingsurfing_city_service.wsdl	