country_deacon_service.wsdl	citycountryduration__HotelReserveservice.wsdl	country_drought_service.wsdl	country_hotel_service.wsdl	country_lightning_service.wsdl	country_map_service.wsdl	country_profession_service.wsdl	citycountry_accommodation_service.wsdl	citycountry_hotel_service.wsdl	countrycity_hotel_service.wsdl	countryvillage_hotel_service.wsdl	towncountry_hotel_service.wsdl	countrycapital-city_hotel_service.wsdl	country_companyprofession_service.wsdl	country_corporationprofession_service.wsdl	country_occupationaltrade_service.wsdl	country_organizationprofession_service.wsdl	country_skilledoccupation_jobsservice.wsdl	country_skilledoccupation_service.wsdl	country_sportsposition_service.wsdl	