degree_scholarship_GermanGovservice.wsdl	academic-degree_scholarship_GermanGovservice.wsdl	degreegovernment_scholarship_service.wsdl	governmentdegree_scholarship_service.wsdl	governmentdegree_scholarship_TheBestservice.wsdl	academic-degreegovernment_scholarship_service.wsdl	degreegovernmentorganization_scholarship_service.wsdl	degreenationalgovernment_scholarship_service.wsdl	degree_scholarshipduration_GermanGovservice.wsdl	academic-degree_scholarshipduration_GermanGovservice.wsdl	governmentdegree_scholarshipquantity_service.wsdl	award_scholarship_GermanGovservice.wsdl	government_scholarship_service.wsdl	governmentaward_scholarship_service.wsdl	governmentorganization_scholarship_service.wsdl	nationalgovernment_scholarship_service.wsdl	award_scholarshipduration_GermanGovservice.wsdl	award_scholarshipduration_SwissGovservice.wsdl	government_scholarshiporganization_service.wsdl	nationalgovernment_scholarshipquantity_service.wsdl	