durationgeopolitical-entitycity_bedandbreakfast_service.wsdl	time-measuregeopolitical-entitycity_bedandbreakfast_service.wsdl	geopolitical-entity_bedandbreakfast_service.wsdl	city_bedandbreakfast_service.wsdl	geographical-region_bedandbreakfast_service.wsdl	durationgeopolitical-entitycity_accommodation_service.wsdl	durationgeopolitical-entitycity_hotel_service.wsdl	geopolitical-entity_professiontimeduration_service.wsdl	geopolitical-entity_occupationaltradetimeduration_service.wsdl	geopolitical-entity_skilledoccupationtimeduration_service.wsdl	time-measuregeopolitical-entitycity_accommodation_service.wsdl	time-measuregeopolitical-entitycity_hotel_service.wsdl	citycountryduration__HotelReserveservice.wsdl	AddLinks__service.wsdl	durationcountrycity_hotel_service.wsdl	geopolitical-entity_accommodation_service.wsdl	geopolitical-entity_drought_service.wsdl	geopolitical-entity_hotel_service.wsdl	geopolitical-entity_lightning_service.wsdl	geopolitical-entity_profession_service.wsdl	