car_technology_service.wsdl	fastcar_technology_service.wsdl	4wheeledcar_technology_service.wsdl	cheapcar_technology_service.wsdl	expensivecar_technology_service.wsdl	auto_technology_service.wsdl	car_price_service.wsdl	car_report_service.wsdl	lenthu_rentcar_service.wsdl	3wheeledcar_price_service.wsdl	4wheeledcar_price_service.wsdl	bicyclecar_price_service.wsdl	carbicycle_price_service.wsdl	carcycle_price_service.wsdl	cheapcar_price_service.wsdl	expensivecar_price_service.wsdl	1personbicyclecar_price_Kohlservice.wsdl	1personbicyclecar_price_service.wsdl	1personbicyclecar_price_TheBestservice.wsdl	3wheeledcaryear_price_service.wsdl	