car_taxedpricereport_service.wsdl	fastcar_taxedpricereport_service.wsdl	cheapcar_taxedpricereport_service.wsdl	SPD-Grune_service.wsdl	car_pricereport_service.wsdl	fastcar_pricereport_service.wsdl	cheapcar_pricereport_service.wsdl	4wheeledcaryear_pricereport_service.wsdl	car_report_service.wsdl	_aps-slrpricereport_Musuemservice.wsdl	car_taxedpriceprice_service.wsdl	carbicycle_taxedprice_service.wsdl	cyclecar_pricetaxedprice_service.wsdl	_droughtreport_service.wsdl	_coffeeteareport_service.wsdl	title_highcomedyfilmreport_service.wsdl	author_noveltaxedprice_service.wsdl	book_taxedprice_service.wsdl	butter_taxedprice_service.wsdl	coffee_taxedprice_service.wsdl	