findNearbyWikipediaArticles.wsdl	findNearbyPostalCodes.wsdl	findPlaceNamePostalCode.wsdl	getZipCodesWithinCityState.wsdl	getLocationOfAddress.wsdl	getAddressOfLocation.wsdl	getDistanceBetweenPlaces.wsdl	getZipCodeInfo.wsdl	getZipCodeLocation.wsdl	getLocationOfAddressWorldwide.wsdl	getGeographicAreaOfZipCode.wsdl	getLocationOfCityWorldwide.wsdl	searchFormattedAddress.wsdl	searchRawAddress.wsdl	getDistanceBetweenLocations.wsdl	getATMLocationsInCity.wsdl	getElevationFromLocation.wsdl	getCoordinatesOfAddress.wsdl	calculateSunriseTime.wsdl	calculatorDistanceSphericalLawOfCosines.wsdl	