gazetteerLookupLocation.wsdl	queryParserLocation.wsdl	getTrafficInformation.wsdl	getDrivingDirections.wsdl	googleStaticMapsAPI.wsdl	getLocationOfAddress.wsdl	getATMLocationsInCity.wsdl	getLocationOfCityWorldwide.wsdl	locationlocation_icon_service.wsdl	locationlocation_map_service.wsdl	locationlocation_map_SRIservice.wsdl	location_icon_service.wsdl	location_photograph_service.wsdl	locationlocation_arrowfigure_service.wsdl	getDistanceBetweenCitiesWorldwide.wsdl	getLocationOfZipCodeWorldwide.wsdl	findNearbyWikipediaArticles.wsdl	staticMapsDisplay.wsdl	googleGeocodingAPI.wsdl	findPlaceNamePostalCode.wsdl	