geographical-region_companyprofession_service.wsdl	country_companyprofession_service.wsdl	company_profession_service.wsdl	geopolitical-entity_companyprofession_service.wsdl	geographical-region_companyoccupationaltrade_service.wsdl	geographical-region_companyskilledoccupation_service.wsdl	_professiongeographical-region_USservice.wsdl	geographical-region_corporationprofession_service.wsdl	geographical-region_organizationprofession_service.wsdl	country_companyskilledoccupation_service.wsdl	geopolitical-entity_companyskilledoccupation_service.wsdl	amount-of-moneycar_pricecompany_service.wsdl	country_companyoccupationaltrade_service.wsdl	geopolitical-entity_companyoccupationaltrade_service.wsdl	geopolitical-entity_skilledoccupationcompany_service.wsdl	company_skilledoccupation_service.wsdl	companycountry_skilledoccupation_service.wsdl	public-companycountry_skilledoccupation_service.wsdl	country_profession_service.wsdl	geopolitical-entity_profession_service.wsdl	