geopolitical-entityrecorded-video_activityhotel_service.wsdl	geopolitical-entity_hotel_service.wsdl	durationgeopolitical-entitycity_hotel_service.wsdl	geopolitical-entity_luxuryhotel_service.wsdl	time-measuregeopolitical-entitycity_hotel_service.wsdl	activity_beach_service.wsdl	activity_city_service.wsdl	activity_destination_service.wsdl	activity_farmland_service.wsdl	activity_town_service.wsdl	activity_familydestination_service.wsdl	activity_nationalpark_service.wsdl	activity_ruralarea_service.wsdl	activity_urbanarea_service.wsdl	_hotel_Worldwideservice.wsdl	city_hotel_Germanservice.wsdl	city_hotel_Saarlandservice.wsdl	city_hotel_service.wsdl	country_hotel_service.wsdl	village_hotel_service.wsdl	