getATMLocationsInCity.wsdl	getLocationOfAddress.wsdl	getLocationOfCityWorldwide.wsdl	getDistanceBetweenCitiesWorldwide.wsdl	getLocationOfCityState.wsdl	getZipCodeInfoWorldwide.wsdl	city_state_ZipCodes.wsdl	getLocationOfUSCity.wsdl	getDistanceBetweenLocations.wsdl	checkAndLookupAddress.wsdl	getZipcodeForUSCity.wsdl	getUSZipCodeLocation.wsdl	geocodeUSAddress.wsdl	real-time_geocoding.wsdl	getZipCodeInfo.wsdl	getDistanceBetweenPlaces.wsdl	getZipCodeLocation.wsdl	getZipCodesWithinCityState.wsdl	getCoordinatesOfAddress.wsdl	real-time_geocodingStreetAddress.wsdl	