getCoordinatesOfAddress.wsdl	staticMapsDisplay.wsdl	getLocationOfAddressYahooMaps.wsdl	googleGeocodingAPI.wsdl	real-time_geocodingStreetAddress.wsdl	geocodeUSAddress.wsdl	getMapOfUSAddress.wsdl	getMapOfAddress.wsdl	getPlaceOfAddress.wsdl	getLocationOfAddress.wsdl	getZipCodeInfoWorldwide.wsdl	real-time_geocoding.wsdl	city_state_ZipCodes.wsdl	addressGeocoder.wsdl	checkAndLookupAddress.wsdl	getLocationOfUSZipcode.wsdl	googleStaticMapsAPI.wsdl	objectsMappingService.wsdl	findPlaceNamePostalCode.wsdl	getLocationOfCityState.wsdl	