getDistanceBetweenLocations.wsdl	getLocationOfAddress.wsdl	getLocationOfCityWorldwide.wsdl	calculateDistanceInMiles.wsdl	getDistanceBetweenPlaces.wsdl	calculatorDistanceSphericalLawOfCosines.wsdl	getZipCodeLocation.wsdl	getZipCodesWithinCityState.wsdl	getATMLocationsInCity.wsdl	addressDistanceCalculator.wsdl	calculateDistanceUsingSphericalGeometry.wsdl	uszipcode_distance.wsdl	getDistanceBetweenCitiesWorldwide.wsdl	searchFormattedAddress.wsdl	searchRawAddress.wsdl	usPostalCode_distance.wsdl	getZipCodeInfoWorldwide.wsdl	getGeographicAreaOfZipCode.wsdl	googleGeocodingAPI.wsdl	getElevationFromLocation.wsdl	