getDistanceBetweenPlaces.wsdl	getZipCodesWithinCityState.wsdl	getZipCodeInfo.wsdl	findPlaceNamePostalCode.wsdl	findNearbyWikipediaArticles.wsdl	findNearbyPostalCodes.wsdl	getCoordinatesOfAddress.wsdl	getDistanceBetweenLocations.wsdl	usPostalCode_distance.wsdl	getDistanceBetweenCitiesWorldwide.wsdl	getLocationOfAddress.wsdl	calculatorDistanceSphericalLawOfCosines.wsdl	getZipCodeInfoWorldwide.wsdl	city_state_ZipCodes.wsdl	getZipCodeLocation.wsdl	getATMLocationsInCity.wsdl	getZipcodeForUSCity.wsdl	getGeographicAreaOfZipCode.wsdl	calculateDistanceInMiles.wsdl	uszipcode_distance.wsdl	