getLocationOfCityState.wsdl	getLocationOfUSCity.wsdl	city_state_ZipCodes.wsdl	getZipcodeForUSCity.wsdl	getZipCodeInfoWorldwide.wsdl	getDistanceBetweenCitiesWorldwide.wsdl	getATMLocationsInCity.wsdl	getUSZipCodeLocation.wsdl	getLocationOfAddress.wsdl	real-time_geocoding.wsdl	getMapOfUSAddress.wsdl	getCoordinatesOfAddress.wsdl	getListOfMatchingCities.wsdl	geocodeUSAddress.wsdl	checkAndLookupAddress.wsdl	citycity_map_service.wsdl	activity_city_service.wsdl	sightseeing_city_service.wsdl	real-time_geocodingStreetAddress.wsdl	hikingsurfing_city_service.wsdl	