getLocationOfAddress.wsdl	getLocationOfCityWorldwide.wsdl	getATMLocationsInCity.wsdl	getDistanceBetweenLocations.wsdl	getZipCodeLocation.wsdl	findNearbyWikipediaArticles.wsdl	findNearbyPostalCodes.wsdl	getAddressOfLocation.wsdl	getGeographicAreaOfZipCode.wsdl	findPlaceNamePostalCode.wsdl	searchFormattedAddress.wsdl	getDistanceBetweenPlaces.wsdl	getZipCodeInfo.wsdl	getLocationOfAddressWorldwide.wsdl	searchRawAddress.wsdl	getZipCodesWithinCityState.wsdl	getZipCodeInfoWorldwide.wsdl	city_state_ZipCodes.wsdl	getElevationFromLocation.wsdl	getLocationOfZipCodeWorldwide.wsdl	