getPlaceOfAddress.wsdl	getLocationOfAddressYahooMaps.wsdl	getCoordinatesOfAddress.wsdl	renderMapService.wsdl	_Francemap_service.wsdl	_mapFrankfurtBerlin_service.wsdl	_mapGerman_service.wsdl	country_map_service.wsdl	citycity_map_service.wsdl	locationlocation_map_service.wsdl	locationlocation_map_SRIservice.wsdl	getMapOfUSAddress.wsdl	geographical-region_mapFromFrankfurt_service.wsdl	geographical-region_mapToBerlin_service.wsdl	geographical-regiongeographical-region_map_Gorgservice.wsdl	geographical-regiongeographical-region_map_service.wsdl	getMapOfAddress.wsdl	staticMapsDisplay.wsdl	googleStaticMapsAPI.wsdl	objectsMappingService.wsdl	