getZipCodesWithinCityState.wsdl	getDistanceBetweenPlaces.wsdl	getZipCodeInfo.wsdl	findPlaceNamePostalCode.wsdl	findNearbyWikipediaArticles.wsdl	findNearbyPostalCodes.wsdl	getCoordinatesOfAddress.wsdl	getLocationOfAddress.wsdl	getDistanceBetweenLocations.wsdl	getZipCodeLocation.wsdl	calculatorDistanceSphericalLawOfCosines.wsdl	getGeographicAreaOfZipCode.wsdl	usPostalCode_distance.wsdl	getATMLocationsInCity.wsdl	googleGeocodingAPI.wsdl	getAddressOfLocation.wsdl	getLocationOfAddressWorldwide.wsdl	getDistanceBetweenCitiesWorldwide.wsdl	getLocationOfCityWorldwide.wsdl	getZipCodeInfoWorldwide.wsdl	