getZipCodeInfoWorldwide.wsdl	city_state_ZipCodes.wsdl	checkAndLookupAddress.wsdl	getLocationOfAddress.wsdl	getATMLocationsInCity.wsdl	getMapOfAddress.wsdl	getZipcodeForUSCity.wsdl	getDistanceBetweenPlaces.wsdl	getLocationOfCityState.wsdl	getCoordinatesOfAddress.wsdl	getZipCodeInfo.wsdl	getLocationOfCityWorldwide.wsdl	getZipCodeLocation.wsdl	getLocationOfUSCity.wsdl	geocodeUSAddress.wsdl	real-time_geocodingStreetAddress.wsdl	getZipCodesWithinCityState.wsdl	getMapOfUSAddress.wsdl	getUSZipCodeLocation.wsdl	calculateDistanceInMiles.wsdl	