googleGeocodingAPI.wsdl	googleStaticMapsAPI.wsdl	getCoordinatesOfAddress.wsdl	getLocationOfAddressYahooMaps.wsdl	geocodeUSAddress.wsdl	real-time_geocodingStreetAddress.wsdl	real-time_geocoding.wsdl	getLocationOfUSZipcode.wsdl	getPlaceOfAddress.wsdl	getLocationOfAddress.wsdl	getDistanceBetweenLocations.wsdl	getZipCodeInfoWorldwide.wsdl	calculateDistanceInMiles.wsdl	staticMapsDisplay.wsdl	getMapOfAddress.wsdl	getLocationOfCityWorldwide.wsdl	checkAndLookupAddress.wsdl	city_state_ZipCodes.wsdl	addressGeocoder.wsdl	findNearbyPostalCodes.wsdl	