governmentweapon_funding_service.wsdl	governmentmissileweapon_fundingfunding_service.wsdl	governmentmissileweapon_funding_service.wsdl	nationalgovernmentweapon_funding_service.wsdl	weaponmissile_funding_Iraqservice.wsdl	government_funding_ABombservice.wsdl	government_funding_BallMissileservice.wsdl	government_funding_ForPhDservice.wsdl	government_funding_Missileservice.wsdl	awardgovernment_funding_service.wsdl	degreegovernment_funding_service.wsdl	governmentmissile_funding_Reliableservice.wsdl	governmentmissile_funding_service.wsdl	projectilegovernment_funding_service.wsdl	academic-degreegovernment_funding_service.wsdl	missilegovernmentorganization_funding_service.wsdl	academic-degreegovernmentorganization_funding_service.wsdl	governmentorganizationselfpowereddevice_funding_service.wsdl	missilegovernment_fundingrange_service.wsdl	ballisticmissilegovernment_fundingrange_service.wsdl	