grocerystore_butterquantity_service.wsdl	retailstore_butterquantity_service.wsdl	grocerystore_butterselling_service.wsdl	grocerystore_flourdoughbutter_service.wsdl	grocerystore_foodquantity_service.wsdl	grocerystore_sandwichquantity_service.wsdl	Available_preparedfoodquantity_service.wsdl	grocerystore_breadorbiscuitquantity_service.wsdl	grocerystore_preparedfoodquantity_service.wsdl	Required_preparedfoodquantity_service.wsdl	retailstore_foodquantity_service.wsdl	retailstore_sandwichquantity_service.wsdl	retailstore_breadorbiscuitquantity_service.wsdl	retailstore_preparedfoodquantity_service.wsdl	butter_maxprice_service.wsdl	butter_recommendedprice_service.wsdl	butter_taxedprice_service.wsdl	preparedfood_GSprice_service.wsdl	grocerystore_fodder_AnimalFoodservice.wsdl	grocerystore_food_service.wsdl	