grocerystore_fodder_AnimalFoodservice.wsdl	_fodder_USimportservice.wsdl	preparedfood_GSprice_service.wsdl	grocerystore_food_service.wsdl	grocerystore_butterquantity_service.wsdl	grocerystore_butterselling_service.wsdl	grocerystore_foodquantity_service.wsdl	grocerystore_preparedfood_service.wsdl	grocerystore_sandwichquantity_service.wsdl	grocerystore_teaprice_service.wsdl	Available_preparedfoodquantity_service.wsdl	grocerystore_breadorbiscuitquantity_service.wsdl	grocerystore_flourdoughbutter_service.wsdl	grocerystore_preparedfoodprice_service.wsdl	grocerystore_preparedfoodquantity_service.wsdl	Required_preparedfoodquantity_service.wsdl	drugstore_tea_service.wsdl	retailstore_apple_service.wsdl	store_preparedfood_Merchantservice.wsdl	store_preparedfood_service.wsdl	