HealthInsurance_service.wsdl	shoppingmall_pricecellphonewithcamera_service.wsdl	ContactEMA_services.wsdl	AuthorizePhysician_service.wsdl	ProvideNonMedicalTransportInformation_service.wsdl	ProvideMedicalTransportInformation_service.wsdl	UpdatePatientMedicalRecords_service.wsdl	PatientTransport_service.wsdl	HospitalPhysician_service.wsdl	SetUpCostAndHealingPlan_service.wsdl	country_sportsposition_service.wsdl	_propositionmotion_service.wsdl	country_professionfulltimeposition_service.wsdl	country_professionparttimeposition_service.wsdl	geopolitical-entity_professionfulltimeposition_service.wsdl	geopolitical-entity_professionparttimeposition_service.wsdl	municipal-unit_professionfulltimeposition_service.wsdl	municipal-unit_professionparttimeposition_service.wsdl	country_occupationaltradefulltimeposition_service.wsdl	country_occupationaltradeparttimeposition_service.wsdl	