hiking_town_service.wsdl	surfinghiking_town_service.wsdl	activity_town_service.wsdl	sightseeing_town_service.wsdl	sports_town_service.wsdl	towncountry_hotel_service.wsdl	hiking_destination_service.wsdl	hiking_nationalpark_service.wsdl	hiking_ruralarea_service.wsdl	hiking_urbanarea_service.wsdl	getCoordinatesOfAddress.wsdl	hikingsurfing_city_service.wsdl	organizationhiking_destination_service.wsdl	surfinghiking_city_service.wsdl	surfinghiking_city_SFservice.wsdl	surfinghiking_destination_DFGservice.wsdl	surfinghiking_destination_PDSservice.wsdl	surfinghiking_destination_PFservice.wsdl	surfinghiking_destination_service.wsdl	surfinghiking_nationalpark_service.wsdl	