hiking_nationalpark_service.wsdl	surfinghiking_nationalpark_service.wsdl	activity_nationalpark_service.wsdl	sightseeing_nationalpark_service.wsdl	sports_nationalpark_service.wsdl	surfing_nationalpark_service.wsdl	nationalgovernment_lending_service.wsdl	nationalgovernment_scholarship_service.wsdl	degreenationalgovernment_scholarship_service.wsdl	nationalgovernmentweapon_funding_service.wsdl	nationalgovernment_scholarshipquantity_service.wsdl	nationalgovernment_scholarshipquantityduration_service.wsdl	nationalgovernment_physical-quantityscholarshiplandarea_service.wsdl	hiking_destination_service.wsdl	hiking_town_service.wsdl	hiking_ruralarea_service.wsdl	hiking_urbanarea_service.wsdl	hikingsurfing_city_service.wsdl	organizationhiking_destination_service.wsdl	surfinghiking_city_service.wsdl	