hiking_ruralarea_service.wsdl	surfinghiking_ruralarea_service.wsdl	activity_ruralarea_service.wsdl	adventure_ruralarea_service.wsdl	sports_ruralarea_service.wsdl	surfing_ruralarea_service.wsdl	hiking_urbanarea_service.wsdl	activity_urbanarea_service.wsdl	adventure_urbanarea_service.wsdl	flip_slider.wsdl	nationalgovernment_physical-quantityscholarshiplandarea_service.wsdl	getLocationOfCityState.wsdl	hiking_destination_service.wsdl	hiking_town_service.wsdl	calculateDistanceInMiles.wsdl	hiking_nationalpark_service.wsdl	getLocationOfUSZipcode.wsdl	getAltitudeOfLocation.wsdl	getElevationFromLocation.wsdl	hikingsurfing_city_service.wsdl	