hospital_postal-addressinvestigating_service.wsdl	hospital_investigatingaddress_service.wsdl	academic_postal-address_service.wsdl	employee_postal-address_service.wsdl	employee_postal-address_XYZService.wsdl	researcher_postal-address_service.wsdl	educational-employee_postal-address_service.wsdl	researcher-in-academia_publication-referencepostal-address_.wsdl	researcher-in-academia_publication-referencepostal-address_service.wsdl	postal-addresscity_hotel_service.wsdl	hospital_investigating_service.wsdl	getLocationOfAddress.wsdl	getCoordinatesOfAddress.wsdl	findPlaceNamePostalCode.wsdl	findNearbyPostalCodes.wsdl	_investigating_Saarservice.wsdl	careorganization_investigating_service.wsdl	medicalclinic_investigating_MedService.wsdl	medicalclinic_investigating_service.wsdl	academic_address_service.wsdl	