maxprice_beercola_service.wsdl	maxprice_colabeer_service.wsdl	maxprice_whiskeycolabeer_service.wsdl	maxprice_cola_Bestservice.wsdl	maxprice_cola_service.wsdl	qualitymaxprice_cola_service.wsdl	maxprice_colabreadorbiscuit_Bothservice.wsdl	maxprice_colabreadorbiscuit_service.wsdl	author_novelmaxprice_service.wsdl	butter_maxprice_service.wsdl	coffee_maxprice_service.wsdl	sandwich_maxprice_service.wsdl	tea_maxprice_service.wsdl	mediaplayer_maxprice_service.wsdl	mp3player_maxprice_service.wsdl	autobicycle_maxprice_service.wsdl	autocycle_maxprice_service.wsdl	cdplayer_maxprice_service.wsdl	dvdplayer_maxprice_service.wsdl	novel_authormaxprice_service.wsdl	