mediaplayer_maxprice_service.wsdl	mp3player_maxprice_service.wsdl	cdplayer_maxprice_service.wsdl	dvdplayer_maxprice_service.wsdl	title_mediamaxpricequality_service.wsdl	title_videomediamaxpricequality_service.wsdl	author_novelmaxprice_service.wsdl	butter_maxprice_service.wsdl	coffee_maxprice_service.wsdl	sandwich_maxprice_service.wsdl	tea_maxprice_service.wsdl	autobicycle_maxprice_service.wsdl	autocycle_maxprice_service.wsdl	novel_authormaxprice_service.wsdl	preparedfood_maxprice_service.wsdl	author_bookmaxprice_service.wsdl	author_monographmaxprice_service.wsdl	author_publicationmaxprice_service.wsdl	auto2personbicycle_maxprice_service.wsdl	beverage_maxpricequantity_service.wsdl	