mercantileorganization_food_service.wsdl	PhillipDigCamera_price_service.wsdl	mercantileorganization_compactprice_service.wsdl	mercantileorganization_slrprice_service.wsdl	_food_Exportservice.wsdl	_food_HEBgroceryCompservice.wsdl	grocerystore_food_service.wsdl	store_preparedfood_Merchantservice.wsdl	store_preparedfood_service.wsdl	grocerystore_foodquantity_service.wsdl	grocerystore_preparedfood_service.wsdl	retailstore_foodquality_service.wsdl	retailstore_foodquantity_service.wsdl	retailstore_preparedfood_service.wsdl	wholesalestore_preparedfood_service.wsdl	Available_preparedfoodquantity_service.wsdl	grocerystore_preparedfoodprice_service.wsdl	grocerystore_preparedfoodquantity_service.wsdl	Required_preparedfoodquantity_service.wsdl	retailstore_preparedfoodquantity_service.wsdl	