mileToKilometerConverter.wsdl	CAD_medical_service.wsdl	municipal-unit_drought_service.wsdl	municipal-unit_lightning_service.wsdl	municipal-unit_warmfront_service.wsdl	municipal-unit_weatherfront_service.wsdl	municipal-unit_weatherprocess_service.wsdl	municipal-unit_weathersystem_service.wsdl	municipal-unit_professiontimeduration_service.wsdl	municipal-unit_professiontimemeasure_service.wsdl	municipal-unit_weatherseason_service.wsdl	municipal-unit_occupationaltradetimeduration_service.wsdl	municipal-unit_occupationaltradetimemeasure_service.wsdl	municipal-unit_skilledoccupationtimeduration_service.wsdl	municipal-unit_skilledoccupationtimemeasure_service.wsdl	getDrivingDirections.wsdl	municipal-unit_professionfulltimeposition_service.wsdl	municipal-unit_professionparttimeposition_service.wsdl	municipal-unit_occupationaltradefulltimeposition_service.wsdl	municipal-unit_occupationaltradeparttimeposition_service.wsdl	