municipal-unit_weatherseason_service.wsdl	city_weatherseason_service.wsdl	country_weatherseason_service.wsdl	geographical-region_weatherseason_service.wsdl	geopolitical-entity_weatherseason_service.wsdl	geopolitical-entity_weatherseasonproposition_service.wsdl	geopolitical-entity_weatherseasontimeposition_service.wsdl	municipal-unit_weatherfront_service.wsdl	municipal-unit_weatherprocess_service.wsdl	municipal-unit_weathersystem_service.wsdl	UnsuccessfulDiagnosis_service.wsdl	municipal-unit_drought_service.wsdl	municipal-unit_lightning_service.wsdl	_weatherfront_BombayIndiaservice.wsdl	_weatherfront_Britishservice.wsdl	_weatherfront_Germanyservice.wsdl	_weatherprocess_Germanservice.wsdl	municipal-unit_warmfront_service.wsdl	city_weatherfront_service.wsdl	city_weathersystem_service.wsdl	