municipal-unit_warmfront_service.wsdl	_warmfront_Italyservice.wsdl	country_warmfront_service.wsdl	geographical-region_warmfront_service.wsdl	geopolitical-entity_warmfront_service.wsdl	municipal-unit_weatherfront_service.wsdl	_weatherfront_BombayIndiaservice.wsdl	_weatherfront_Britishservice.wsdl	_weatherfront_Germanyservice.wsdl	city_weatherfront_service.wsdl	country_weatherfront_service.wsdl	geographical-region_weatherfront_service.wsdl	geographical-region_weatherfront_WService.wsdl	geopolitical-entity_weatherfront_service.wsdl	municipal-unit_drought_service.wsdl	municipal-unit_lightning_service.wsdl	municipal-unit_weatherprocess_service.wsdl	municipal-unit_weathersystem_service.wsdl	municipal-unit_professiontimeduration_service.wsdl	municipal-unit_professiontimemeasure_service.wsdl	