NonMedicalFlightCompany_service.wsdl	ProvideMedicalFlightInformation_services.wsdl	BookMedicalFlight_service.wsdl	BookNonMedicalFlight_service.wsdl	GetNonMedicalFlightAccount_service.wsdl	GetMedicalFlightAccount_service.wsdl	SelectFlight_service.wsdl	ProvideNonMedicalTransportInformation_service.wsdl	ProvideMedicalTransportInformation_service.wsdl	GetMedicalTransportAccount_service.wsdl	GetNonMedicalTransportAccount_service.wsdl	HospitalPhysician_service.wsdl	UpdatePatientMedicalRecords_service.wsdl	SeePatientMedicalRecords_service.wsdl	BookMedicalTransport_service.wsdl	BookNonMedicalTransport_service.wsdl	PatientTransport_service.wsdl	_medicaldoctor_UNOservice.wsdl	medicalclinic_diagnosticprocesstimeduration_service.wsdl	medicalclinic_diagnosticprocesstimeinterval_service.wsdl	