objectpersoncreditaccount_price_service.wsdl	bookpersoncreditcardaccount_price_service.wsdl	printedmaterialpersoncreditcardaccount_price_service.wsdl	bookpersoncreditcardaccount_recommendedprice_service.wsdl	monographpersoncreditcardaccount_recommendedprice_service.wsdl	bookpersoncreditcardaccount_taxedfreeprice_service.wsdl	bookpersoncreditaccount__Beaservice.wsdl	bookpersoncreditaccount__service.wsdl	bookpersoncreditcardaccount__BShopservice.wsdl	bookpersoncreditcardaccount__service.wsdl	personmonographcreditcardaccount__service.wsdl	printedmaterialpersoncreditcardaccount__service.wsdl	GetMedicalFlightAccount_service.wsdl	GetNonMedicalTransportAccount_service.wsdl	GetNonMedicalFlightAccount_service.wsdl	GetMedicalTransportAccount_service.wsdl	objectperson__service.wsdl	bookusercreditcardaccount__service.wsdl	recommendedprice_coffeewithwhiskeycontentbearingobject_service.wsdl	recommendedprice_contentbearingobjectwhiskeycoffee_service.wsdl	