price_cola_Hallo2service.wsdl	price_cola_Halloservice.wsdl	maxprice_cola_Bestservice.wsdl	maxprice_cola_service.wsdl	price_cola_Gudduservice.wsdl	qualitymaxprice_cola_service.wsdl	taxfreeprice_cola_service.wsdl	maxprice_beercola_service.wsdl	maxprice_colabreadorbiscuit_Bothservice.wsdl	maxprice_colabreadorbiscuit_service.wsdl	maxprice_colabeer_service.wsdl	maxprice_whiskeycolabeer_service.wsdl	price_irishcoffeemixerycola_service.wsdl	untangibleobjects_cola_service.wsdl	KodakDigCamera_price_service.wsdl	novel_price_service.wsdl	_3WheeledAudiCarprice_service.wsdl	_3WheeledOpelCarPrice_service.wsdl	_price_CannonCameraservice.wsdl	_price_Fishservice.wsdl	