publication-number_edited-book_service.wsdl	AcademicBookNumberOrISBNSearch.wsdl	publication-number_book_Portalservice.wsdl	publication-number_book_service.wsdl	publication_book_service.wsdl	publication-number_bookauthor_service.wsdl	publication-number_bookauthorpublisher_service.wsdl	_book_Oracleservice.wsdl	book_authorbook-type_service.wsdl	EBookOrder1.wsdl	EBookOrder2.wsdl	EBookOrder3.wsdl	BookFinder.wsdl	BookSearchService.wsdl	isbn_book_service.wsdl	book_pricesizebook-type_service.wsdl	sciencefictionbook_authorbook-type_service.wsdl	academic-item-number_book_service.wsdl	AcademicBookNumberSearch.wsdl	novel_authorbook-type_service.wsdl	