publication-number_publicationauthor_service.wsdl	isbn_publicationauthor_service.wsdl	publication_author_service.wsdl	academic-item-number_publicationauthor_service.wsdl	publication-number_bookauthor_service.wsdl	author_publicationprice_service.wsdl	author_publicationmaxprice_service.wsdl	author_publicationrecommendedprice_service.wsdl	author_publicationtaxedprice_service.wsdl	publication-number_bookauthorpublisher_service.wsdl	author_publicationtaxfreeprice_service.wsdl	novel_author_BookOntoservice.wsdl	novel_author_MyOntoservice.wsdl	novel_author_service.wsdl	_author_CompJservice.wsdl	_author_DMservice.wsdl	book_author_EncSSservice.wsdl	book_author_service.wsdl	encyclopedia_author_service.wsdl	monograph_author_service.wsdl	