publication_publisher_service.wsdl	publication-number_bookauthorpublisher_service.wsdl	novel_publisher_service.wsdl	book_publisher_service.wsdl	encyclopedia_publisher_service.wsdl	monograph_publisher_service.wsdl	romanticnovel_publisher_service.wsdl	short-story_publisher_service.wsdl	science-fiction-novel_publisher_service.wsdl	sciencefictionbook_publisher_service.wsdl	isbn_publicationpublisher_service.wsdl	publication-number_publication_service.wsdl	publication_number_publication_service.wsdl	_publication_PPservice.wsdl	publication-number_currencypublication_service.wsdl	publication-number_publicationauthor_service.wsdl	isbn_publication_service.wsdl	text_publication_service.wsdl	academic-item-number_publication_service.wsdl	author_publicationprice_service.wsdl	