queryParserLocation.wsdl	gazetteerLookupLocation.wsdl	findPlaceNamePostalCode.wsdl	getTrafficInformation.wsdl	getDrivingDirections.wsdl	staticMapsDisplay.wsdl	googleStaticMapsAPI.wsdl	googleGeocodingAPI.wsdl	objectsMappingService.wsdl	findNearbyWikipediaArticles.wsdl	findNearbyPostalCodes.wsdl	getLocationOfAddress.wsdl	getATMLocationsInCity.wsdl	getLocationOfCityWorldwide.wsdl	getAddressOfLocation.wsdl	locationlocation_icon_service.wsdl	locationlocation_map_service.wsdl	locationlocation_map_SRIservice.wsdl	location_icon_service.wsdl	location_photograph_service.wsdl	