redLight_to_off.wsdl	redLight_to_on.wsdl	greenLight_to_off.wsdl	greenLight_to_on.wsdl	fill_pills.wsdl	switch_off_messemodul.wsdl	switch_on_messemodul.wsdl	flip_up_slider.wsdl	fall_down_pill.wsdl	flip_down_slider.wsdl	