researcher-in-academia_abstract-information_service.wsdl	researcher_abstract-information_service.wsdl	researcher-in-academia_address_service.wsdl	researcher-in-academia_address_TREEservice.wsdl	researcher-in-academia_address_ZOOservice.wsdl	researcher-in-academia_publication-referencepostal-address_.wsdl	researcher-in-academia_publication-referencepostal-address_service.wsdl	university_researcher_service.wsdl	researcher_address_HOM2service.wsdl	researcher_address_service.wsdl	visiting-researcher_address_service.wsdl	researcher_postal-address_service.wsdl	_lecturer-in-academiaMunchenUniversity_service.wsdl	_lecturer-in-academiaSaarlandUniversity_service.wsdl	_lecturer-in-academiaZambiaUniversity_service.wsdl	organization_lecturer-in-academia_service.wsdl	university_lecturer-in-academiaCurrentSemmester_service.wsdl	university_lecturer-in-academia_Recommendservice.wsdl	university_lecturer-in-academia_service.wsdl	university_professor-in-academia_service.wsdl	