retailstore_breadorbiscuitquantity_service.wsdl	grocerystore_breadorbiscuitquantity_service.wsdl	maxprice_colabreadorbiscuit_Bothservice.wsdl	maxprice_colabreadorbiscuit_service.wsdl	breadorbiscuit_recPricetaxedpriceineuro_service.wsdl	retailstore_butterquantity_service.wsdl	retailstore_foodquantity_service.wsdl	retailstore_sandwichquantity_service.wsdl	retailstore_preparedfoodquantity_service.wsdl	grocerystore_butterquantity_service.wsdl	grocerystore_foodquantity_service.wsdl	grocerystore_sandwichquantity_service.wsdl	Available_preparedfoodquantity_service.wsdl	grocerystore_preparedfoodquantity_service.wsdl	Required_preparedfoodquantity_service.wsdl	retailstore_apple_service.wsdl	retailstore_compactprice_service.wsdl	retailstore_foodquality_service.wsdl	retailstore_preparedfood_service.wsdl	retailstore_slrprice_service.wsdl	