romanticnovel_authorprice_service.wsdl	romanticnovel_authormaxprice_service.wsdl	romanticnovel_authorrecommendedprice_service.wsdl	romanticnovel_authortaxedprice_service.wsdl	romanticnovel_authorbook-type_service.wsdl	novel_authorprice_service.wsdl	book_authorprice_Novelservice.wsdl	book_authorprice_service.wsdl	short-story_authorprice_service.wsdl	novel_authormaxprice_service.wsdl	novel_authorrecommendedprice_service.wsdl	novel_authortaxedprice_service.wsdl	science-fiction-novel_authorprice_service.wsdl	science-fiction-novel_priceauthor_service.wsdl	author_novelprice_service.wsdl	sciencefictionbook_authorprice_service.wsdl	short-story_authormaxprice_service.wsdl	short-story_authorrecommendedprice_service.wsdl	short-story_authortaxedprice_service.wsdl	science-fiction-novel_authormaxprice_service.wsdl	