science-fiction-novel_authormaxprice_service.wsdl	sciencefictionbook_authormaxprice_service.wsdl	author_sciencefictionbookmaxprice_service.wsdl	title_sciencefictionfilmmaxpricequality_service.wsdl	science-fiction-novel_authorprice_service.wsdl	science-fiction-novel_priceauthor_service.wsdl	sciencefictionbook_authorprice_service.wsdl	science-fiction-novel_authorrecommendedprice_service.wsdl	science-fiction-novel_authortaxedprice_service.wsdl	author_sciencefictionbookprice_service.wsdl	novel_authormaxprice_service.wsdl	romanticnovel_authormaxprice_service.wsdl	short-story_authormaxprice_service.wsdl	sciencefictionbook_authorrecommendedprice_service.wsdl	sciencefictionbook_authortaxedprice_service.wsdl	author_novelmaxprice_service.wsdl	author_sciencefictionbookrecommendedprice_service.wsdl	author_sciencefictionbooktaxedprice_service.wsdl	author_bookmaxprice_service.wsdl	author_monographmaxprice_service.wsdl	