sciencefictionnovel_author_MyOntoservice.wsdl	sfnovel_authorauthor_BookOntoservice.wsdl	sciencefictionbook_author_service.wsdl	science-fiction-novel_authorbook-type_service.wsdl	science-fiction-novel_authorprice_service.wsdl	science-fiction-novel_priceauthor_service.wsdl	sciencefictionbook_authorbook-type_service.wsdl	sciencefictionbook_authorprice_service.wsdl	author_sciencefictionbookprice_service.wsdl	science-fiction-novel_authormaxprice_service.wsdl	science-fiction-novel_authorrecommendedprice_service.wsdl	science-fiction-novel_authortaxedprice_service.wsdl	sciencefictionbook_authormaxprice_service.wsdl	sciencefictionbook_authorrecommendedprice_service.wsdl	sciencefictionbook_authortaxedprice_service.wsdl	author_sciencefictionbookmaxprice_service.wsdl	author_sciencefictionbookrecommendedprice_service.wsdl	author_sciencefictionbooktaxedprice_service.wsdl	author_sciencefictionbooktaxfreeprice_service.wsdl	title_sciencefictionfilmpricequality_service.wsdl	