science-fiction-novel_publisher_service.wsdl	sciencefictionbook_publisher_service.wsdl	novel_publisher_service.wsdl	book_publisher_service.wsdl	encyclopedia_publisher_service.wsdl	monograph_publisher_service.wsdl	publication_publisher_service.wsdl	romanticnovel_publisher_service.wsdl	short-story_publisher_service.wsdl	publication-number_bookauthorpublisher_service.wsdl	isbn_publicationpublisher_service.wsdl	sfnovel_authorauthor_BookOntoservice.wsdl	author_sciencefictionbookprice_service.wsdl	sciencefictionnovel_author_MyOntoservice.wsdl	author_sciencefictionbookmaxprice_service.wsdl	author_sciencefictionbookrecommendedprice_service.wsdl	author_sciencefictionbooktaxedprice_service.wsdl	title_sciencefictionfilmpricequality_service.wsdl	DeoSFN_price_service.wsdl	sciencefictionbook_author_service.wsdl	