SeePatientMedicalRecords_service.wsdl	HospitalPhysician_service.wsdl	UpdatePatientMedicalRecords_service.wsdl	PatientTransport_service.wsdl	SetUpCostAndHealingPlan_service.wsdl	AuthorizePhysician_service.wsdl	geopolitical-entityrecorded-video_activityhotel_service.wsdl	GetMedicalFlightAccount_service.wsdl	GetNonMedicalTransportAccount_service.wsdl	GetNonMedicalFlightAccount_service.wsdl	GetMedicalTransportAccount_service.wsdl	BookMedicalTransport_service.wsdl	BookNonMedicalTransport_service.wsdl	BookMedicalFlight_service.wsdl	BookNonMedicalFlight_service.wsdl	_medicaldoctor_UNOservice.wsdl	NonMedicalFlightCompany_service.wsdl	ProvideMedicalFlightInformation_services.wsdl	medicalclinic_biopsy_service.wsdl	medicalclinic_experimenting_service.wsdl	