shoppingmall_compacttaxedprice_service.wsdl	shoppingmall_compactprice_service.wsdl	CCP_service.wsdl	mercantileorganization_compactprice_service.wsdl	retailstore_compactprice_service.wsdl	shoppingmall_cameraprice_service.wsdl	shoppingmall_recommendedprice_Shirtservice.wsdl	shoppingmall_slrprice_service.wsdl	shoppingmall_pricedigitalanalog_service.wsdl	shoppingmall_purchaseableitemprice_service.wsdl	shoppingmall_analogpricecalendar-date_service.wsdl	shoppingmall_calendar-datepricecamera_service.wsdl	shoppingmall_maxpricedigital-video_service.wsdl	shoppingmall_pricecellphonewithcamera_service.wsdl	shoppingmall_pricepurchaseableitemrange_service.wsdl	SRcamera_service.wsdl	shoppingmall_digital-slrpricecalendar-date_service.wsdl	author_noveltaxedprice_service.wsdl	book_taxedprice_service.wsdl	butter_taxedprice_service.wsdl	