shoppingmall_calendar-datepricecamera_service.wsdl	shoppingmall_analogpricecalendar-date_service.wsdl	shoppingmall_digital-slrpricecalendar-date_service.wsdl	shoppingmall_cameraprice_service.wsdl	shoppingmall_pricecellphonewithcamera_service.wsdl	SRcamera_service.wsdl	_cameraprice_MyShopservice.wsdl	_pricecamera_Wallmartservice.wsdl	_camerataxedprice_service.wsdl	_camerataxedpricedutytax_service.wsdl	getSunsetSunriseTimeOfLocation.wsdl	shoppingmall_compactprice_service.wsdl	shoppingmall_recommendedprice_Shirtservice.wsdl	shoppingmall_slrprice_service.wsdl	shoppingmall_compacttaxedprice_service.wsdl	shoppingmall_pricedigitalanalog_service.wsdl	shoppingmall_purchaseableitemprice_service.wsdl	datefruit_price_service.wsdl	CCP_service.wsdl	shoppingmall_maxpricedigital-video_service.wsdl	