short-story_publisher_service.wsdl	novel_publisher_service.wsdl	book_publisher_service.wsdl	encyclopedia_publisher_service.wsdl	monograph_publisher_service.wsdl	publication_publisher_service.wsdl	romanticnovel_publisher_service.wsdl	science-fiction-novel_publisher_service.wsdl	sciencefictionbook_publisher_service.wsdl	publication-number_bookauthorpublisher_service.wsdl	isbn_publicationpublisher_service.wsdl	short-story_author_service.wsdl	short-story_authorbook-type_service.wsdl	short-story_authorprice_service.wsdl	short-story_authormaxprice_service.wsdl	short-story_authorrecommendedprice_service.wsdl	short-story_authortaxedprice_service.wsdl	