short-story_authorbook-type_service.wsdl	book_authorbook-type_service.wsdl	novel_authorbook-type_service.wsdl	encyclopedia_authorbook-type_service.wsdl	isbn_bookauthor_service.wsdl	publication-number_bookauthor_service.wsdl	romanticnovel_authorbook-type_service.wsdl	sciencefictionbook_authorbook-type_service.wsdl	book_author_EncSSservice.wsdl	book_author_service.wsdl	academic-item-number_bookauthor_service.wsdl	science-fiction-novel_authorbook-type_service.wsdl	short-story_author_service.wsdl	book_authorprice_Novelservice.wsdl	book_authorprice_service.wsdl	book_authortext_service.wsdl	sciencefictionbook_author_service.wsdl	author_bookprice_service.wsdl	publication-number_bookauthorpublisher_service.wsdl	short-story_authorprice_service.wsdl	