sightseeing_city_service.wsdl	activity_city_service.wsdl	getUSZipCodeLocation.wsdl	hikingsurfing_city_service.wsdl	surfinghiking_city_service.wsdl	surfinghiking_city_SFservice.wsdl	getLocationOfCityState.wsdl	getListOfMatchingCities.wsdl	surfingorganization_city_service.wsdl	surfinggeneric-agent_city_service.wsdl	getLocationOfUSCity.wsdl	citycity_map_service.wsdl	getDistanceBetweenCitiesWorldwide.wsdl	sightseeing_town_service.wsdl	citycountryduration__HotelReserveservice.wsdl	city_accommodation_service.wsdl	city_hotel_Germanservice.wsdl	city_hotel_Saarlandservice.wsdl	city_hotel_service.wsdl	citycity_arrowfigure_service.wsdl	