sports_ruralarea_service.wsdl	activity_ruralarea_service.wsdl	adventure_ruralarea_service.wsdl	hiking_ruralarea_service.wsdl	surfing_ruralarea_service.wsdl	surfinghiking_ruralarea_service.wsdl	activity_urbanarea_service.wsdl	adventure_urbanarea_service.wsdl	hiking_urbanarea_service.wsdl	flip_slider.wsdl	nationalgovernment_physical-quantityscholarshiplandarea_service.wsdl	getLocationOfCityState.wsdl	country_sportsposition_service.wsdl	countrycity_sportshotel_service.wsdl	personcountrycity_sportshotel_service.wsdl	sports_beach_service.wsdl	sports_destination_service.wsdl	sports_farmland_service.wsdl	sports_town_service.wsdl	sportsorganization_destination_service.wsdl	