sports_beach_service.wsdl	activity_beach_service.wsdl	surfing_beach_service.wsdl	country_sportsposition_service.wsdl	countrycity_sportshotel_service.wsdl	personcountrycity_sportshotel_service.wsdl	sports_destination_service.wsdl	sports_farmland_service.wsdl	sports_town_service.wsdl	sportsorganization_destination_service.wsdl	generic-agentsports_destination_service.wsdl	generic-agentsports_destination_SportsService.wsdl	sportslegal-agent_destination_service.wsdl	sports_nationalpark_service.wsdl	sports_ruralarea_service.wsdl	