surfing_ruralarea_service.wsdl	surfinghiking_ruralarea_service.wsdl	activity_ruralarea_service.wsdl	adventure_ruralarea_service.wsdl	hiking_ruralarea_service.wsdl	sports_ruralarea_service.wsdl	activity_urbanarea_service.wsdl	adventure_urbanarea_service.wsdl	hiking_urbanarea_service.wsdl	flip_slider.wsdl	nationalgovernment_physical-quantityscholarshiplandarea_service.wsdl	getLocationOfCityState.wsdl	calculateDistanceInMiles.wsdl	getLocationOfUSZipcode.wsdl	getAltitudeOfLocation.wsdl	surfing_beach_service.wsdl	surfing_destination_Alwaysservice.wsdl	surfing_destination_AUSservice.wsdl	surfing_destination_service.wsdl	surfing_destination_SOHservice.wsdl	