surfingorganization_city_service.wsdl	hikingsurfing_city_service.wsdl	surfinghiking_city_service.wsdl	surfinghiking_city_SFservice.wsdl	surfinggeneric-agent_city_service.wsdl	surfingorganization_destination_Bestservice.wsdl	surfingorganization_destination_SAARservice.wsdl	surfingorganization_destination_service.wsdl	surfingorganization_destination_SODservice.wsdl	surfingorganizationperson_destination_service.wsdl	activity_city_service.wsdl	sightseeing_city_service.wsdl	getUSZipCodeLocation.wsdl	getLocationOfCityState.wsdl	learning-centred-organizationsurfing_destination_service.wsdl	getListOfMatchingCities.wsdl	getLocationOfUSCity.wsdl	citycity_map_service.wsdl	getDistanceBetweenCitiesWorldwide.wsdl	citycountryduration__HotelReserveservice.wsdl	