surfinghiking_ruralarea_service.wsdl	surfing_ruralarea_service.wsdl	hiking_ruralarea_service.wsdl	activity_ruralarea_service.wsdl	adventure_ruralarea_service.wsdl	sports_ruralarea_service.wsdl	hiking_urbanarea_service.wsdl	activity_urbanarea_service.wsdl	adventure_urbanarea_service.wsdl	flip_slider.wsdl	nationalgovernment_physical-quantityscholarshiplandarea_service.wsdl	getLocationOfCityState.wsdl	hikingsurfing_city_service.wsdl	surfinghiking_city_service.wsdl	surfinghiking_city_SFservice.wsdl	surfinghiking_destination_DFGservice.wsdl	surfinghiking_destination_PDSservice.wsdl	surfinghiking_destination_PFservice.wsdl	surfinghiking_destination_service.wsdl	surfinghiking_town_service.wsdl	