surfinghiking_destination_DFGservice.wsdl	surfinghiking_destination_PDSservice.wsdl	surfinghiking_destination_PFservice.wsdl	surfinghiking_destination_service.wsdl	surfing_destination_Alwaysservice.wsdl	surfing_destination_AUSservice.wsdl	surfing_destination_service.wsdl	surfing_destination_SOHservice.wsdl	surfingorganization_destination_Bestservice.wsdl	surfingorganization_destination_SAARservice.wsdl	surfingorganization_destination_service.wsdl	surfingorganization_destination_SODservice.wsdl	legal-agentsurfing_destination_service.wsdl	surfinggeneric-agent_destination_service.wsdl	surfingorganizationperson_destination_service.wsdl	learning-centred-organizationsurfing_destination_service.wsdl	__destination_MyOfficeservice.wsdl	hiking_destination_service.wsdl	organizationhiking_destination_service.wsdl	activity_destination_service.wsdl	