title_obtainablevideomedia_service.wsdl	title_videomediaMM_service.wsdl	title_videomedia_service.wsdl	title_videomediapricequality_service.wsdl	title_videomediarecommendedprice_service.wsdl	title_videomediamaxpricequality_service.wsdl	title_videomediarecommendedpricequality_service.wsdl	title_videomediataxedpricequality_service.wsdl	title_videomediataxfreepricequality_service.wsdl	_videomediaBBC_service.wsdl	_videomediaSaturn_service.wsdl	_videomediaSmithLee_service.wsdl	linguisticexpression_videomedia_service.wsdl	_filmvideomediaDiscoveryChannel_service.wsdl	shoppingmall_maxpricedigital-video_service.wsdl	geopolitical-entityrecorded-video_activityhotel_service.wsdl	title_media_service.wsdl	title_mediapricequality_service.wsdl	title_mediamaxpricequality_service.wsdl	title_mediarecommendedpricequality_service.wsdl	