TitleSaving_service.wsdl	BookFinder.wsdl	BookSearchService.wsdl	title_filmActionComedy_service.wsdl	title_filmP2P_service.wsdl	title_film_service.wsdl	title_media_service.wsdl	title_vhs_service.wsdl	title_videomediaMM_service.wsdl	title_videomedia_service.wsdl	title_actionfilm_service.wsdl	title_comedyfilm_BFservice.wsdl	title_comedyfilm_Megaservice.wsdl	title_comedyfilm_service.wsdl	title_pricebook_service.wsdl	title_vhsdvd_service.wsdl	title_obtainablevideomedia_service.wsdl	title_mediapricequality_service.wsdl	title_cdpricesoftwareStreaming_service.wsdl	title_filmpricequality_service.wsdl	