title_comedyfilm_BFservice.wsdl	title_comedyfilm_Megaservice.wsdl	title_comedyfilm_service.wsdl	title_lowcomedyfilm_service.wsdl	title_comedyfilmpricequality_service.wsdl	title_highcomedyfilmreport_service.wsdl	title_comedyfilmmaxpricequality_service.wsdl	title_comedyfilmrecommendedpricequality_service.wsdl	title_comedyfilmtaxedpricequality_service.wsdl	title_comedyfilmtaxfreepricequality_service.wsdl	_comedyfilmactionfilm_service.wsdl	_comedyfilmfantacyfilm_service.wsdl	title_filmActionComedy_service.wsdl	title_filmP2P_service.wsdl	title_film_service.wsdl	title_actionfilm_service.wsdl	title_filmpricequality_service.wsdl	title_actionfilmpricequality_service.wsdl	title_filmmaxpricequality_service.wsdl	title_filmrecommendedpricequality_service.wsdl	