university_academic-support-staff_service.wsdl	academic_address_service.wsdl	academic-degree_funding_GermanGovservice.wsdl	academic-degree_lending_GermanGovservice.wsdl	academic-degree_scholarship_GermanGovservice.wsdl	academic-item-number_book_service.wsdl	academic-item-number_publication_service.wsdl	AcademicBookNumberSearch.wsdl	academic-degreegovernment_funding_service.wsdl	academic-degreegovernment_lending_service.wsdl	academic-degreegovernment_scholarship_service.wsdl	academic_postal-address_service.wsdl	academic-degreegovernment_unilateralgiving_service.wsdl	academic-degreegovernmentorganization_funding_service.wsdl	academic-degreegovernmentorganization_lending_service.wsdl	academic-degree_fundingduration_GermanGovservice.wsdl	academic-degree_lendingduration_GermanGovservice.wsdl	academic-degree_scholarshipduration_GermanGovservice.wsdl	academic-item-number_bookauthor_service.wsdl	academic-item-number_publicationauthor_service.wsdl	