userbook_price_service.wsdl	sciencefictionbookuser_price_service.wsdl	bookusercreditcardaccount__service.wsdl	user_price_ShoppingStatusservice.wsdl	EBookOrder1.wsdl	EBookOrder2.wsdl	EBookOrder3.wsdl	fantansynoveluser_price_service.wsdl	userRomanticnovel_price_service.wsdl	DeoSFN_price_service.wsdl	userscience-fiction-novel_price_Bestservice.wsdl	userscience-fiction-novel_price_service.wsdl	userscience-fiction-novel_Relprice_service.wsdl	SFNRecommendedPrice_service.wsdl	science-fiction-noveluser_recommendedpriceindollar_service.wsdl	ScienceFNovelReview_service.wsdl	SFNovelReview_service.wsdl	author_bookprice_service.wsdl	title_pricebook_service.wsdl	book_pricesizebook-type_service.wsdl	