diagnostic	process	organization	diagnostic	process	diagnostic	process	organization	organization	diagnostic	process	organization	diagnostic	organization	process	diagnostic	process	organization	diagnostic	organization	process	diagnostic	organization	process	diagnostic	organization	process	diagnostic	process	organization	diagnostic	process	organization	diagnostic	process	organization	