position	proposition	motion	position	proposition	position	proposition	motion	motion	position	proposition	motion	position	proposition	motion	position	proposition	motion	position	proposition	motion	position	proposition	motion	position	proposition	motion	position	proposition	motion	position	proposition	motion	position	proposition	motion	