lending	government	government	academic	degree	academic	degree	lending	lending	lending	academic	government	degree	lending	lending	academic	government	degree	lending	academic	government	degree	lending	academic	government	degree	lending	lending	lending	lending	