publication	max	price	publication	publication	max	price	max	price	publication	max	price	author	author	author	max	price	publication	publication	max	price	author	max	price	publication	author	max	price	publication	author	max	price	publication	publication	max	price	publication	max	price	publication	max	price	