monograph	recommend	price	author	author	monograph	recommend	price	monograph	monograph	recommend	price	recommend	price	author	recommend	monograph	price	monograph	recommend	price	author	recommend	monograph	price	author	recommend	monograph	price	author	recommend	monograph	price	monograph	recommend	price	monograph	recommend	price	monograph	recommend	price	