price	max	person	bicycle	person	bicycle	auto	auto	price	max	max	price	max	price	auto	bicycle	person	price	max	price	max	auto	bicycle	person	price	max	auto	bicycle	person	price	max	auto	bicycle	person	price	max	price	max	price	max	price	max	