lending	duration	lending	lending	duration	duration	lending	duration	award	award	award	duration	lending	lending	duration	award	duration	lending	award	duration	lending	award	duration	lending	lending	duration	lending	duration	lending	duration	