price	physical	quantity	beverage	beverage	price	physical	quantity	price	price	physical	quantity	physical	quantity	beverage	physical	price	quantity	price	physical	quantity	beverage	physical	price	quantity	beverage	physical	price	quantity	beverage	physical	price	quantity	price	physical	quantity	price	physical	quantity	price	physical	quantity	