price	quantity	beverage	beverage	price	quantity	price	price	quantity	quantity	beverage	price	quantity	price	quantity	beverage	price	quantity	beverage	price	quantity	beverage	price	quantity	price	quantity	price	quantity	price	quantity	