parameter	lat	geo	geo	geo	geo	geo	geo	geo	geo	geo	geo	distance	spherical	law	cosine	parameter	distance	spherical	law	cosine	parameter	parameter	distance	spherical	law	cosine	lat	lat	lat	distance	spherical	law	cosine	distance	spherical	law	cosine	lat	lat	lat	lat	distance	spherical	law	cosine	lat	distance	spherical	law	cosine	lat	distance	spherical	law	cosine	lat	distance	spherical	law	cosine	lat	lat	lat	lat	lat	distance	spherical	law	cosine	distance	spherical	law	cosine	distance	spherical	law	cosine	lat	distance	spherical	law	cosine	distance	spherical	law	cosine	distance	spherical	law	cosine	lat	distance	spherical	law	cosine	distance	spherical	law	cosine	distance	spherical	law	cosine	