check	equipment	availability	availability	treatment	treatment	treatment	treatment	date	time	date	time	treatment	treatment	check	equipment	availability	availability	availability	availability	equipment	availability	check	check	equipment	availability	availability	equipment	availability	check	equipment	availability	check	equipment	availability	check	check	equipment	availability	availability	check	equipment	availability	availability	check	equipment	availability	availability	