check	personnel	availability	availability	treatment	treatment	treatment	treatment	date	time	date	time	check	personnel	availability	availability	availability	availability	personnel	availability	check	check	personnel	availability	availability	personnel	availability	check	personnel	availability	check	personnel	availability	check	check	personnel	availability	availability	check	personnel	availability	availability	check	personnel	availability	availability	