occupation	skill	skill	occupation	skill	occupation	occupation	skill	country	country	country	occupation	skill	occupation	skill	country	occupation	skill	country	occupation	skill	country	occupation	skill	occupation	skill	occupation	skill	occupation	skill	