profession	duration	time	country	country	profession	duration	time	profession	profession	time	duration	time	duration	country	profession	duration	time	profession	duration	time	country	profession	duration	time	country	profession	duration	time	country	profession	duration	time	profession	duration	time	profession	duration	time	profession	duration	time	