occupation	skill	measure	time	country	country	occupation	skill	measure	time	skill	occupation	skill	occupation	time	measure	time	measure	country	occupation	measure	skill	time	occupation	skill	measure	time	country	occupation	measure	skill	time	country	occupation	measure	skill	time	country	occupation	measure	skill	time	occupation	skill	measure	time	occupation	skill	measure	time	occupation	skill	measure	time	