hotel	hotel	hotel	hotel	city	city	country	country	duration	duration	country	city	duration	hotel	hotel	country	city	duration	hotel	country	city	duration	hotel	country	city	duration	hotel	hotel	hotel	hotel	