accommodation	accommodation	accommodation	accommodation	city	city	geopolitical	entity	geopolitical	entity	duration	duration	geopolitical	duration	city	entity	accommodation	accommodation	geopolitical	duration	city	entity	accommodation	geopolitical	duration	city	entity	accommodation	geopolitical	duration	city	entity	accommodation	accommodation	accommodation	accommodation	