meta	carta	finder	version	default	error	message	usage	requestor	parameter	query	string	geometry	feature	width	integer	height	gazetteer	lookup	list	location	version	version	version	query	default	usage	query	string	geometry	default	usage	geometry	width	default	usage	width	image	output	height	default	integer	usage	height	image	output	meta	carta	location	finder	meta	carta	location	finder	meta	carta	location	finder	meta	carta	location	finder	meta	carta	location	finder	meta	carta	location	finder	meta	carta	location	finder	meta	carta	location	finder	meta	carta	location	finder	location	query	parameter	location	