company	occupation	skill	company	company	skill	occupation	skill	occupation	company	occupation	skill	geographical	region	geographical	region	geographical	region	occupation	skill	company	company	occupation	skill	geographical	region	occupation	skill	company	geographical	region	occupation	skill	company	geographical	region	occupation	skill	company	company	occupation	skill	company	occupation	skill	company	occupation	skill	