corporation	occupation	skill	geographical	region	geographical	region	corporation	occupation	skill	corporation	corporation	skill	occupation	skill	occupation	geographical	region	occupation	skill	corporation	corporation	occupation	skill	geographical	region	occupation	skill	corporation	geographical	region	occupation	skill	corporation	geographical	region	occupation	skill	corporation	corporation	occupation	skill	corporation	occupation	skill	corporation	occupation	skill	