occupation	skill	skill	occupation	skill	occupation	occupation	skill	geopolitical	entity	geopolitical	entity	geopolitical	entity	occupation	skill	occupation	skill	geopolitical	entity	occupation	skill	geopolitical	entity	occupation	skill	geopolitical	entity	occupation	skill	occupation	skill	occupation	skill	occupation	skill	