geo	srtm3	lat	point	lng	longitude	parameter	text	type	radar	system	onboard	mission	dataset	land	area	degree	degree	web	meter	grid	lat	lat	lng	point	output	output	geo	srtm3	geo	srtm3	geo	srtm3	geo	srtm3	geo	srtm3	geo	srtm3	geo	srtm3	geo	srtm3	geo	srtm3	elevation	point	