city	geocoder	state	code	character	center	area	city	city	city	state	code	state	code	city	city	code	geocoder	city	code	geocoder	city	code	geocoder	city	code	geocoder	city	code	geocoder	city	code	geocoder	city	code	geocoder	city	code	geocoder	city	code	geocoder	city	code	geocoder	city	code	geocoder	city	code	geocoder	location	city	city	state	code	