funding	funding	funding	funding	weapon	weapon	missile	missile	government	government	weapon	government	missile	funding	funding	weapon	government	missile	funding	weapon	government	missile	funding	weapon	government	missile	funding	funding	funding	funding	