butter	sell	butter	butter	sell	sell	butter	sell	grocery	store	grocery	store	grocery	store	butter	sell	butter	sell	grocery	store	butter	sell	grocery	store	butter	sell	grocery	store	butter	sell	butter	sell	butter	sell	butter	sell	