butter	quantity	butter	butter	quantity	quantity	butter	quantity	grocery	store	grocery	store	grocery	store	butter	quantity	butter	quantity	grocery	store	butter	quantity	grocery	store	butter	quantity	grocery	store	butter	quantity	butter	quantity	butter	quantity	butter	quantity	