diagnostic	process	time	duration	diagnostic	process	diagnostic	process	time	duration	time	duration	diagnostic	process	time	duration	hospital	hospital	hospital	diagnostic	time	process	duration	diagnostic	process	time	duration	hospital	diagnostic	time	process	duration	hospital	diagnostic	time	process	duration	hospital	diagnostic	time	process	duration	diagnostic	process	time	duration	diagnostic	process	time	duration	diagnostic	process	time	duration	