summary	diagnostic	process	hospital	hospital	summary	diagnostic	process	summary	summary	diagnostic	process	diagnostic	process	hospital	diagnostic	process	summary	summary	diagnostic	process	hospital	diagnostic	process	summary	hospital	diagnostic	process	summary	hospital	diagnostic	process	summary	summary	diagnostic	process	summary	diagnostic	process	summary	diagnostic	process	