send	ema	phone	ema	phone	phone	telephone	phone	telephone	send	ema	phone	ema	phone	gps	position	gps	position	phone	ema	send	send	ema	phone	ema	phone	phone	ema	send	phone	ema	send	phone	ema	send	send	ema	phone	ema	phone	send	ema	phone	ema	phone	send	ema	phone	ema	phone	