price	physical	quantity	meat	meat	price	physical	quantity	price	price	physical	quantity	physical	quantity	meat	physical	price	quantity	price	physical	quantity	meat	physical	price	quantity	meat	physical	price	quantity	meat	physical	price	quantity	price	physical	quantity	price	physical	quantity	price	physical	quantity	