slr	price	slr	slr	price	price	slr	price	mercantile	organization	mercantile	organization	organization	mercantile	slr	price	slr	price	organization	mercantile	slr	price	organization	mercantile	slr	price	organization	mercantile	slr	price	slr	price	slr	price	slr	price	