dollar	price	tax	tax	price	dollar	tax	price	dollar	dollar	price	tax	prepare	food	prepare	food	prepare	food	dollar	price	tax	dollar	price	tax	prepare	food	dollar	price	tax	prepare	food	dollar	price	tax	prepare	food	dollar	price	tax	dollar	price	tax	dollar	price	tax	dollar	price	tax	