whiskey	coffee	whiskey	whiskey	coffee	coffee	whiskey	coffee	price	price	price	coffee	whiskey	whiskey	coffee	price	coffee	whiskey	price	coffee	whiskey	price	coffee	whiskey	whiskey	coffee	whiskey	coffee	whiskey	coffee	