coffee	whiskey	measure	time	price	price	coffee	whiskey	measure	time	coffee	coffee	whiskey	whiskey	time	measure	time	measure	price	measure	coffee	time	whiskey	coffee	whiskey	measure	time	price	measure	coffee	time	whiskey	price	measure	coffee	time	whiskey	price	measure	coffee	time	whiskey	coffee	whiskey	measure	time	coffee	whiskey	measure	time	coffee	whiskey	measure	time	