coffee	whiskey	symbolic	quality	coffee	coffee	whiskey	whiskey	symbolic	symbolic	quality	quality	coffee	whiskey	symbolic	quality	recommend	price	recommend	price	recommend	price	coffee	whiskey	symbolic	quality	coffee	whiskey	symbolic	quality	recommend	price	coffee	whiskey	symbolic	quality	recommend	price	coffee	whiskey	symbolic	quality	recommend	price	coffee	whiskey	symbolic	quality	coffee	whiskey	symbolic	quality	coffee	whiskey	symbolic	quality	coffee	whiskey	symbolic	quality	