coffee	whiskey	recommend	price	euro	recommend	price	euro	coffee	whiskey	coffee	coffee	whiskey	whiskey	euro	price	recommend	coffee	whiskey	coffee	whiskey	euro	price	recommend	coffee	whiskey	euro	price	recommend	coffee	whiskey	euro	price	recommend	coffee	whiskey	coffee	whiskey	coffee	whiskey	coffee	whiskey	