author	tax	price	science	fiction	science	fiction	author	tax	price	author	author	tax	price	tax	price	science	fiction	author	tax	price	author	tax	price	science	fiction	author	tax	price	science	fiction	author	tax	price	science	fiction	author	tax	price	author	tax	price	author	tax	price	author	tax	price	