hotel	hotel	hotel	hotel	city	city	geopolitical	entity	geopolitical	entity	time	measure	time	measure	time	geopolitical	measure	city	entity	hotel	hotel	time	geopolitical	measure	city	entity	hotel	time	geopolitical	measure	city	entity	hotel	time	geopolitical	measure	city	entity	hotel	hotel	hotel	hotel	