fiction	film	science	max	price	quality	science	fiction	film	science	fiction	film	max	price	max	price	quality	quality	fiction	film	science	max	price	quality	title	title	title	fiction	max	film	quality	price	science	fiction	film	science	max	price	quality	title	fiction	max	film	quality	price	science	title	fiction	max	film	quality	price	science	title	fiction	max	film	quality	price	science	fiction	film	science	max	price	quality	fiction	film	science	max	price	quality	fiction	film	science	max	price	quality	