medium	price	recommend	quality	medium	medium	recommend	price	recommend	price	quality	quality	medium	price	recommend	quality	title	title	title	price	recommend	quality	medium	price	recommend	quality	title	price	recommend	quality	title	price	recommend	quality	title	price	recommend	quality	medium	price	recommend	quality	medium	price	recommend	quality	medium	price	recommend	quality	