film	tax	price	quality	title	title	film	tax	price	quality	film	film	tax	price	tax	price	quality	quality	title	tax	film	quality	price	film	tax	price	quality	title	tax	film	quality	price	title	tax	film	quality	price	title	tax	film	quality	price	film	tax	price	quality	film	tax	price	quality	film	tax	price	quality	