price	price	price	price	person	bicycle	person	bicycle	wheel	car	wheel	car	car	wheel	bicycle	person	price	price	car	wheel	bicycle	person	price	car	wheel	bicycle	person	price	car	wheel	bicycle	person	price	price	price	price	