price	max	person	bicycle	person	bicycle	wheel	car	wheel	car	price	max	max	price	max	price	car	wheel	bicycle	person	price	max	price	max	car	wheel	bicycle	person	price	max	car	wheel	bicycle	person	price	max	car	wheel	bicycle	person	price	max	price	max	price	max	price	max	