publication	recommend	price	publication	publication	recommend	price	recommend	price	publication	recommend	price	author	author	author	recommend	price	publication	publication	recommend	price	author	recommend	price	publication	author	recommend	price	publication	author	recommend	price	publication	publication	recommend	price	publication	recommend	price	publication	recommend	price	