fiction	book	science	max	price	author	author	fiction	book	science	max	price	science	fiction	book	science	fiction	book	max	price	max	price	author	max	fiction	book	price	science	fiction	book	science	max	price	author	max	fiction	book	price	science	author	max	fiction	book	price	science	author	max	fiction	book	price	science	fiction	book	science	max	price	fiction	book	science	max	price	fiction	book	science	max	price	