free	price	tax	physical	quantity	beverage	beverage	free	price	tax	physical	quantity	tax	free	price	tax	free	price	physical	quantity	physical	quantity	beverage	physical	free	price	tax	quantity	free	price	tax	physical	quantity	beverage	physical	free	price	tax	quantity	beverage	physical	free	price	tax	quantity	beverage	physical	free	price	tax	quantity	free	price	tax	physical	quantity	free	price	tax	physical	quantity	free	price	tax	physical	quantity	