price	tax	physical	quantity	tax	price	tax	price	physical	quantity	physical	quantity	price	tax	physical	quantity	beverage	beverage	beverage	physical	price	tax	quantity	price	tax	physical	quantity	beverage	physical	price	tax	quantity	beverage	physical	price	tax	quantity	beverage	physical	price	tax	quantity	price	tax	physical	quantity	price	tax	physical	quantity	price	tax	physical	quantity	