price	year	price	price	year	year	price	year	car	car	bicycle	bicycle	bicycle	car	year	price	price	year	bicycle	car	year	price	bicycle	car	year	price	bicycle	car	year	price	price	year	price	year	price	year	