diagnostic	process	time	duration	care	organization	care	organization	diagnostic	process	time	duration	diagnostic	process	diagnostic	process	time	duration	time	duration	care	organization	diagnostic	time	process	duration	diagnostic	process	time	duration	care	organization	diagnostic	time	process	duration	care	organization	diagnostic	time	process	duration	care	organization	diagnostic	time	process	duration	diagnostic	process	time	duration	diagnostic	process	time	duration	diagnostic	process	time	duration	