occupation	skill	skill	occupation	skill	occupation	occupation	skill	country	country	city	city	city	country	occupation	skill	occupation	skill	city	country	occupation	skill	city	country	occupation	skill	city	country	occupation	skill	occupation	skill	occupation	skill	occupation	skill	