hotel	luxury	city	city	country	country	hotel	luxury	luxury	hotel	luxury	hotel	country	city	hotel	luxury	hotel	luxury	country	city	hotel	luxury	country	city	hotel	luxury	country	city	hotel	luxury	hotel	luxury	hotel	luxury	hotel	luxury	