occupation	skill	position	part	time	country	country	occupation	skill	position	part	time	skill	occupation	skill	occupation	part	time	position	part	time	position	country	occupation	position	part	skill	time	occupation	skill	position	part	time	country	occupation	position	part	skill	time	country	occupation	position	part	skill	time	country	occupation	position	part	skill	time	occupation	skill	position	part	time	occupation	skill	position	part	time	occupation	skill	position	part	time	