occupational	trade	duration	time	country	country	occupational	trade	duration	time	occupational	trade	occupational	trade	time	duration	time	duration	country	duration	occupational	trade	time	occupational	trade	duration	time	country	duration	occupational	trade	time	country	duration	occupational	trade	time	country	duration	occupational	trade	time	occupational	trade	duration	time	occupational	trade	duration	time	occupational	trade	duration	time	