hotel	hotel	hotel	hotel	city	city	geopolitical	entity	geopolitical	entity	duration	duration	geopolitical	duration	city	entity	hotel	hotel	geopolitical	duration	city	entity	hotel	geopolitical	duration	city	entity	hotel	geopolitical	duration	city	entity	hotel	hotel	hotel	hotel	