technology	expensive	car	expensive	car	technology	technology	technology	car	expensive	technology	technology	car	expensive	technology	car	expensive	technology	car	expensive	technology	technology	technology	technology	