geo	postal	place	query	default	string	parameter	style	medium	verbosity	row	document	return	list	xml	zip	zip	area	zip	centroid	centroid	code	code	postalcode	postal	code	postalcode	postal	code	place	country	country	country	code	country	country	place	placename	place	placename	place	code	country	code	parameter	style	default	row	row	default	geo	postal	code	geo	postal	code	geo	postal	code	geo	postal	code	geo	postal	code	geo	postal	code	geo	postal	code	geo	postal	code	geo	postal	code	code	place	query	document	code	code	code	country	code	