slider	cup	ultra	sound	sensor	contact	sensor	carriage	carriage	spatial	zone	slider	slider	cup	cup	ultra	sound	sensor	ultra	sound	sensor	contact	sensor	contact	sensor	carriage	carriage	spatial	zone	spatial	zone	slider	cup	ultra	sound	sensor	contact	sensor	carriage	carriage	spatial	zone	messe	modul	messe	modul	slider	slider	cup	ultra	sound	sensor	contact	sensor	carriage	carriage	spatial	zone	slider	slider	slider	slider	cup	ultra	sound	sensor	contact	sensor	carriage	carriage	spatial	zone	slider	cup	ultra	sound	sensor	contact	sensor	carriage	carriage	spatial	zone	slider	cup	ultra	sound	sensor	contact	sensor	carriage	carriage	spatial	zone	