max	price	quantity	max	price	max	price	quantity	quantity	max	price	quantity	food	food	food	max	price	quantity	max	price	quantity	food	max	price	quantity	food	max	price	quantity	food	max	price	quantity	max	price	quantity	max	price	quantity	max	price	quantity	