price	physical	quantity	food	food	price	physical	quantity	price	price	physical	quantity	physical	quantity	food	physical	price	quantity	price	physical	quantity	food	physical	price	quantity	food	physical	price	quantity	food	physical	price	quantity	price	physical	quantity	price	physical	quantity	price	physical	quantity	