price	quantity	price	price	quantity	quantity	price	quantity	food	food	food	price	quantity	price	quantity	food	price	quantity	food	price	quantity	food	price	quantity	price	quantity	price	quantity	price	quantity	