price	tax	physical	quantity	food	food	price	tax	physical	quantity	tax	price	tax	price	physical	quantity	physical	quantity	food	physical	price	tax	quantity	price	tax	physical	quantity	food	physical	price	tax	quantity	food	physical	price	tax	quantity	food	physical	price	tax	quantity	price	tax	physical	quantity	price	tax	physical	quantity	price	tax	physical	quantity	