profession	time	position	full	profession	profession	full	time	position	full	time	position	profession	time	position	full	geopolitical	entity	geopolitical	entity	geopolitical	entity	profession	time	position	full	profession	time	position	full	geopolitical	entity	profession	time	position	full	geopolitical	entity	profession	time	position	full	geopolitical	entity	profession	time	position	full	profession	time	position	full	profession	time	position	full	profession	time	position	full	