sandwich	quantity	sandwich	sandwich	quantity	quantity	sandwich	quantity	grocery	store	grocery	store	grocery	store	sandwich	quantity	sandwich	quantity	grocery	store	sandwich	quantity	grocery	store	sandwich	quantity	grocery	store	sandwich	quantity	sandwich	quantity	sandwich	quantity	sandwich	quantity	