food	quantity	food	food	quantity	quantity	food	quantity	grocery	store	grocery	store	grocery	store	food	quantity	food	quantity	grocery	store	food	quantity	grocery	store	food	quantity	grocery	store	food	quantity	food	quantity	food	quantity	food	quantity	