patient	authorize	medical	record	medical	record	date	patient	medical	record	acknowledgement	medical	record	medical	record	acknowledgement	acknowledgement	patient	medical	record	authorize	medical	record	date	patient	medical	record	acknowledgement	date	time	date	time	treatment	treatment	gps	position	gps	position	health	insurance	health	insurance	account	password	account	password	physician	id	physician	id	medical	patient	record	patient	medical	record	authorize	medical	record	date	patient	medical	record	acknowledgement	medical	patient	record	medical	patient	record	medical	patient	record	patient	medical	record	authorize	medical	record	date	patient	medical	record	acknowledgement	patient	medical	record	authorize	medical	record	date	patient	medical	record	acknowledgement	patient	medical	record	authorize	medical	record	date	patient	medical	record	acknowledgement	