publication	author	isbn	isbn	publication	author	publication	publication	author	author	isbn	publication	author	publication	author	isbn	publication	author	isbn	publication	author	isbn	publication	author	publication	author	publication	author	publication	author	