funding	range	funding	funding	range	range	funding	range	government	organization	government	organization	missile	missile	organization	government	missile	funding	range	funding	range	organization	government	missile	funding	range	organization	government	missile	funding	range	organization	government	missile	funding	range	funding	range	funding	range	funding	range	