dollar	price	tax	price	tax	price	dollar	tax	price	dollar	price	price	dollar	price	tax	price	prepare	food	prepare	food	prepare	food	dollar	price	tax	dollar	price	tax	price	prepare	food	dollar	price	tax	prepare	food	dollar	price	tax	prepare	food	dollar	price	tax	dollar	price	tax	price	dollar	price	tax	price	dollar	price	tax	price	