coffee	whiskey	price	price	coffee	whiskey	coffee	whiskey	coffee	whiskey	price	coffee	whiskey	coffee	whiskey	price	coffee	whiskey	price	coffee	whiskey	price	coffee	whiskey	coffee	whiskey	coffee	whiskey	coffee	whiskey	