occupation	skill	skill	occupation	skill	occupation	occupation	skill	country	country	public	company	public	company	public	country	company	occupation	skill	occupation	skill	public	country	company	occupation	skill	public	country	company	occupation	skill	public	country	company	occupation	skill	occupation	skill	occupation	skill	occupation	skill	