book	author	publisher	publish	publication	publication	book	author	publisher	publish	book	book	author	author	publisher	publish	publisher	publish	publication	author	publisher	book	publish	book	author	publisher	publish	publication	author	publisher	book	publish	publication	author	publisher	book	publish	publication	author	publisher	book	publish	book	author	publisher	publish	book	author	publisher	publish	book	author	publisher	publish	