prepare	food	retail	store	retail	store	prepare	food	prepare	food	prepare	food	retail	store	prepare	food	prepare	food	retail	store	prepare	food	retail	store	prepare	food	retail	store	prepare	food	prepare	food	prepare	food	prepare	food	