accommodation	accommodation	accommodation	accommodation	city	city	geopolitical	entity	geopolitical	entity	time	measure	time	measure	time	geopolitical	measure	city	entity	accommodation	accommodation	time	geopolitical	measure	city	entity	accommodation	time	geopolitical	measure	city	entity	accommodation	time	geopolitical	measure	city	entity	accommodation	accommodation	accommodation	accommodation	