medium	price	quality	title	title	medium	price	quality	medium	medium	price	price	quality	quality	title	price	quality	medium	price	quality	title	price	quality	title	price	quality	title	price	quality	medium	price	quality	medium	price	quality	medium	price	quality	