geocodeUSAddress.wsdl	3
getLocationOfAddress.wsdl	3
getLocationOfAddressWorldwide.wsdl	3
getLocationOfAddressYahooMaps.wsdl	3
googleGeocodingAPI.wsdl	3
getMapOfAddress.wsdl	3
searchFormattedAddress.wsdl	3
getPlaceOfAddress.wsdl	3
getCoordinatesOfAddress.wsdl	3
addressGeocoder.wsdl	3
checkAndLookupAddress.wsdl	3
getLocationOfCityWorldwide.wsdl	2
getZipCodeLocation.wsdl	2
getUSZipCodeLocation.wsdl	2
getLocationOfZipCodeWorldwide.wsdl	2
searchRawAddress.wsdl	2
gazetteerLookupLocation.wsdl	2
queryParserLocation.wsdl	2
real-time_geocodingStreetAddress.wsdl	2
real-time_geocoding.wsdl	2
findPlaceNamePostalCode.wsdl	1
getGeographicAreaOfZipCode.wsdl	1
getZipCodeInfoWorldwide.wsdl	1
findNearbyPostalCodes.wsdl	0
findNearbyWikipediaArticles.wsdl	0
getElevationFromLocation.wsdl	0
getDistanceBetweenLocations.wsdl	0
getATMLocationsInCity.wsdl	0
getZipCodesWithinCityState.wsdl	0
getZipCodeInfo.wsdl	0
getDistanceBetweenPlaces.wsdl	0
getAddressOfLocation.wsdl	0
uszipcode_distance.wsdl	0
calculatorDistanceSphericalLawOfCosines.wsdl	0
calculateSunriseTime.wsdl	0
calculateDistanceInMiles.wsdl	0
city_state_ZipCodes.wsdl	0
getSunsetAndSunriseTime.wsdl	0
getListOfMatchingCities.wsdl	0
getSunsetSunriseTwilightTime.wsdl	0
getAltitudeOfLocation.wsdl	0
calculateDistanceUsingSphericalGeometry.wsdl	0
usPostalCode_distance.wsdl	0
googleStaticMapsAPI.wsdl	0
renderMapService.wsdl	0
staticMapsDisplay.wsdl	0
objectsMappingService.wsdl	0
getDrivingDirections.wsdl	0
getTrafficInformation.wsdl	0
getPopulationDensityOfLocation.wsdl	0
addressDistanceCalculator.wsdl	0
