getDistanceBetweenCitiesWorldwide.wsdl	3
getDistanceBetweenLocations.wsdl	2
getDistanceBetweenPlaces.wsdl	2
uszipcode_distance.wsdl	1
calculatorDistanceSphericalLawOfCosines.wsdl	1
calculateDistanceInMiles.wsdl	1
calculateDistanceUsingSphericalGeometry.wsdl	1
usPostalCode_distance.wsdl	1
addressDistanceCalculator.wsdl	1
_mapGerman_service.wsdl	1
citycity_map_service.wsdl	1
country_map_service.wsdl	1
geographical-region_mapFromFrankfurt_service.wsdl	1
geographical-region_mapToBerlin_service.wsdl	1
geographical-regiongeographical-region_map_Gorgservice.wsdl	1
geographical-regiongeographical-region_map_service.wsdl	1
locationlocation_map_service.wsdl	1
locationlocation_map_SRIservice.wsdl	1
locationlocation_arrowfigure_service.wsdl	1
citycity_arrowfigure_service.wsdl	1
findNearbyPostalCodes.wsdl	0
findNearbyWikipediaArticles.wsdl	0
findPlaceNamePostalCode.wsdl	0
getElevationFromLocation.wsdl	0
getLocationOfAddress.wsdl	0
getLocationOfCityWorldwide.wsdl	0
getZipCodeLocation.wsdl	0
getATMLocationsInCity.wsdl	0
getZipCodesWithinCityState.wsdl	0
getZipCodeInfo.wsdl	0
getAddressOfLocation.wsdl	0
getLocationOfAddressWorldwide.wsdl	0
getUSZipCodeLocation.wsdl	0
getGeographicAreaOfZipCode.wsdl	0
calculateSunriseTime.wsdl	0
city_state_ZipCodes.wsdl	0
getZipCodeInfoWorldwide.wsdl	0
getSunsetAndSunriseTime.wsdl	0
getLocationOfAddressYahooMaps.wsdl	0
getListOfMatchingCities.wsdl	0
getSunsetSunriseTwilightTime.wsdl	0
getAltitudeOfLocation.wsdl	0
getLocationOfZipCodeWorldwide.wsdl	0
googleStaticMapsAPI.wsdl	0
googleGeocodingAPI.wsdl	0
getMapOfAddress.wsdl	0
searchRawAddress.wsdl	0
searchFormattedAddress.wsdl	0
renderMapService.wsdl	0
getPlaceOfAddress.wsdl	0
gazetteerLookupLocation.wsdl	0
queryParserLocation.wsdl	0
staticMapsDisplay.wsdl	0
getCoordinatesOfAddress.wsdl	0
real-time_geocodingStreetAddress.wsdl	0
real-time_geocoding.wsdl	0
objectsMappingService.wsdl	0
getDrivingDirections.wsdl	0
getTrafficInformation.wsdl	0
getPopulationDensityOfLocation.wsdl	0
addressGeocoder.wsdl	0
checkAndLookupAddress.wsdl	0
