getMapOfUSAddress.wsdl	3
getMapOfAddress.wsdl	3
queryParserLocation.wsdl	3
staticMapsDisplay.wsdl	3
gazetteerLookupLocation.wsdl	2
getLocationOfAddress.wsdl	1
getLocationOfAddressWorldwide.wsdl	1
getLocationOfAddressYahooMaps.wsdl	1
googleStaticMapsAPI.wsdl	1
searchFormattedAddress.wsdl	1
renderMapService.wsdl	1
getCoordinatesOfAddress.wsdl	1
real-time_geocodingStreetAddress.wsdl	1
addressGeocoder.wsdl	1
checkAndLookupAddress.wsdl	1
country_map_service.wsdl	1
findNearbyPostalCodes.wsdl	0
findNearbyWikipediaArticles.wsdl	0
findPlaceNamePostalCode.wsdl	0
getElevationFromLocation.wsdl	0
getDistanceBetweenLocations.wsdl	0
getLocationOfCityWorldwide.wsdl	0
getZipCodeLocation.wsdl	0
getATMLocationsInCity.wsdl	0
getZipCodesWithinCityState.wsdl	0
getZipCodeInfo.wsdl	0
getDistanceBetweenPlaces.wsdl	0
getAddressOfLocation.wsdl	0
uszipcode_distance.wsdl	0
getUSZipCodeLocation.wsdl	0
getGeographicAreaOfZipCode.wsdl	0
calculatorDistanceSphericalLawOfCosines.wsdl	0
calculateSunriseTime.wsdl	0
calculateDistanceInMiles.wsdl	0
city_state_ZipCodes.wsdl	0
getZipCodeInfoWorldwide.wsdl	0
getSunsetAndSunriseTime.wsdl	0
getListOfMatchingCities.wsdl	0
getSunsetSunriseTwilightTime.wsdl	0
getAltitudeOfLocation.wsdl	0
calculateDistanceUsingSphericalGeometry.wsdl	0
usPostalCode_distance.wsdl	0
getLocationOfZipCodeWorldwide.wsdl	0
googleGeocodingAPI.wsdl	0
searchRawAddress.wsdl	0
getPlaceOfAddress.wsdl	0
real-time_geocoding.wsdl	0
objectsMappingService.wsdl	0
getDrivingDirections.wsdl	0
getTrafficInformation.wsdl	0
getPopulationDensityOfLocation.wsdl	0
addressDistanceCalculator.wsdl	0
