missilegovernmentorganization_fundingrange_service.wsdl	3
government_funding_Missileservice.wsdl	3
missilegovernment_giving_Borrowservice.wsdl	3
missilegovernment_fundingrange_service.wsdl	3
governmentmissileweapon_funding_service.wsdl	3
governmentmissile_funding_Reliableservice.wsdl	3
missilegovernment_giving_service.wsdl	3
missilegovernment_givingrange_service.wsdl	3
missilegovernmentorganization_funding_service.wsdl	3
governmentorganizationselfpowereddevice_funding_service.wsdl	3
governmentmissileweapon_fundingfunding_service.wsdl	3
missilegovernmentorganization_givingrange_service.wsdl	3
projectilegovernment_funding_service.wsdl	3
governmentmissile_funding_service.wsdl	3
missile_funding_Asianservice.wsdl	2
ballisticmissilegovernment_financingrange_service.wsdl	2
missilegovernmentorganization_financingrange_service.wsdl	2
ballisticmissilegovernmentorganization_fundingrange_service.wsdl	2
ballisticmissilegovernment_lendingrange_service.wsdl	2
ballisticmissilegovernmentorganization_financingrange_service.wsdl	2
weaponmissile_funding_Iraqservice.wsdl	2
missile_financing_Russianservice.wsdl	2
ballisticmissilegovernmentorganization_givingrange_service.wsdl	2
missile_financing_USservice.wsdl	2
missilegovernment_financingrange_service.wsdl	2
missile_financing_Chinaservice.wsdl	2
ballisticmissilegovernment_givingrange_service.wsdl	2
missile_funding_Pakservice.wsdl	2
nationalgovernmentweapon_funding_service.wsdl	2
government_funding_ABombservice.wsdl	2
missile_funding_NKoreaservice.wsdl	2
governmentweapon_funding_service.wsdl	2
missile_funding_Indiaservice.wsdl	2
governmentmissile_financing_service.wsdl	2
government_funding_BallMissileservice.wsdl	2
ballisticmissilegovernment_fundingrange_service.wsdl	2
missilegovernment_lendingrange_service.wsdl	1
ballisticmissilegovernmentorganization_lendingrange_service.wsdl	1
missilegovernmentorganization_lendingrange_service.wsdl	1
governmentorganizationmissile_unilateralgiving_service.wsdl	1
fastcar_yearprice_service.wsdl	0
government_scholarshiporganization_service.wsdl	0
government_lending_service.wsdl	0
governmentdegree_scholarship_service.wsdl	0
organization_diagnosticprocesscost_service.wsdl	0
degreegovernment_unilateralgiving_service.wsdl	0
degree_scholarship_GermanGovservice.wsdl	0
isbn_bookauthor_service.wsdl	0
government_funding_ForPhDservice.wsdl	0
governmentdegree_scholarshipquantity_service.wsdl	0
academic-degreegovernmentorganization_lending_service.wsdl	0
isbn_publicationpublisher_service.wsdl	0
academic-degree_funding_GermanGovservice.wsdl	0
degreegovernmentorganization_scholarship_service.wsdl	0
academic-degreegovernment_lending_service.wsdl	0
governmentdegree_givingback_service.wsdl	0
degreegovernment_funding_service.wsdl	0
degree_scholarshipduration_GermanGovservice.wsdl	0
citygovernment_lending_service.wsdl	0
organization_diagnosticprocess_service.wsdl	0
_mapFrankfurtBerlin_service.wsdl	0
academic-degree_fundingduration_GermanGovservice.wsdl	0
award_funding_GermanGovservice.wsdl	0
academic-degreegovernment_scholarship_service.wsdl	0
awardgovernment_funding_service.wsdl	0
governmentorganization_scholarship_service.wsdl	0
governmentdegree_welfare_service.wsdl	0
academic-degreegovernment_funding_service.wsdl	0
degreegovernment_scholarship_service.wsdl	0
maxprice_whiskeycolabeer_service.wsdl	0
degree_fundingduration_GermanGovservice.wsdl	0
geographical-regiongeographical-region_map_service.wsdl	0
academic-degree_scholarship_GermanGovservice.wsdl	0
expensivecar_yearprice_service.wsdl	0
isbn_publicationauthor_service.wsdl	0
government_welfare_service.wsdl	0
isbn_book_service.wsdl	0
cheapcar_yearprice_service.wsdl	0
degree_funding_GermanGovservice.wsdl	0
linguisticexpression_videomedia_service.wsdl	0
academic-degree_lending_GermanGovservice.wsdl	0
government-organization_profession_service.wsdl	0
academic-degreegovernmentorganization_funding_service.wsdl	0
car_yearprice_service.wsdl	0
degree_lending_GermanGovservice.wsdl	0
nationalgovernment_scholarshipquantityduration_service.wsdl	0
award_scholarshipduration_SwissGovservice.wsdl	0
government-organization_skilledoccupation_service.wsdl	0
governmentdegree_scholarship_TheBestservice.wsdl	0
nationalgovernment_scholarshipquantity_service.wsdl	0
academic-degreegovernmentorganization_unilateralgiving_service.wsdl	0
degreegovernment_lending_service.wsdl	0
nationalgovernment_scholarship_service.wsdl	0
nationalgovernment_physical-quantityscholarshiplandarea_service.wsdl	0
geographical-region_mapToBerlin_service.wsdl	0
award_fundingduration_GermanGovservice.wsdl	0
governmentaward_scholarship_service.wsdl	0
government_scholarship_service.wsdl	0
academic-degreegovernment_unilateralgiving_service.wsdl	0
degreenationalgovernment_scholarship_service.wsdl	0
award_lending_GermanGovservice.wsdl	0
nationalgovernment_lending_service.wsdl	0
