hospital_IIPsummary_service.wsdl	3
hospital_postal-addressinvestigating_service.wsdl	3
hospital_investigatingaddress_service.wsdl	3
careorganization_investigating_service.wsdl	3
hospital_investigating_service.wsdl	3
hospital_diagnosticprocess_service.wsdl	2
questionhospital_diagnosticprocess_service.wsdl	2
careorganization_biopsy_service.wsdl	2
organization_diagnosticprocess_service.wsdl	2
careorganization_experimenting_service.wsdl	2
CAD_medical_service.wsdl	2
hospital_biopsy_service.wsdl	2
medicalclinic_investigating_service.wsdl	2
organization_experimenting_service.wsdl	2
hospital_diagnosticprocesscost_service.wsdl	2
hospital_experimenting_service.wsdl	2
_investigating_Saarservice.wsdl	2
careorganization_diagnosticprocess_service.wsdl	2
careorganization_diagnosticprocesstimeinterval_service.wsdl	2
careorganization_diagnosticprocesstimeduration_service.wsdl	2
careorganization_diagnosticprocesstimemeasure_service.wsdl	2
hospital_diagnosticprocesstimeduration_service.wsdl	2
organization_experimentingtimeduration_service.wsdl	2
HDP2_service.wsdl	2
organization_diagnosticprocesscost_service.wsdl	2
_diagnosticprocessorganization_service.wsdl	2
hospital_diagnosticprocesstimeinterval_service.wsdl	2
hospital_diagnosticprocesstimemeasure_service.wsdl	2
HDP_service.wsdl	2
hospital_diagnosticprocess_MedDiagservice.wsdl	2
medicalclinic_diagnosticprocesstimeduration_service.wsdl	1
medicalclinic_biopsy_service.wsdl	1
medicalclinic_predicting_service.wsdl	1
careorganization_predicting_service.wsdl	1
medicalclinic_investigating_MedService.wsdl	1
medicalclinic_diagnosticprocess_service.wsdl	1
medicalclinic_diagnosticprocesstimemeasure_service.wsdl	1
hospital_predicting_service.wsdl	1
medicalclinic_diagnosticprocesstimeinterval_service.wsdl	1
medicalclinic_experimenting_service.wsdl	1
publication-number_bookauthorpublisher_service.wsdl	0
shoppingmall_cameraprice_service.wsdl	0
retailstore_preparedfood_service.wsdl	0
CCP_service.wsdl	0
_translocation_Chemicalservice.wsdl	0
shoppingmall_calendar-datepricecamera_service.wsdl	0
monograph_author_service.wsdl	0
retailstore_foodquality_service.wsdl	0
shoppingmall_compacttaxedprice_service.wsdl	0
_polling_Germanservice.wsdl	0
Required_preparedfoodquantity_service.wsdl	0
government_funding_ABombservice.wsdl	0
novel_authorbook-type_service.wsdl	0
shoppingmall_pricecellphonewithcamera_service.wsdl	0
government_funding_BallMissileservice.wsdl	0
governmentorganizationmissile_unilateralgiving_service.wsdl	0
_aps-slrpricereport_Musuemservice.wsdl	0
MerkelD_service.wsdl	0
shoppingmall_analogpricecalendar-date_service.wsdl	0
sportsorganization_destination_service.wsdl	0
encyclopedia_author_service.wsdl	0
_medicaldoctor_UNOservice.wsdl	0
preparedfood_taxedprice_service.wsdl	0
shoppingmall_slrprice_service.wsdl	0
SRcamera_service.wsdl	0
governmentorganization_scholarship_service.wsdl	0
locationlocation_arrowfigure_service.wsdl	0
preparedfood_recommendedprice_service.wsdl	0
shoppingmall_digital-slrpricecalendar-date_service.wsdl	0
short-story_authorbook-type_service.wsdl	0
countrycity_sportshotel_service.wsdl	0
mercantileorganization_compactprice_service.wsdl	0
shoppingmall_maxpricedigital-video_service.wsdl	0
missilegovernment_giving_service.wsdl	0
_bankeraddress_CityBankservice.wsdl	0
ballisticmissilegovernment_fundingrange_service.wsdl	0
locationlocation_map_service.wsdl	0
retailstore_apple_service.wsdl	0
science-fiction-novel_authorbook-type_service.wsdl	0
shoppingmall_compactprice_service.wsdl	0
PhillipDigCamera_price_service.wsdl	0
government_funding_Missileservice.wsdl	0
country_skilledoccupation_jobsservice.wsdl	0
Available_preparedfoodquantity_service.wsdl	0
grocerystore_teaprice_service.wsdl	0
corporation_apple_service.wsdl	0
datefruit_price_service.wsdl	0
academic-degreegovernmentorganization_lending_service.wsdl	0
_droughtreport_service.wsdl	0
CheckPersonnelAvailability_service.wsdl	0
encyclopedia_authorbook-type_service.wsdl	0
novel_publisher_service.wsdl	0
projectilegovernment_funding_service.wsdl	0
shoppingmall_pricepurchaseableitemrange_service.wsdl	0
InformHospital_service.wsdl	0
apple_price_service.wsdl	0
government_funding_ForPhDservice.wsdl	0
awardgovernment_funding_service.wsdl	0
PatientTransport_service.wsdl	0
grocerystore_food_service.wsdl	0
book_publisher_service.wsdl	0
_camerataxedpricedutytax_service.wsdl	0
romanticnovel_authorbook-type_service.wsdl	0
sportslegal-agent_destination_service.wsdl	0
shoppingmall_recommendedprice_Shirtservice.wsdl	0
retailstore_preparedfoodquantity_service.wsdl	0
sciencefictionbook_authorbook-type_service.wsdl	0
grocerystore_preparedfoodquantity_service.wsdl	0
mercantileorganization_slrprice_service.wsdl	0
citycountry_skilledoccupation_service.wsdl	0
locationlocation_map_SRIservice.wsdl	0
store_preparedfood_service.wsdl	0
shoppingmall_purchaseableitemprice_service.wsdl	0
wirelessplayerwmaplayer_price_service.wsdl	0
