food_pricephysical-quantity_Aldiservice.wsdl	3
preparedfood_taxedpriceindollarprice_service.wsdl	3
food_pricequantity_Aldiservice.wsdl	3
MerkelD_service.wsdl	3
preparedfood_price_service.wsdl	3
food_price_AnimalFoodservice.wsdl	3
preparedfood_priceday_service.wsdl	3
MarkoPS_service.wsdl	3
preparedfood_taxfreeprice_service.wsdl	2
Ben_service.wsdl	2
ZAD_service.wsdl	2
food_taxfreepricequantity_Aldiservice.wsdl	2
preparedfood_recommendedprice_service.wsdl	2
preparedfood_SpainishTax_service.wsdl	2
food_taxedpricequantity_Aldiservice.wsdl	2
preparedfood_GSprice_service.wsdl	2
MAK_service.wsdl	2
food_maxpricephysical-quantity_Aldiservice.wsdl	2
food_taxfreepricephysical-quantity_Aldiservice.wsdl	2
preparedfood_maxprice_service.wsdl	2
food_taxedpricephysical-quantity_Aldiservice.wsdl	2
preparedfood_taxedprice_service.wsdl	2
SPD-Grune_service.wsdl	2
food_recommendedprice_service.wsdl	2
food_maxpricequantity_service.wsdl	2
food_price_service.wsdl	2
grocerystore_teaprice_service.wsdl	1
breadorbiscuit_recPricetaxedpriceineuro_service.wsdl	1
preparedfood_USTax_service.wsdl	1
user_price_ShoppingStatusservice.wsdl	1
butter_taxedprice_service.wsdl	1
coffeesandwich_price_service.wsdl	1
coffee_taxedprice_service.wsdl	1
sandwich_taxedprice_service.wsdl	1
tea_recommendedprice_service.wsdl	1
meat_pricephysical-quantity_Aldiservice.wsdl	1
meat_pricequantity_Aldiservice.wsdl	1
sandwich_recommendedprice_service.wsdl	1
butter_recommendedprice_service.wsdl	1
grocerystore_preparedfoodprice_service.wsdl	1
sandwich_maxprice_service.wsdl	1
coffee_recommendedprice_service.wsdl	1
butter_maxprice_service.wsdl	1
coffee_maxprice_service.wsdl	1
_price_Fishservice.wsdl	1
food_maxpricequantity_Aldiservice.wsdl	1
cheapcar_yearprice_service.wsdl	0
expensivecar_yearprice_service.wsdl	0
userscience-fiction-novel_price_service.wsdl	0
1personbicycle4wheeledcar_price_service.wsdl	0
bicycleauto_price_service.wsdl	0
Available_preparedfoodquantity_service.wsdl	0
dvdplayermp3player_price_Rservice.wsdl	0
grocerystore_preparedfoodquantity_service.wsdl	0
amount-of-moneyexpensivecar_price_service.wsdl	0
auto_yearprice_service.wsdl	0
book_Cheapestprice_service.wsdl	0
BookPrice.wsdl	0
cdplayermp3player_price_service.wsdl	0
bookperson_price_service.wsdl	0
printedmaterialpersoncreditcardaccount_price_service.wsdl	0
cheapcar2personbicycle_price_service.wsdl	0
mercantileorganization_slrprice_service.wsdl	0
datefruit_price_service.wsdl	0
expensivecar_pricecolor_service.wsdl	0
author_novelprice_service.wsdl	0
rawfood_price_service.wsdl	0
fastcar_yearprice_service.wsdl	0
shoppingmall_digital-slrpricecalendar-date_service.wsdl	0
fastcar_pricecolor_service.wsdl	0
userbook_price_service.wsdl	0
cyclecar_pricetaxedprice_service.wsdl	0
machine_price_service.wsdl	0
1personbicyclecar_price_service.wsdl	0
retailstore_foodquality_service.wsdl	0
_food_Exportservice.wsdl	0
shoppingmall_pricepurchaseableitemrange_service.wsdl	0
expensivecar_price_service.wsdl	0
car_pricereport_service.wsdl	0
autobicycle_price_service.wsdl	0
car_price_service.wsdl	0
dvdplayermp3player_pricemessage_service.wsdl	0
book_authorprice_service.wsdl	0
amount-of-moneycheapcar_price_service.wsdl	0
author_publicationprice_service.wsdl	0
book_price_service.wsdl	0
KodakDigCamera_price_service.wsdl	0
car2personbicycle_price_service.wsdl	0
book_taxedpriceprice_service.wsdl	0
microwaveoven_price_service.wsdl	0
retailstore_preparedfoodquantity_service.wsdl	0
encyclopedia_price_service.wsdl	0
lemonfruit_price_service.wsdl	0
electricdevice_price_service.wsdl	0
auto_pricecolor_service.wsdl	0
3wheeledcar_price_service.wsdl	0
4wheeledcar_yearprice_service.wsdl	0
shoppingmall_purchaseableitemprice_service.wsdl	0
bookpersonOptional_price_service.wsdl	0
4wheeledcarbicycle_price_service.wsdl	0
objectpersoncreditaccount_price_service.wsdl	0
bicyclecar_priceyear_service.wsdl	0
novel_price_service.wsdl	0
sciencefictionbookuser_price_service.wsdl	0
monograph_price_service.wsdl	0
mp3playerportabledvdplayer_price_service.wsdl	0
lenthu_rentcar_service.wsdl	0
pea_price_service.wsdl	0
printedmaterial_price_service.wsdl	0
apple_price_service.wsdl	0
dvdplayermp3player_price_MDservice.wsdl	0
retailstore_preparedfood_service.wsdl	0
dvdplayermp3player_price_service.wsdl	0
shoppingmall_cameraprice_service.wsdl	0
amount-of-moneycar_price_service.wsdl	0
car_pricequality_service.wsdl	0
Required_preparedfoodquantity_service.wsdl	0
shoppingmall_analogpricecalendar-date_service.wsdl	0
book_pricesizebook-type_service.wsdl	0
mediaplayer_price_service.wsdl	0
userscience-fiction-novel_price_Bestservice.wsdl	0
2personbicycle4wheeledcar_price_service.wsdl	0
bookpersoncreditcardaccount_price_service.wsdl	0
agent_price_MianMarktservice.wsdl	0
novelperson_price_service.wsdl	0
beverage_pricequantity_Aldiservice.wsdl	0
cheapcar_price_service.wsdl	0
_price_CannonCameraservice.wsdl	0
car_yearprice_service.wsdl	0
book_pricereviewbook_service.wsdl	0
shoppingmall_pricecellphonewithcamera_service.wsdl	0
retailstore_slrprice_service.wsdl	0
honey_price_service.wsdl	0
cheapcar1personbicycle_price_service.wsdl	0
carcycle_price_service.wsdl	0
cheapcar_pricecolor_service.wsdl	0
author_bookprice_service.wsdl	0
shoppingmall_calendar-datepricecamera_service.wsdl	0
PhillipDigCamera_price_service.wsdl	0
carbicycle_price_service.wsdl	0
mp3playerdvdplayer_priceshipping_service.wsdl	0
grocerystore_food_service.wsdl	0
retailstore_compactprice_service.wsdl	0
auto2personbicycle_price_service.wsdl	0
shoppingmall_slrprice_service.wsdl	0
userRomanticnovel_price_service.wsdl	0
1personbicyclecar_price_TheBestservice.wsdl	0
cheapcar_pricereport_service.wsdl	0
auto_price_service.wsdl	0
mp3playercdplayermicrowaveoven_price_service.wsdl	0
auto1personbicycle_price_service.wsdl	0
mercantileorganization_compactprice_service.wsdl	0
store_preparedfood_Merchantservice.wsdl	0
bicycle4wheeledcar_price_service.wsdl	0
grocerystore_preparedfood_service.wsdl	0
coconut_price_service.wsdl	0
fantansynoveluser_price_service.wsdl	0
author_monographprice_service.wsdl	0
fastcar_pricereport_service.wsdl	0
bicyclecar_price_service.wsdl	0
beverage_pricephysical-quantity_Aldiservice.wsdl	0
shoppingmall_pricedigitalanalog_service.wsdl	0
4wheeledcar_price_service.wsdl	0
4wheeledcar2personbicycle_price_service.wsdl	0
book_authorprice_Novelservice.wsdl	0
wholesalestore_preparedfood_service.wsdl	0
autocycle_price_service.wsdl	0
store_preparedfood_service.wsdl	0
author_sciencefictionbookprice_service.wsdl	0
vehicle_price_service.wsdl	0
wirelessplayerwmaplayer_price_service.wsdl	0
car_priceauto_service.wsdl	0
book_reviewprice_service.wsdl	0
_3WheeledOpelCarPrice_service.wsdl	0
shoppingmall_compactprice_service.wsdl	0
cycle1personbicycle_price_service.wsdl	0
orangefruit_price_service.wsdl	0
car_taxedpriceprice_service.wsdl	0
avocado_price_service.wsdl	0
book_taxedprice_service.wsdl	0
mercantileorganization_food_service.wsdl	0
