price_whiskeycoffee_service.wsdl	3
price_coffeewhiskeyquality_service.wsdl	3
price_coffeewhiskey_service.wsdl	3
price_whiskeycoffee_Zikoservice.wsdl	3
recommendedprice_coffeewhiskeysymbolicstring_service.wsdl	3
recommendedprice_coffeewhiskey_service.wsdl	3
price_coffeewhiskey_Thebestservice.wsdl	3
recommendedprice_coffeewithwhiskeycontentbearingobject_service.wsdl	3
recommendedprice_coffeewhiskey_Bestservice.wsdl	3
price_coffeewhiskeyqualitytimeposition_service.wsdl	3
hotelrecommendedprice_coffeewhiskey_service.wsdl	3
recommendedprice_contentbearingobjectwhiskeycoffee_service.wsdl	3
recommendedpriceindollar_whiskeycoffee_service.wsdl	3
taxfreeprice_whiskeycoffee_service.wsdl	3
price_coffeewhiskeytimemeasure_service.wsdl	3
recommendedpriceineuro_coffeewhiskey_service.wsdl	3
recommendedprice_coffeewhiskeysymbolicstringquality_service.wsdl	3
maxprice_coffeewhiskey_service.wsdl	3
recommendedprice_irishcoffeetasting_service.wsdl	2
taxfreeprice_cola_service.wsdl	2
price_drinks_service.wsdl	2
maxprice_drinks_Hotservice.wsdl	2
food_recommendedprice_service.wsdl	1
preparedfood_recommendedprice_service.wsdl	1
coffee_recommendedprice_service.wsdl	1
coffee_taxedprice_service.wsdl	1
maxprice_drinks_service.wsdl	1
recommendedprice_irishcoffee_service.wsdl	1
price_irishcoffeemixerycola_service.wsdl	1
maxprice_whiskeycolabeer_service.wsdl	1
coffee_maxprice_service.wsdl	1
price_coffeewithwhiskey_service.wsdl	1
monographpersoncreditcardaccount_recommendedprice_service.wsdl	0
SFNovelReview_service.wsdl	0
sciencefictionbook_authorprice_service.wsdl	0
romanticnovel_authormaxprice_service.wsdl	0
monograph_price_service.wsdl	0
book_Cheapestprice_service.wsdl	0
maxprice_beercola_service.wsdl	0
book_publisher_service.wsdl	0
monograph_recommendedpriceineuro_service.wsdl	0
book_taxedprice_service.wsdl	0
book_person_Publisherservice.wsdl	0
maxprice_cola_Bestservice.wsdl	0
price_cola_Gudduservice.wsdl	0
encyclopedia_authorbook-type_service.wsdl	0
book_pricereviewbook_service.wsdl	0
short-story_authorprice_service.wsdl	0
novel_authorrecommendedprice_service.wsdl	0
romanticnovel_authorbook-type_service.wsdl	0
novel_publisher_service.wsdl	0
tea_recommendedprice_service.wsdl	0
encyclopedia_author_service.wsdl	0
degreegovernment_funding_service.wsdl	0
untangibleobjects_cola_service.wsdl	0
sciencefictionbook_authormaxprice_service.wsdl	0
sciencefictionbook_authortaxedprice_service.wsdl	0
romanticnovel_authorrecommendedprice_service.wsdl	0
novel_userreviewauthor_service.wsdl	0
BookPrice.wsdl	0
governmentorganization_scholarship_service.wsdl	0
coffeesandwich_price_service.wsdl	0
sciencefictionbook_publisher_service.wsdl	0
novel_person_Reserverservice.wsdl	0
book_readerreview_service.wsdl	0
sciencefictionbook_author_service.wsdl	0
novel_price_service.wsdl	0
book_price_service.wsdl	0
novel_authortaxedprice_service.wsdl	0
book_authorbook-type_service.wsdl	0
title_filmrecommendedpricequality_service.wsdl	0
Tizonbook_recommendedpriceindollar_service.wsdl	0
_coffeeteareport_service.wsdl	0
novel_person_Writerservice.wsdl	0
novel_author_MyOntoservice.wsdl	0
short-story_authortaxedprice_service.wsdl	0
novel_authormaxprice_service.wsdl	0
book_author_service.wsdl	0
short-story_authorbook-type_service.wsdl	0
short-story_authorrecommendedprice_service.wsdl	0
book_recommendedprice_RegisteredUserservice.wsdl	0
SFNRecommendedPrice_service.wsdl	0
novel_authorprice_service.wsdl	0
price_cola_Halloservice.wsdl	0
romanticnovel_publisher_service.wsdl	0
book_recommendedpriceindollar_service.wsdl	0
_videomediaSmithLee_service.wsdl	0
sciencefictionbook_authorrecommendedprice_service.wsdl	0
sciencefictionnovel_author_MyOntoservice.wsdl	0
sciencefictionbook_authorbook-type_service.wsdl	0
car_recommendedprice_service.wsdl	0
encyclopedia_publisher_service.wsdl	0
book_taxedpriceprice_service.wsdl	0
novel_authorbook-type_service.wsdl	0
objectpersoncreditaccount_price_service.wsdl	0
price_cola_Hallo2service.wsdl	0
romanticnovel_authorprice_service.wsdl	0
book_readerreviewperson_service.wsdl	0
university_lecturer-in-academia_Recommendservice.wsdl	0
fantansynoveluser_price_service.wsdl	0
car_recommendedpriceindollar_service.wsdl	0
bookpersoncreditcardaccount_recommendedprice_service.wsdl	0
maxprice_cola_service.wsdl	0
science-fiction-noveluser_recommendedpriceindollar_service.wsdl	0
book_author_EncSSservice.wsdl	0
book_recommendedprice_service.wsdl	0
ScienceFNovelReview_service.wsdl	0
title_mediarecommendedpricequality_service.wsdl	0
book_reviewprice_service.wsdl	0
