book_taxedpriceprice_service.wsdl	3
printedmaterial_price_service.wsdl	3
book_reviewprice_service.wsdl	3
DeoSFN_price_service.wsdl	3
science-fiction-noveluser_recommendedpriceindollar_service.wsdl	3
novel_authortaxedprice_service.wsdl	3
book_taxedprice_service.wsdl	3
book_price_service.wsdl	3
science-fiction-novel_authorprice_service.wsdl	3
userscience-fiction-novel_price_service.wsdl	3
userscience-fiction-novel_Relprice_service.wsdl	3
bookpersonOptional_price_service.wsdl	3
userbook_price_service.wsdl	3
sciencefictionbookuser_price_service.wsdl	3
userscience-fiction-novel_price_Bestservice.wsdl	3
bookperson_price_service.wsdl	3
novelperson_price_service.wsdl	3
ScienceFNovelReview_service.wsdl	2
Tizonbook_recommendedpriceindollar_service.wsdl	2
bookpersoncreditcardaccount_price_service.wsdl	2
novel_authorprice_service.wsdl	2
science-fiction-novel_priceauthor_service.wsdl	2
book_Cheapestprice_service.wsdl	2
sciencefictionbook_authorprice_service.wsdl	2
novel_price_service.wsdl	2
BookPrice.wsdl	2
book_pricereviewbook_service.wsdl	2
SFNovelReview_service.wsdl	2
book_pricesizebook-type_service.wsdl	2
book_authorprice_Novelservice.wsdl	2
SFNRecommendedPrice_service.wsdl	2
monograph_price_service.wsdl	2
short-story_authormaxprice_service.wsdl	1
author_monographprice_service.wsdl	1
objectpersoncreditaccount_price_service.wsdl	1
shoppingmall_purchaseableitemprice_service.wsdl	1
author_bookprice_service.wsdl	1
romanticnovel_authormaxprice_service.wsdl	1
sciencefictionbook_authorrecommendedprice_service.wsdl	1
author_novelrecommendedprice_service.wsdl	1
romanticnovel_authorprice_service.wsdl	1
sciencefictionbook_authortaxedprice_service.wsdl	1
romanticnovel_authortaxedprice_service.wsdl	1
author_novelprice_service.wsdl	1
author_sciencefictionbookmaxprice_service.wsdl	1
author_publicationprice_service.wsdl	1
novel_authorrecommendedprice_service.wsdl	1
short-story_authorprice_service.wsdl	1
bookpersoncreditcardaccount_recommendedprice_service.wsdl	1
userRomanticnovel_price_service.wsdl	1
monograph_recommendedpriceineuro_service.wsdl	1
novel_authormaxprice_service.wsdl	1
short-story_authortaxedprice_service.wsdl	1
author_sciencefictionbookprice_service.wsdl	1
author_sciencefictionbooktaxedprice_service.wsdl	1
fantansynoveluser_price_service.wsdl	1
science-fiction-novel_authortaxedprice_service.wsdl	1
author_sciencefictionbooktaxfreeprice_service.wsdl	1
author_noveltaxedprice_service.wsdl	1
science-fiction-novel_authorrecommendedprice_service.wsdl	1
short-story_authorrecommendedprice_service.wsdl	1
book_recommendedpriceindollar_service.wsdl	1
book_recommendedprice_RegisteredUserservice.wsdl	1
author_sciencefictionbookrecommendedprice_service.wsdl	1
science-fiction-novel_authormaxprice_service.wsdl	1
romanticnovel_authorrecommendedprice_service.wsdl	1
sciencefictionbook_authormaxprice_service.wsdl	1
user_price_ShoppingStatusservice.wsdl	1
book_recommendedprice_service.wsdl	1
book_authorprice_service.wsdl	0
3wheeledcar_price_service.wsdl	0
preparedfood_taxedprice_service.wsdl	0
autobicycle_price_service.wsdl	0
apple_price_service.wsdl	0
novel_authortime_service.wsdl	0
amount-of-moneyexpensivecar_price_service.wsdl	0
romanticnovel_publisher_service.wsdl	0
science-fiction-novel_publisher_service.wsdl	0
preparedfood_taxedpriceindollarprice_service.wsdl	0
food_price_AnimalFoodservice.wsdl	0
1personbicycle4wheeledcar_price_service.wsdl	0
food_price_service.wsdl	0
4wheeledcaryear_pricereport_service.wsdl	0
mp3playerportabledvdplayer_price_service.wsdl	0
grocerystore_preparedfoodprice_service.wsdl	0
beverage_pricephysical-quantity_Aldiservice.wsdl	0
4wheeledcar1personbicycle_price_service.wsdl	0
MerkelD_service.wsdl	0
grocerystore_teaprice_service.wsdl	0
shoppingmall_digital-slrpricecalendar-date_service.wsdl	0
PhillipDigCamera_price_service.wsdl	0
sciencefictionbook_authorbook-type_service.wsdl	0
food_pricequantity_Aldiservice.wsdl	0
4wheeledcarbicycle_price_service.wsdl	0
car_pricequality_service.wsdl	0
sfnovel_authorauthor_BookOntoservice.wsdl	0
auto_yearprice_service.wsdl	0
pea_price_service.wsdl	0
4wheeledcar_yearprice_service.wsdl	0
beverage_pricequantity_Aldiservice.wsdl	0
mediaplayer_price_service.wsdl	0
coconut_price_service.wsdl	0
shoppingmall_calendar-datepricecamera_service.wsdl	0
2personbicycle4wheeledcar_price_service.wsdl	0
shoppingmall_compactprice_service.wsdl	0
bicycle4wheeledcar_price_service.wsdl	0
amount-of-moneycar_price_service.wsdl	0
carbicycle_price_service.wsdl	0
avocado_price_service.wsdl	0
4wheeledcar_price_service.wsdl	0
sciencefictionbook_publisher_service.wsdl	0
car2personbicycle_price_service.wsdl	0
EntranceFee_service.wsdl	0
EntranceFeeindollar_service.wsdl	0
novelperson__Reservationservice.wsdl	0
novel_author_service.wsdl	0
dvdplayermp3player_price_Rservice.wsdl	0
car_price_service.wsdl	0
novel_person_Reserverservice.wsdl	0
novel_author_MyOntoservice.wsdl	0
amount-of-money4wheeledcar_price_service.wsdl	0
lemonfruit_price_service.wsdl	0
carcycle_price_service.wsdl	0
retailstore_compactprice_service.wsdl	0
machine_price_service.wsdl	0
food_pricephysical-quantity_Aldiservice.wsdl	0
1personbicyclecar_price_Kohlservice.wsdl	0
4wheeledcaryear_price_service.wsdl	0
MarkoPS_service.wsdl	0
car_yearprice_service.wsdl	0
shoppingmall_cameraprice_service.wsdl	0
shoppingmall_pricecellphonewithcamera_service.wsdl	0
dvdplayermp3player_price_service.wsdl	0
amount-of-money3wheeledcar_price_service.wsdl	0
novel_authorbook-type_service.wsdl	0
1personbicyclecar_price_TheBestservice.wsdl	0
bookusercreditcardaccount__service.wsdl	0
mercantileorganization_compactprice_service.wsdl	0
novel_userreviewauthor_service.wsdl	0
car_priceauto_service.wsdl	0
rawfood_price_service.wsdl	0
amount-of-moneycheapcar_price_service.wsdl	0
bicyclecar_priceyear_service.wsdl	0
honey_price_service.wsdl	0
3wheeledcaryear_price_service.wsdl	0
auto_pricecolor_service.wsdl	0
novel_authorgenre_service.wsdl	0
encyclopedia_price_service.wsdl	0
car_pricereport_service.wsdl	0
4wheeledcar2personbicycle_price_service.wsdl	0
shoppingmall_pricepurchaseableitemrange_service.wsdl	0
retailstore_slrprice_service.wsdl	0
datefruit_price_service.wsdl	0
book_person_Publisherservice.wsdl	0
meat_pricephysical-quantity_Aldiservice.wsdl	0
electricdevice_price_service.wsdl	0
meat_pricequantity_Aldiservice.wsdl	0
sciencefictionnovel_author_MyOntoservice.wsdl	0
book_publisher_service.wsdl	0
cdplayermp3player_price_service.wsdl	0
auto1personbicycle_price_service.wsdl	0
shoppingmall_analogpricecalendar-date_service.wsdl	0
shoppingmall_pricedigitalanalog_service.wsdl	0
romanticnovel_authorbook-type_service.wsdl	0
auto2personbicycle_price_service.wsdl	0
auto_price_service.wsdl	0
preparedfood_price_service.wsdl	0
_3WheeledAudiCarprice_service.wsdl	0
amount-of-moneycar_pricecompany_service.wsdl	0
cyclecar_pricetaxedprice_service.wsdl	0
novel_author_BookOntoservice.wsdl	0
novel_person_Writerservice.wsdl	0
bicycleauto_price_service.wsdl	0
car_taxedpriceprice_service.wsdl	0
_3WheeledOpelCarPrice_service.wsdl	0
preparedfood_priceday_service.wsdl	0
sciencefictionbook_author_service.wsdl	0
preparedfood_maxprice_service.wsdl	0
bicyclecar_price_service.wsdl	0
1personbicyclecar_price_service.wsdl	0
shoppingmall_slrprice_service.wsdl	0
science-fiction-novel_authorbook-type_service.wsdl	0
novel_publisher_service.wsdl	0
mercantileorganization_slrprice_service.wsdl	0
mp3playercdplayermicrowaveoven_price_service.wsdl	0
agent_price_MianMarktservice.wsdl	0
autocycle_price_service.wsdl	0
